In [1]:
import numpy as np
import pandas as pd

In [2]:
flats = pd.read_csv('flats_cleaned.csv')
house = pd.read_csv('house_cleaned.csv')

In [3]:
df = pd.concat([flats,house],ignore_index = True)

In [4]:
df.shape

(3953, 20)

In [5]:
df = df.sample(df.shape[0] , ignore_index = True)

In [6]:
df.head()

,property_name,property_type,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,4 Bedroom House for sale in DLF Phase 4,house,independent,4.50,125000.0,360.0,Built Up area: 360 (33.45 sq.m.),4,4,0,not available,"Dlf City Phase 4, Sector 28, DLF Phase 4, Gurg...",4.0,NaN,undefined,NaN,Best in class property available at dlf city p...,"['1 Light', 'No AC', 'No Bed', 'No Chimney', '...",NaN,"['Environment5 out of 5', 'Lifestyle4 out of 5..."
1,3 BHK Flat in Sector 66 Gurgaon,flat,emaar mgf the palm drive,2.80,14358.0,1950.0,Super Built up area 1950(181.16 sq.m.)Built Up...,3,3,2,"servant room,study room,pooja room","Sector 66 Gurgaon, Gurgaon, Haryana",12.0,East,0 to 1 Year Old,"['Sector 55-56 Rapid Metro Station', 'HUB 66',...",Emaar palm drive apartment available for sale ...,"['6 Fan', '1 Fridge', '1 Exhaust Fan', '1 Dini...","['Security / Fire Alarm', 'Power Back-up', 'In...","['Green Area5 out of 5', 'Construction4.5 out ..."
2,3 BHK Flat in Sector 104 Gurgaon,flat,hero homes,1.90,11249.0,1689.0,Super Built up area 1689(156.91 sq.m.)Carpet a...,3,3,3,pooja room,"Sector 104 Gurgaon, Gurgaon, Haryana",16.0,NaN,Mar 2025,"['Basai Metro Station', 'HUDA Market', 'Dwarka...",Property located bang on dwarka expressway,"['1 Water Purifier', '1 Exhaust Fan', '3 Geyse...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Environment4 out of 5', 'Lifestyle4 out of 5..."
3,5 Bedroom House for sale in Nirvana Country,house,independent,10.56,32593.0,3240.0,Plot area 360(301.01 sq.m.),5,5,3,servant room,"Nirvana Country, Gurgaon, Haryana",3.0,NaN,5 to 10 Year Old,"['Radhakrishna Shani Mandir', 'Standard charte...",Urgent for sale\nOn main wide road\nConfirm de...,NaN,"['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
4,2 BHK Flat in Shanti Nagar,flat,ganga apartment,0.55,3352.0,1641.0,Super Built up area 1700(157.94 sq.m.)Built Up...,2,2,1,not available,"Shanti Nagar, Gurgaon, Haryana",3.0,North-East,5 to 10 Year Old,"['Rajiv Chowk Mosque', 'Hanuman Mandir', 'Stat...","Cash payment can be accepted\nPrime location ,...","['4 Fan', '1 Exhaust Fan', '1 Dining Table', '...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Safety4 out of 5', 'Lifestyle4 out of 5', 'E..."

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3953 entries, 0 to 3952
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   property_name    3953 non-null   object
 1   property_type    3953 non-null   object
 2   society          3952 non-null   object
 3   price            3933 non-null   float64
 4   price_per_sqft   3933 non-null   float64
 5   area             3933 non-null   float64
 6   areaWithType     3953 non-null   object
 7   bedRoom          3953 non-null   int64
 8   bathroom         3953 non-null   int64
 9   balcony          3953 non-null   object
 10  additionalRoom   3953 non-null   object
 11  address          3943 non-null   object
 12  floorNum         3929 non-null   float64
 13  facing           2783 non-null   object
 14  agePossession    3952 non-null   object
 15  nearbyLocations  3750 non-null   object
 16  description      3953 non-null   object
 17  furnishDetails   2927 non-null   object
 18  features         3251 non-null   object
 19  rating           3503 non-null   object
dtypes: float64(4), int64(2), object(14)
memory usage: 617.8+ KB

In [8]:
df.to_csv('gurgaon_properties.csv', index = False)