In [1]:
import numpy as np
import pandas as pd

In [3]:
pd.set_option('display.max_rows',None)
pd.set_option('display.max_columns',None)

In [6]:
df=pd.read_csv('flats.csv')
df.sample(3)

,property_name,link,society,price,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating,property_id
2330,3 BHK Flat in Sector 89 Gurgaon,https://www.99acres.com/3-bhk-bedroom-apartmen...,Smart World Gems,1.2 Crore,"₹ 8,432/sq.ft.",Built Up area: 1423 (132.2 sq.m.),3 Bedrooms,3 Bathrooms,2 Balconies,"Study Room,Others","Sector 89 Gurgaon, Gurgaon, Haryana",3rd of 4 Floors,East,Within 6 months,"['Sant Soordas Sihi Metro Station', 'Airia Mal...","Well connected with dwarka expressway, nh-8, s...",NaN,"['Security / Fire Alarm', 'Lift(s)', 'Maintena...","['Environment4 out of 5', 'Lifestyle4 out of 5...",Q69481026
1698,3 BHK Flat in Nirvana Country,https://www.99acres.com/3-bhk-bedroom-apartmen...,The Close North4.0 ★,2.65 Crore,"₹ 11,276/sq.ft.",Super Built up area 2605(242.01 sq.m.)Built Up...,3 Bedrooms,3 Bathrooms,3+ Balconies,Servant Room,"Higher Floor, Nirvana Country, Gurgaon, Haryana",3rd of 18 Floors,South-East,5 to 10 Year Old,"['Sector 55-56 Metro Station', 'Eros City Squa...","Situated in nirvana country, gurgaon, the clos...",NaN,"['Centrally Air Conditioned', 'Water purifier'...","['Green Area5 out of 5', 'Construction4 out of...",G69221508
1340,4 BHK Flat in Sector 92 Gurgaon,https://www.99acres.com/4-bhk-bedroom-apartmen...,Sare Homes,1.1 Crore,"₹ 5,347/sq.ft.",Carpet area: 2057 (191.1 sq.m.),4 Bedrooms,4 Bathrooms,3 Balconies,Servant Room,"403, Sector 92 Gurgaon, Gurgaon, Haryana",4th of 21 Floors,North-West,1 to 5 Year Old,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",Sare homes is one of the most popular destinat...,NaN,"['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Environment5 out of 5', 'Lifestyle4 out of 5...",V69811272

In [7]:
df.shape

(3028, 20)

In [9]:
# i have seen in excel that some rows should be deleted toh mei abhi karra
df.iloc[2995:3007,:] # observed from MS EXcel

,property_name,link,society,price,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating,property_id
2995,3 BHK Flat in Sector 9A Gurgaon,https://www.99acres.com/3-bhk-bedroom-apartmen...,Jammu and Kashmir Bank Employees CGHS3.7 ★,NaN,"₹ 6,129/sq.ft.",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2996,3 BHK Flat in Sector 37C Gurgaon,https://www.99acres.com/3-bhk-bedroom-apartmen...,ILD Greens4.1 ★,NaN,"₹ 4,723/sq.ft.",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2997,3 BHK Flat in Adarsh Nagar,https://www.99acres.com/3-bhk-bedroom-apartmen...,ss residency,NaN,"₹ 4,818/sq.ft.",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2998,3 BHK Flat in Rajendra Park,https://www.99acres.com/3-bhk-bedroom-apartmen...,Uphar lakshya homes,NaN,"₹ 4,200/sq.ft.",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2999,2 BHK Flat in Sector 79 Gurgaon,https://www.99acres.com/2-bhk-bedroom-apartmen...,Supertech Araville,NaN,"₹ 9,000/sq.ft.",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3000,3 BHK Flat in Sector 37C Gurgaon,https://www.99acres.com/3-bhk-bedroom-apartmen...,Corona Optus3.9 ★,NaN,"₹ 6,361/sq.ft.",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3001,3 BHK Flat in Sector 78 Gurgaon,https://www.99acres.com/3-bhk-bedroom-apartmen...,Umang Monsoon Breeze,NaN,"₹ 6,493/sq.ft.",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3002,3 BHK Flat in Sector 88A Gurgaon,https://www.99acres.com/3-bhk-bedroom-apartmen...,Godrej Oasis3.9 ★,NaN,"₹ 8,108/sq.ft.",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3003,"2 BHK Flat in Godrej Aria , sector 79 , Gurgaon",https://www.99acres.com/2-bhk-bedroom-apartmen...,"Godrej Aria , sector 79 , Gurgaon",NaN,"₹ 11,111/sq.ft.",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3004,4 BHK Flat in DLF Phase 4,https://www.99acres.com/4-bhk-bedroom-apartmen...,Chanderlok Society,90 Lac,"₹ 7,234/sq.ft.",Carpet area: 1244 (115.57 sq.m.),4 Bedrooms,2 Bathrooms,3+ Balconies,NaN,"DLF Phase 4, Gurgaon, Haryana",1st of 2 Floors,NaN,10+ Year Old,"['Iffco chowk metro station', 'Mg road metro s...",Walking distance from mg metro station and gal...,NaN,NaN,"['Safety5 out of 5', 'Lifestyle4 out of 5', 'E...",M56674250
3005,3 BHK Flat in Sector 9A Gurgaon,https://www.99acres.com/3-bhk-bedroom-apartmen...,Jammu and Kashmir Bank Employees CGHS3.7 ★,95 Lac,"₹ 6,129/sq.ft.",Super Built up area 1550(144 sq.m.),3 Bedrooms,3 Bathrooms,2 Balconies,Others,"Sector 9A Gurgaon, Gurgaon, Haryana",5th of 5 Floors,West,5 to 10 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Shri...",We are the proud owners of this 3 bhk apartmen...,"['2 Wardrobe', '4 Fan', '3 Geyser', 'No AC', '...","['Lift(s)', 'Maintenance Staff', 'Park', 'Visi...","['Management4 out of 5', 'Green Area4 out of 5...",E45070641
3006,3 BHK Flat in Sector 37C Gurgaon,https://www.99acres.com/3-bhk-bedroom-apartmen...,ILD Greens4.1 ★,1 Crore,"₹ 4,723/sq.ft.",Super Built up area 1800(167.23 sq.m.),3 Bedrooms,3 Bathrooms,3 Balconies,NaN,"Sector 37C Gurgaon, Gurgaon, Haryana",3rd of 15 Floors,NaN,Under Construction,"['The Esplanade Mall', 'Gurgaon Road', 'Delhi ...",Residential apartment for sell.Located on 3rd ...,[],NaN,"['Management4.5 out of 5', 'Green Area5 out of...",P33152685

In [11]:
df.drop([i for i in range(2995,3007)] , inplace = True)

In [12]:
# now again verify

In [13]:
df.iloc[2995:3006,:]

,property_name,link,society,price,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating,property_id
3007,3 BHK Flat in Adarsh Nagar,https://www.99acres.com/3-bhk-bedroom-apartmen...,ss residency,53 Lac,"₹ 4,818/sq.ft.",Super Built up area 1100(102.19 sq.m.),3 Bedrooms,3 Bathrooms,2 Balconies,NaN,"Adarsh Nagar, Gurgaon, Haryana",2nd of 4 Floors,NaN,1 to 5 Year Old,"['Hanuman Mandir', 'State bank of india ATM', ...",Residential apartment for sell.The property ha...,"['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '10 L...","['Intercom Facility', 'Lift(s)', 'Water Storage']",NaN,F55342964
3008,3 BHK Flat in Rajendra Park,https://www.99acres.com/3-bhk-bedroom-apartmen...,Uphar lakshya homes,42 Lac,"₹ 4,200/sq.ft.",Carpet area: 1000 (92.9 sq.m.),3 Bedrooms,2 Bathrooms,1 Balcony,NaN,"Rajendra Park, Gurgaon, Haryana",1st of 4 Floors,East,1 to 5 Year Old,"['Palam Vihar Vyapar kendra', 'Chintapurni Man...",Best location with nearby gurgaon railway stat...,NaN,"['Lift(s)', 'Visitor Parking']","['Safety4 out of 5', 'Lifestyle4 out of 5', 'E...",S57817870
3009,2 BHK Flat in Sector 79 Gurgaon,https://www.99acres.com/2-bhk-bedroom-apartmen...,Supertech Araville,1.35 Crore,"₹ 9,000/sq.ft.",Super Built up area 1530(142.14 sq.m.)Built Up...,2 Bedrooms,2 Bathrooms,3 Balconies,"Study Room,Others","Naurangpur, Delhi-Jaipur Highway, Sector 79 Gu...",6th of 18 Floors,East,0 to 1 Year Old,"['Petrol Pump Indian Oil', 'Petrol Pump', 'Rao...",East facing flat in tower e with a good view o...,"['1 Wardrobe', '1 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Safety4 out of 5', 'Lifestyle3 out of 5', 'E...",L21848441
3010,3 BHK Flat in Sector 37C Gurgaon,https://www.99acres.com/3-bhk-bedroom-apartmen...,Corona Optus3.9 ★,1.5 Crore,"₹ 6,361/sq.ft.",Super Built up area 2358(219.07 sq.m.),3 Bedrooms,4 Bathrooms,3+ Balconies,"Servant Room,Others","Tower J, 14th Floor, Sector 37C Gurgaon, Gurga...",14th of 14 Floors,North-East,0 to 1 Year Old,"['The Esplanade Mall', 'Gurugram Road', 'Delhi...",Property is a specious park facing and north f...,"['3 Wardrobe', '7 Fan', '3 Geyser', '15 Light'...","['Security / Fire Alarm', 'Intercom Facility',...","['Management4 out of 5', 'Green Area5 out of 5...",Z42491213
3011,3 BHK Flat in Sector 78 Gurgaon,https://www.99acres.com/3-bhk-bedroom-apartmen...,Umang Monsoon Breeze,1.2 Crore,"₹ 6,493/sq.ft.",Super Built up area 2250(209.03 sq.m.)Carpet a...,3 Bedrooms,3 Bathrooms,2 Balconies,Pooja Room,"Sector 78 Gurgaon, Gurgaon, Haryana",8th of 12 Floors,NaN,5 to 10 Year Old,"['Proposed Metro Station', 'Mahapal Shing', 'N...","A 3 bedroom flat, located in sector-78 gurgaon...","['1 Water Purifier', '1 Fridge', '5 Fan', '1 E...","['Piped-gas', 'Natural Light']","['Safety4 out of 5', 'Lifestyle4 out of 5', 'E...",R61360534
3012,3 BHK Flat in Sector 88A Gurgaon,https://www.99acres.com/3-bhk-bedroom-apartmen...,Godrej Oasis3.9 ★,1.5 Crore,"₹ 8,108/sq.ft.",Carpet area: 1850 (171.87 sq.m.),3 Bedrooms,3 Bathrooms,2 Balconies,NaN,"Sector 88A Gurgaon, Gurgaon, Haryana",3rd of 17 Floors,NaN,1 to 5 Year Old,"['Double Infinity market', 'Pataudi road', 'Dw...",We are the proud owners of this 3 bhk apartmen...,"['3 AC', 'No Bed', 'No Chimney', 'No Curtains'...","['Lift(s)', 'Swimming Pool', 'Park', 'Visitor ...","['Management4.5 out of 5', 'Green Area5 out of...",O53137952
3013,"2 BHK Flat in Godrej Aria , sector 79 , Gurgaon",https://www.99acres.com/2-bhk-bedroom-apartmen...,"Godrej Aria , sector 79 , Gurgaon",1.5 Crore,"₹ 11,111/sq.ft.",Carpet area: 1350 (125.42 sq.m.),2 Bedrooms,2 Bathrooms,3+ Balconies,NaN,"Flat D 0704 , 7th Floor ,godrej Aria, Godrej A...",7th of 13 Floors,North-East,0 to 1 Year Old,"['Hanuman Mandir', 'Sharma Hospital Gurgaon', ...","2 bedroom flat d 0704 , 7th floor ,godrej aria...","['5 Fan', '1 Exhaust Fan', '1 Geyser', '10 Lig...","['Security / Fire Alarm', 'Intercom Facility',...",NaN,S61001204
3014,3 BHK Flat in Sector 92 Gurgaon,https://www.99acres.com/3-bhk-bedroom-apartmen...,Raheja Sampada,90 Lac,"₹ 6,569/sq.ft.",Super Built up area 1370(127.28 sq.m.),3 Bedrooms,2 Bathrooms,3 Balconies,NaN,"Sector 92 Gurgaon, Gurgaon, Haryana",11st of 14 Floors,East,1 to 5 Year Old,"['Sapphire 93', 'JMS crosswalk', 'Reliance Sma...",We are the proud owners of this 3 bhk apartmen...,NaN,"['Security / Fire Alarm', 'Power Back-up', 'Fe...","['Safety3 out of 5', 'Lifestyle4 out of 5', 'E...",I56902148
3015,4 BHK Flat in Sector 92 Gurgaon,https://www.99acres.com/4-bhk-bedroom-apartmen...,Sare Green ParC Phase 3,1.08 Crore,"₹ 5,150/sq.ft.",Super Built up area 2090(194.17 sq.m.),4 Bedrooms,4 Bathrooms,2 Balconies,Servant Room,NaN,16th of 19 Floors,NaN,0 to 1 Year Old,"['Huda Metro Station', 'Sector Road', 'Delhi-J...",Only end user and buyers to contact. Flat in r...,NaN,"['Security / Fire Alarm', 'Intercom Facility',...","['Safety3 out of 5', 'Lifestyle4 out of 5', 'E...",A46782853
3016,2 BHK Flat in Sector 92 Gurgaon,https://www.99acres.com/2-bhk-bedroom-apartmen...,Raheja Navodaya3.6 ★,62.5 Lac,"₹ 4,807/sq.ft.",Built Up area: 1498 (139.17 sq.m.)Carpet area:...,2 Bedrooms,2 Bathrooms,2 Balconies,NaN,"Sector 92 Gurgaon, Gurgaon, Haryana",5th of 15 Floors,NaN,0 to 1 Year Old,"['NH8', 'Dwarka Expressway', 'IMT Manesar', 'Y...",Brand new residential apartment for sell.Locat...,[],NaN,"['Management4 out of 5', 'Green Area5 out of 5...",B24118357
3017,4 BHK Flat in Sector 68 Gurgaon,https://www.99acres.com/4-bhk-bedroom-apartmen...,Pareena Mi Casa,1.7 Crore,"₹ 8,500/sq.ft.",Super Built up area 1999(185.71 sq.m.),4 Bedrooms,4 Bathrooms,3+ Balconies,NaN,"2304, Sector 68 Gurgaon, Gurgaon, Haryana",23rd of 36 Floors,NaN,0 to 1 Year Old,"['Sector 55-56 Metro Station', 'Airia Mall', '...",The property is on the 23rd floor with an road...,"['1 Modular Kitchen', 'No AC', 'No Bed', 'No C...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Safety5 out of 5', 'Lifestyle4 out of 5', 'E...",Z45897659

In [18]:
df.iloc[2850:2855,:] # observed from MS EXCEL again

,property_name,link,society,price,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating,property_id
2850,2 BHK Flat in Sector 107 Gurgaon,https://www.99acres.com/2-bhk-bedroom-apartmen...,Signature Global Solera3.7 ★,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2851,4 BHK Flat in Sector 53 Gurgaon,https://www.99acres.com/4-bhk-bedroom-apartmen...,Tulip Monsella,NaN,"₹ 33,198/sq.ft.",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2852,2 BHK Flat in New Palam Vihar,https://www.99acres.com/2-bhk-bedroom-apartmen...,My Home,NaN,"₹ 4,400/sq.ft.",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2853,2 BHK Flat in Sohna,https://www.99acres.com/2-bhk-bedroom-apartmen...,Breez Global Hill View,NaN,"₹ 5,470/sq.ft.",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2854,4 BHK Flat in Sector 53 Gurgaon,https://www.99acres.com/4-bhk-bedroom-apartmen...,Tulip Monsella,7.4 Crore,"₹ 33,198/sq.ft.",Carpet area: 2229 (207.08 sq.m.),4 Bedrooms,4 Bathrooms,3 Balconies,NaN,"Sector 53 Gurgaon, Gurgaon, Haryana",21st of 36 Floors,NaN,Jun 2027,"['Sector 53-54 Metro Station', 'Central Plaza ...","The platinum collection by tulip group, driven...","['1 Wardrobe', '1 Geyser', '1 Light', '1 AC', ...","['Feng Shui / Vaastu Compliant', 'Lift(s)', 'S...","['Safety4 out of 5', 'Lifestyle5 out of 5', 'E...",A66658898

In [20]:
df.drop([i for i in range(2850,2854)] , inplace = True)

In [22]:
df[df['property_name']=='property_name'] # again observed from MS excel

,property_name,link,society,price,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating,property_id
286,property_name,link,society,price,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating,property_id

In [23]:
df.drop([286],inplace= True)

In [24]:
df[df['property_name']=='property_name'] # verrify

Empty DataFrame
Columns: [property_name, link, society, price, area, areaWithType, bedRoom, bathroom, balcony, additionalRoom, address, floorNum, facing, agePossession, nearbyLocations, description, furnishDetails, features, rating, property_id]
Index: []

In [25]:
df.shape

(3011, 20)

In [26]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3011 entries, 0 to 3027
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   property_name    3011 non-null   object
 1   link             3011 non-null   object
 2   society          3010 non-null   object
 3   price            3004 non-null   object
 4   area             2999 non-null   object
 5   areaWithType     3005 non-null   object
 6   bedRoom          3005 non-null   object
 7   bathroom         3005 non-null   object
 8   balcony          3005 non-null   object
 9   additionalRoom   1693 non-null   object
 10  address          2999 non-null   object
 11  floorNum         3003 non-null   object
 12  facing           2126 non-null   object
 13  agePossession    3004 non-null   object
 14  nearbyLocations  2910 non-null   object
 15  description      3005 non-null   object
 16  furnishDetails   2201 non-null   object
 17  features         2593 non-null   object
 18  rating           2673 non-null   object
 19  property_id      3005 non-null   object
dtypes: object(20)
memory usage: 494.0+ KB

In [27]:
df[df['area'].isnull()]

,property_name,link,society,price,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating,property_id
18,2 BHK Flat in Sector 93 Gurgaon,https://www.99acres.com/2-bhk-bedroom-apartmen...,Signature Global Orchard Avenue 2,NaN,NaN,Carpet area: 577.11 (53.62 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,NaN,"L-1104, Sector 93 Gurgaon, Gurgaon, Haryana",11st of 14 Floors,East,Under Construction,"['Huda Metro Station', 'V3S Sapphire Ninety', ...",Looking for a budget-Friendly 2 bhk flat in a ...,NaN,"['Security / Fire Alarm', 'Feng Shui / Vaastu ...",NaN,H68815396
25,5 BHK Flat in Sector 1 Gurgaon,https://www.99acres.com/5-bhk-bedroom-apartmen...,The New People Apartments,Price on Request,NaN,Built Up area: 4500 (418.06 sq.m.),5 Bedrooms,1 Bathroom,No Balcony,NaN,"Sector 1, Sector 1 Gurgaon, Gurgaon, Haryana",Ground of 1 Floors,NaN,undefined,"['Pooja Clinic', 'Dr. Sahil Clinic', 'Prakash ...",Best in class property available at sector 1 l...,NaN,NaN,NaN,Z68804716
1645,4 BHK Flat in Sector 50 Gurgaon,https://www.99acres.com/4-bhk-bedroom-apartmen...,SS Hibiscus,Price on Request,NaN,Carpet area: 4800 (445.93 sq.m.),4 Bedrooms,4 Bathrooms,3 Balconies,Servant Room,"Sector 50 Gurgaon, Gurgaon, Haryana",7th of 18 Floors,East,5 to 10 Year Old,"['Baani Square', 'SS Plaza', 'Good Earth City ...",4bedroom 4800sq.Ft middle floor apartment avai...,"['4 Fan', '8 Light', 'No AC', 'No Bed', 'No Ch...","['Lift(s)', 'Water purifier', 'Swimming Pool',...","['Environment5 out of 5', 'Lifestyle5 out of 5...",S65406842
1973,1 BHK Flat in Sector 31 Gurgaon,https://www.99acres.com/1-bhk-bedroom-apartmen...,Raheja Atlantis3.8 ★,Price on Request,NaN,Carpet area: 650 (60.39 sq.m.),1 Bedroom,1 Bathroom,1 Balcony,"Pooja Room,Study Room,Servant Room","Yes, Sector 31 Gurgaon, Gurgaon, Haryana",3rd of 15 Floors,East,0 to 1 Year Old,"['Huda Metro Station', 'Reliance Fresh, Indira...",It is my property and good condition and good ...,NaN,"['Feng Shui / Vaastu Compliant', 'Security / F...","['Green Area4 out of 5', 'Construction4 out of...",Q70122610
2055,2 BHK Flat in Sector 79 Gurgaon,https://www.99acres.com/2-bhk-bedroom-apartmen...,Supertech Araville,Price on Request,NaN,Built Up area: 1295 (120.31 sq.m.),2 Bedrooms,2 Bathrooms,No Balcony,NaN,"Sector 79, Sector 79 Gurgaon, Gurgaon, Haryana",15th of 15 Floors,NaN,undefined,NaN,"2 bath, unfurnished, 15th floor (Of 18), super...",NaN,NaN,"['Environment4 out of 5', 'Lifestyle3 out of 5...",M69984000
2358,2 BHK Flat in Sector 37D Gurgaon,https://www.99acres.com/2-bhk-bedroom-apartmen...,The Millennia 2,Price on Request,NaN,Carpet area: 552 (51.28 sq.m.),2 Bedrooms,1 Bathroom,1 Balcony,NaN,"Sector 37D Gurgaon, Gurgaon, Haryana",13rd of 13 Floors,NaN,undefined,"['Shri Balaji Hospital and Trauma Center', 'Sh...","1 bath, unfurnished, 13th floor (Of 13), at se...",NaN,NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5...",L69416788
2523,2 BHK Flat in Sector 95A Gurgaon,https://www.99acres.com/2-bhk-bedroom-apartmen...,The Roselia 2,Price on Request,NaN,Carpet area: 593 (55.09 sq.m.),2 Bedrooms,2 Bathrooms,2 Balconies,NaN,"Sector 95a, Pataudi Road, Sector 95A Gurgaon, ...",14th of 14 Floors,NaN,undefined,NaN,Best in class property available at sector 95a...,NaN,NaN,"['Environment5 out of 5', 'Lifestyle4.5 out of...",A69074608
2550,3 BHK Flat in Sector-2 Sohna,https://www.99acres.com/3-bhk-bedroom-apartmen...,Supertech Hilltown,Price on Request,NaN,Built Up area: 1720 (159.79 sq.m.),3 Bedrooms,3 Bathrooms,3 Balconies,NaN,"Sohna Sector 2,gurgaon, Sector-2 Sohna, Gurgao...",4th of 4 Floors,North-East,undefined,NaN,"3 bath, unfurnished, 4th floor (Of 4), overloo...",NaN,NaN,NaN,X66482366
2641,2 BHK Flat in Sector 95A Gurgaon,https://www.99acres.com/2-bhk-bedroom-apartmen...,The Roselia 2,Price on Request,NaN,Carpet area: 593 (55.09 sq.m.),2 Bedrooms,2 Bathrooms,2 Balconies,NaN,"Sector 95a, Pataudi Road, Sector 95A Gurgaon, ...",14th of 14 Floors,NaN,undefined,NaN,Best in class property available at sector 95a...,NaN,NaN,"['Environment5 out of 5', 'Safety5 out of 5', ...",A69074608
2960,3 BHK Flat in Sector 104 Gurgaon,https://www.99acres.com/3-bhk-bedroom-apartmen...,Godrej Summit3.7 ★,Price on Request,NaN,Super Built up area 1647(153.01 sq.m.)Carpet a...,3 Bedrooms,3 Bathrooms,3 Balconies,NaN,"1402, Sector 104 Gurgaon, Gurgaon, Haryana",14th of 17 Floors,NaN,1 to 5 Year Old,"['MG Road Metro Station', 'The Esplanade Mall'...",We are the proud owners of this 3 bhk apartmen...,[],"['Intercom Facility', 'Lift(s)', 'Maintenance ...","['Management3 out of 5', 'Green Area4.5 out of...",F62164440
2973,4 BHK Flat in Gwal Pahari,https://www.99acres.com/4-bhk-bedroom-apartmen...,Krrish Provence Estate,Price on Request,NaN,Built Up area: 5800 (538.84 sq.m.),4 Bedrooms,5 Bathrooms,1 Balcony,NaN,"Gwal Pahari, Gurgaon, Haryana",17th of 24 Floors,NaN,Under Construction,"['Tniy Toons School', 'Pathways School Gurgoan...",Residential apartment for sell.Located on 17th...,NaN,NaN,NaN,H28672425
2974,4 BHK Flat in Sector 95 Gurgaon,https://www.99acres.com/4-bhk-bedroom-apartmen...,Sidhartha NCR One Phase 24.1 ★,Price on Request,NaN,Super Built up area 2354(218.69 sq.m.),4 Bedrooms,4 Bathrooms,3+ Balconies,NaN,"Sector 95 Gurgaon, Gurgaon, Haryana",Ground of 3 Floors,North,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...","North facing entry, Very good layout, Excellen...",[],"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Management4 out of 5', 'Green Area4 out of 5...",E22752179

In [29]:
# checking for duplicate rows
df[df.duplicated()] # df.duplicated.sum()

Empty DataFrame
Columns: [property_name, link, society, price, area, areaWithType, bedRoom, bathroom, balcony, additionalRoom, address, floorNum, facing, agePossession, nearbyLocations, description, furnishDetails, features, rating, property_id]
Index: []

In [31]:
# checking for null values
df.isnull().sum()

property_name         0
link                  0
society               1
price                 7
area                 12
areaWithType          6
bedRoom               6
bathroom              6
balcony               6
additionalRoom     1318
address              12
floorNum              8
facing              885
agePossession         7
nearbyLocations     101
description           6
furnishDetails      810
features            418
rating              338
property_id           6
dtype: int64

In [32]:
# columns - not usefull
df.drop(columns=['link','property_id'] , inplace  = True)

In [33]:
df.head(3)

,property_name,society,price,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Krishna Colony,maa bhagwati residency,45 Lac,"₹ 5,000/sq.ft.",Carpet area: 900 (83.61 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"Krishna Colony, Gurgaon, Haryana",4th of 4 Floors,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ..."
1,2 BHK Flat in Ashok Vihar,Apna Enclave,50 Lac,"₹ 7,692/sq.ft.",Carpet area: 650 (60.39 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"46b, Ashok Vihar, Gurgaon, Haryana",1st of 3 Floors,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ..."
2,2 BHK Flat in Sohna,Tulsiani Easy in Homes,40 Lac,"₹ 6,722/sq.ft.",Carpet area: 595 (55.28 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,NaN,"Sohna, Gurgaon, Haryana",12nd of 14 Floors,NaN,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment4 out of 5', 'Safety4 out of 5', ..."

In [34]:
# one by one column observing
# area --> replace --> price_per_sqft
df.rename(columns = {'area':'price_per_sqft'},inplace = True);
df.head(3)

,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Krishna Colony,maa bhagwati residency,45 Lac,"₹ 5,000/sq.ft.",Carpet area: 900 (83.61 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"Krishna Colony, Gurgaon, Haryana",4th of 4 Floors,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ..."
1,2 BHK Flat in Ashok Vihar,Apna Enclave,50 Lac,"₹ 7,692/sq.ft.",Carpet area: 650 (60.39 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"46b, Ashok Vihar, Gurgaon, Haryana",1st of 3 Floors,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ..."
2,2 BHK Flat in Sohna,Tulsiani Easy in Homes,40 Lac,"₹ 6,722/sq.ft.",Carpet area: 595 (55.28 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,NaN,"Sohna, Gurgaon, Haryana",12nd of 14 Floors,NaN,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment4 out of 5', 'Safety4 out of 5', ..."

In [37]:
# property column on hold
# society 
df['society'].value_counts()

society
SS The Leaf3.8 ★                                     73
Tulip Violet4.3 ★                                    40
Shapoorji Pallonji Joyville Gurugram4.0 ★            39
Signature Global Park4.0 ★                           36
Shree Vardhman Victoria3.8 ★                         35
Tulip Violet4.2 ★                                    33
Emaar MGF Emerald Floors Premier3.8 ★                32
Smart World Gems                                     32
Smart World Orchard                                  32
Paras Dews                                           31
DLF The Ultima4.0 ★                                  31
DLF Regal Gardens3.9 ★                               30
M3M Woodshire4.0 ★                                   29
Shree Vardhman Flora3.8 ★                            29
La Vida by Tata Housing                              28
Godrej Nature Plus                                   27
Signature Global Solera3.7 ★                         27
BPTP Terra3.8 ★                                      25
Emaar Gurgaon Greens4.1 ★                            25
Eldeco Accolade3.8 ★                                 24
DLF New Town Heights 13.9 ★                          24
Vatika Gurgaon 213.7 ★                               24
Experion The Heartsong3.9 ★                          24
Bestech Park View Residency3.9 ★                     23
Tata Primanti4.1 ★                                   22
M3M Heights                                          22
ATS Triumph3.9 ★                                     22
Emaar Palm Gardens4.1 ★                              22
Sare Crescent Parc3.5 ★                              21
ROF Ananda                                           21
Experion Windchants3.8 ★                             20
Godrej 1014.0 ★                                      20
Antriksh Heights3.7 ★                                19
Sare Homes                                           19
ATS Tourmaline3.9 ★                                  18
Mapsko Mount Ville4.1 ★                              18
Ambience Creacions                                   18
CHD Avenue 713.6 ★                                   18
Indiabulls Centrum Park3.7 ★                         18
Supertech Araville                                   18
Sobha City                                           18
M3M Skywalk                                          17
Pareena Coban Residences                             17
M3M Golfestate4.4 ★                                  17
GLS Arawali Homes3.8 ★                               17
Godrej Summit3.7 ★                                   17
Conscient Heritage Max4.3 ★                          17
HCBS Sports Ville3.6 ★                               16
Bestech Park View Grand Spa4.3 ★                     16
M3M Merlin3.7 ★                                      16
Ansal Heights 86                                     15
Umang Monsoon Breeze                                 15
Godrej Oasis3.9 ★                                    15
Emaar MGF The Palm Drive4.1 ★                        15
The Close North4.0 ★                                 14
Imperia The Esfera                                   14
Corona Optus3.9 ★                                    14
Ireo Skyon4.0 ★                                      14
MVN Athens3.7 ★                                      14
Ramsons Kshitij3.7 ★                                 14
Orchid Petals4.1 ★                                   14
Umang Winter Hills3.9 ★                              14
Indiabulls Enigma                                    14
Ireo Victory Valley4.1 ★                             14
DLF The Primus3.9 ★                                  14
Vatika The Seven Lamps3.8 ★                          14
Central Park Flower Valley                           13
Ireo The Corridors                                   13
Puri Emerald Bay3.7 ★                                13
Bestech Park View Ananda4.2 ★                        13
Alpha Corp GurgaonOne 844.0 ★                        11
Raheja Vedaanta3.6 ★                                 11
DLF The Skycourt4.2 ★                                11
M3M Soulitude                                        11
SBTL Caladium                                        11
TARC Maceo3.8 ★                                      11
Adani M2K Oyster Grande3.9 ★                         11
Godrej Aria3.8 ★                                     11
Signature Global Synera3.4 ★                         10
Zara Aavaas                                          10
Ramprastha The Edge Towers3.5 ★                      10
Puri Diplomatic Greens4.0 ★                          10
DLF New Town Heights 24.0 ★                          10
Emaar MGF Palm Hills4.0 ★                            10
ATS Kocoon                                           10
Breez Global Heights4.2 ★                            10
Pyramid Urban Homes 2                                10
Capital Residences 360                               10
Pivotal Devaan                                       10
Godrej Air                                           10
Breez Global Hill View                               10
Parsvnath Green Ville3.9 ★                            9
Pareena Mi Casa                                       9
AIPL The Peaceful Homes3.9 ★                          9
Vatika City4.1 ★                                      9
Bestech Park View Sanskruti4.2 ★                      9
Microtek Greenburg3.8 ★                               9
Assotech Blith                                        8
Tulip Ivory3.5 ★                                      8
Emaar Digihomes                                       8
Orris Aster Court Premier                             8
Birla Navya                                           8
Bestech Altura                                        8
GLS Avenue 51                                         8
Vatika Lifestyle Homes3.8 ★                           8
ILD Greens4.1 ★                                       8
The Lions CGHS                                        8
M3M Capital                                           8
M3M Skycity                                           8
ss                                                    8
AVL 36 Gurgaon3.7 ★                                   8
Emaar Imperial Gardens3.8 ★                           7
Sare Crescent Parc Royal Greens Phase 1               7
Vipul Lavanya3.9 ★                                    7
Signature Andour Heights3.8 ★                         7
Sare Green ParC Phase 3                               7
Ansal Housing Highland Park                           7
AIPL Zen Residences                                   7
Mapsko Casa Bella3.8 ★                                7
Signature Global Orchard Avenue3.6 ★                  7
Orris Carnation Residency3.7 ★                        7
Ireo The Grand Arch4.0 ★                              7
Signature Global City                                 7
Trisara Our Homes 3                                   7
Shapoorji Pallonji Joyville Gurugram                  6
Pioneer Araya3.8 ★                                    6
BPTP Astaire Gardens3.7 ★                             6
Sidhartha NCR One Phase 14.2 ★                        6
HSIIDC Sidco Aravali                                  6
Signature Global Park 4                               6
Parsvnath Exotica3.7 ★                                6
Suncity Vatsal Valley                                 6
DLF Regency Park 13.6 ★                               6
M3M Sierra 68                                         6
Hero Homes                                            6
Signature The Roselia3.6 ★                            6
Signature Global City 63A                             6
Supertech Hues                                        6
Mapsko Royale Ville3.7 ★                              6
Greenopolis                                           6
Ashiana Mulberry                                      6
Bestech Park View Spa Next4.0 ★                       6
Kiran Residency                                       6
Bestech Park View City4.1 ★                           6
Pyramid Urban                                         6
Signature Global Grand IVA3.9 ★                       5
Emaar MGF Emerald Estate3.8 ★                         5
Godrej Habitat                                        5
Pioneer Park3.8 ★                                     5
Apna Enclave                                          5
M3M The Marina4.0 ★                                   5
DLF Regency Park 24.0 ★                               5
Signature Global City 92                              5
ATS Marigold                                          5
Ireo Uptown4.1 ★                                      5
Silverglades The Melia                                5
Vatika Sovereign Park                                 5
Krisumi Waterfall Residences                          5
Signature Global City 81                              5
Central Park Resorts4.4 ★                             5
DLF Park Place4.1 ★                                   5
Satya The Hermitage3.5 ★                              5
Green Court3.7 ★                                      5
Signature Global the Millennia                        5
Conscient Elevate                                     5
Central Park Flower Valley Aqua Front Towers          5
Signature Global City 37D Ph 2                        5
Ashiana Anmol3.5 ★                                    5
Adani Brahma Samsara Vilasa                           5
Vatika City Homes3.9 ★                                5
Pareena Laxmi Apartments3.6 ★                         5
Essel Towers                                          5
ILD Grand                                             4
Ramprastha Skyz                                       4
Unitech Vistas                                        4
Corona Gracieux                                       4
Prime Habitat                                         4
DLF The Skycourt                                      4
Krrish Provence Estate                                4
DLF New Town Heights3.7 ★                             4
Railway Officers RPF Society                          4
Orris Aster Court                                     4
Tata Gurgaon Gateway3.8 ★                             4
Godrej Icon                                           4
Emaar Palm Heights                                    4
Signature The Serenas                                 4
SS The Coralwood3.4 ★                                 4
Tulip Monsella                                        4
Godrej Frontier3.7 ★                                  4
Raheja Navodaya3.6 ★                                  4
Lotus Homz4.0 ★                                       4
HSIIDC Sidco Shivalik Apartments3.8 ★                 4
Ramprastha Primera                                    4
Unitech Fresco3.8 ★                                   4
Sare Petioles                                         4
Global Hill View                                      4
Paras Quartier                                        3
Dhoot Time Residency4.0 ★                             3
Ambience Lagoon3.9 ★                                  3
Unitech Heritage City                                 3
Shri Ram Apartments                                   3
Kendriya Vihar4.1 ★                                   3
Sunischit Apartments                                  3
Raheja Revanta                                        3
Brisk Lumbini Terrace Homes                           3
Valley View Estate                                    3
DLF Express Greens3.9 ★                               3
Sare Green Parc 2                                     3
Pivotal Riddhi Siddhi                                 3
Tulip Purple                                          3
Sidhartha NCR Greens4.3 ★                             3
Signature Global Solera 2                             3
DLF The Arbour                                        3
Adani Aangan Arcade                                   3
Puri Diplomatic Greens3.9 ★                           3
Sare Green Parc                                       3
Whiteland Blissville                                  3
DLF Royalton Tower                                    3
Raheja Atharva3.6 ★                                   3
Unitech Uniworld Gardens3.8 ★                         3
Chintels Paradiso3.9 ★                                3
Spaze Privvy The Address3.9 ★                         3
Pyramid Elite                                         3
Deepak Minda                                          3
AFNHB Jalvayu Vihar3.7 ★                              3
Tulip Lemon3.9 ★                                      3
Krrish Florence Estate                                3
DLF The Grove                                         3
Sapphire Eighty Three                                 3
Piedmont Taksila heights3.6 ★                         3
Tulip White3.5 ★                                      3
Spaze Privy3.9 ★                                      3
Guru Gram Haryana CGHS4.1 ★                           3
Vatika Xpressions                                     3
Sukhshanti Apartment                                  3
Conscient Habitat3.6 ★                                3
Satya Element One                                     3
Sidhartha NCR One                                     3
Apex Our Homes                                        3
Raheja Sampada                                        3
Smriti Apartment                                      3
Suncity Platinum Towers                               3
ATS Kocoon4.2 ★                                       3
Siddhartha Apartment                                  3
Tulip Petals3.6 ★                                     3
AIPL Club Residences                                  3
SS Almeria                                            3
Mahindra Aura4.2 ★                                    3
Essel Tower                                           3
Unitech Sunbreeze                                     3
Shri Banke Bihari Society3.8 ★                        3
DLF Carlton Estate4.0 ★                               3
Unitech The Residences3.7 ★                           3
DLF Belvedere Towers3.8 ★                             3
Vatika Independent Floors3.8 ★                        3
Shree Arihant Apartment                               3
The Roselia 2                                         3
Spaze Privy AT43.9 ★                                  3
Bestech Park View City 23.9 ★                         3
Maxworth City Residences                              3
Oriental Valley CHS                                   2
DLF The Icon3.7 ★                                     2
om appartments                                        2
NBCC Heights3.9 ★                                     2
Professors Enclave CGHS                               2
Supertech Hill Town                                   2
Ashiana Anmol                                         2
Aqua Front Towers                                     2
Signature Global The Millennia 3                      2
SS Hibiscus                                           2
Viridian The Plaza 106                                2
Tulip Leaf                                            2
Tulip Violet                                          2
Vatika Emilia Floors3.7 ★                             2
Emaar MGF Palm Studios                                2
Orchid Island4.2 ★                                    2
M3M Sky Lofts                                         2
Sahara Grace                                          2
ROF Aalayas3.8 ★                                      2
Tulip Orange3.9 ★                                     2
AWHO Shanti Vihar4.0 ★                                2
Central Park 2 Bellevue                               2
Ansal API Esencia3.7 ★                                2
Ganga Apartment                                       2
Raheja Atlantis3.8 ★                                  2
The Penthouses at the Hibiscus                        2
M3M Ikonic                                            2
Bestech Park View Sanskruti4.1 ★                      2
DLF The Crest3.6 ★                                    2
Samaspurkunj                                          2
BPTP Mansions Park Prime                              2
Housing Board Colony                                  2
Suncity Avenue 76                                     2
Paras Irene3.7 ★                                      2
Godrej Nature Plus Serenity                           2
Residency Grand                                       2
HCBS Sports Ville                                     2
Adani Aangan Galleria                                 2
Mittal Surya Vihar                                    2
Suposhaa Smartworld Orchard                           2
DLF The Belaire3.9 ★                                  2
Suncity Avenue 1023.9 ★                               2
BPTP Amstoria3.8 ★                                    2
Emaar MGF The Enclave                                 2
Vipul Belmonte3.9 ★                                   2
Shapoorji Pallonji Joyville                           2
Maruti Vihar                                          2
Ardee City3.8 ★                                       2
Raheja Vanya                                          2
Surendra Avenue 69                                    2
Landmark The Residency                                2
Vasant Appartments                                    2
Vatika INXT Floors                                    2
Suncity Heights3.7 ★                                  2
Ambience Caitriona                                    2
Palam Vihar Society                                   2
Bhagwati Sadan                                        2
Unitech Uniworld Gardens 23.4 ★                       2
BPTP Pedestal                                         2
M3M Urbana                                            2
Ramprastha City                                       2
Lavanya Apartments                                    2
MRG World Ultimus                                     2
Sidhivinayak Apartments                               2
Mapsko Paradise3.9 ★                                  2
Park Royal Apartment                                  2
Today Callidora                                       2
Ansal Heights3.2 ★                                    2
My Home                                               2
Ramprastha The Atrium3.4 ★                            2
Puri The Aravallis                                    2
Mahindra Luminare4.0 ★                                2
BPTP Freedom Park Life4.0 ★                           2
Supertech Hilltown                                    2
Silverglades Hightown Residences                      2
Ansal API Celebrity Suites                            2
M3M Latitude                                          2
CGHS Airport Apartment                                2
Tulsiani Easy in Homes                                2
Element One Service                                   2
Milan CGHS 9                                          2
Pioneer Urban Presidia                                2
Bestech Spa Signature                                 2
Green Campus CHS                                      2
Elan The Presidential                                 2
Breeze Global Heights                                 2
lagoon apartment                                      2
The Close South3.9 ★                                  2
Vipul World Floors                                    2
Dlf City                                              2
Apartment                                             2
ikon tower baani city centre                          1
Ansal Sushant Residency                               1
Surbhi Apartment                                      1
Ramsons Kshitij                                       1
Mittal Cosmos Executive Apartments3.8 ★               1
Jammu and Kashmir Bank Employees CGHS3.7 ★            1

In [38]:
# problem 1. rating is attached with soceity 
df['society'].value_counts().shape

(638,)

In [42]:
# problem 2. too many categories
# regex remove star , number
import re
df['society'] = df['society'].apply(lambda x: re.sub( r'\d+(\.\d+)\s?★' , '' ,str(x)).strip()).str.lower()

In [43]:
df['society'].value_counts().shape

(604,)

In [44]:
# price 
df['price'].value_counts()

price
1.25 Crore          79
1.1 Crore           61
1.4 Crore           60
1.5 Crore           59
1.2 Crore           59
90 Lac              57
1.3 Crore           57
95 Lac              52
2 Crore             51
1.75 Crore          47
1 Crore             45
1.6 Crore           43
1.35 Crore          41
1.55 Crore          40
1.9 Crore           40
75 Lac              38
1.65 Crore          38
1.8 Crore           37
1.7 Crore           37
80 Lac              36
2.2 Crore           34
50 Lac              33
1.15 Crore          33
1.45 Crore          31
85 Lac              31
1.05 Crore          30
2.5 Crore           29
60 Lac              29
40 Lac              29
2.1 Crore           26
45 Lac              26
65 Lac              25
35 Lac              23
2.35 Crore          23
1.85 Crore          23
3 Crore             22
70 Lac              21
55 Lac              20
2.25 Crore          20
3.5 Crore           19
2.4 Crore           18
2.3 Crore           18
30 Lac              17
2.65 Crore          16
2.6 Crore           15
1.38 Crore          15
2.45 Crore          14
3.4 Crore           14
2.15 Crore          14
1.32 Crore          13
3.25 Crore          13
78 Lac              13
92 Lac              13
82 Lac              13
38 Lac              13
2.7 Crore           13
1.95 Crore          12
1.42 Crore          12
5 Crore             12
42 Lac              12
2.8 Crore           12
88 Lac              11
32 Lac              11
25 Lac              11
1.08 Crore          11
Price on Request    11
28 Lac              10
1.28 Crore          10
87 Lac              10
26 Lac              10
1.78 Crore          10
1.12 Crore          10
2.55 Crore          10
1.68 Crore           9
3.45 Crore           9
36 Lac               9
22 Lac               9
2.05 Crore           9
4 Crore              9
1.72 Crore           9
99 Lac               9
2.85 Crore           9
27 Lac               8
1.76 Crore           8
98 Lac               8
1.18 Crore           8
1.26 Crore           8
1.54 Crore           8
4.25 Crore           8
2.75 Crore           8
3.2 Crore            8
6 Crore              8
48 Lac               8
6.5 Crore            8
20 Lac               8
56 Lac               8
86 Lac               8
1.36 Crore           7
1.27 Crore           7
97 Lac               7
3.7 Crore            7
1.19 Crore           7
3.3 Crore            7
72 Lac               7
2.9 Crore            7
1.29 Crore           7
46 Lac               7
39 Lac               7
1.02 Crore           7
1.99 Crore           7
79 Lac               7
1.59 Crore           6
43 Lac               6
1.49 Crore           6
1.01 Crore           6
2.95 Crore           6
3.9 Crore            6
96 Lac               6
3.65 Crore           6
5.5 Crore            6
1.07 Crore           6
1.98 Crore           6
21 Lac               6
54 Lac               6
1.39 Crore           6
3.35 Crore           6
1.13 Crore           6
71.5 Lac             6
37 Lac               6
4.1 Crore            6
1.34 Crore           6
3.05 Crore           6
1.14 Crore           6
1.16 Crore           6
1.51 Crore           6
1.24 Crore           5
1.33 Crore           5
1.17 Crore           5
2.22 Crore           5
6.75 Crore           5
1.91 Crore           5
1.82 Crore           5
2.78 Crore           5
1.69 Crore           5
1.44 Crore           5
49 Lac               5
3.75 Crore           5
1.92 Crore           5
1.43 Crore           5
66 Lac               5
2.29 Crore           5
1.79 Crore           5
93 Lac               5
1.62 Crore           5
1.83 Crore           5
1.93 Crore           5
4.5 Crore            5
64 Lac               5
2.12 Crore           5
29 Lac               5
24 Lac               5
1.47 Crore           5
68 Lac               5
1.64 Crore           4
2.09 Crore           4
1.37 Crore           4
5.25 Crore           4
3.6 Crore            4
4.3 Crore            4
5.6 Crore            4
1.22 Crore           4
58 Lac               4
4.85 Crore           4
62 Lac               4
1.23 Crore           4
1.77 Crore           4
41.5 Lac             4
1.52 Crore           4
28.5 Lac             4
1.73 Crore           4
33 Lac               4
7 Crore              4
1.31 Crore           4
36.5 Lac             4
1.48 Crore           4
5.9 Crore            4
3.95 Crore           4
6.15 Crore           4
73 Lac               4
1.58 Crore           4
1.71 Crore           4
89 Lac               4
67 Lac               4
31 Lac               4
1.66 Crore           4
74 Lac               4
3.1 Crore            4
2.24 Crore           3
83 Lac               3
72.5 Lac             3
47 Lac               3
2.36 Crore           3
1.21 Crore           3
1.04 Crore           3
4.75 Crore           3
2.03 Crore           3
3.8 Crore            3
64.5 Lac             3
91 Lac               3
5.8 Crore            3
4.8 Crore            3
1.67 Crore           3
2.51 Crore           3
3.49 Crore           3
2.01 Crore           3
2.08 Crore           3
51 Lac               3
52 Lac               3
84 Lac               3
69 Lac               3
1.57 Crore           3
1.41 Crore           3
3.15 Crore           3
2.79 Crore           3
3.85 Crore           3
2.28 Crore           3
34 Lac               3
1.63 Crore           3
94 Lac               3
1.09 Crore           3
4.2 Crore            3
1.88 Crore           3
2.33 Crore           3
2.23 Crore           2
1.46 Crore           2
77.5 Lac             2
53.5 Lac             2
4.49 Crore           2
2.58 Crore           2
6.2 Crore            2
8.5 Crore            2
2.14 Crore           2
27.1 Lac             2
53 Lac               2
2.52 Crore           2
8 Crore              2
2.41 Crore           2
2.57 Crore           2
56.2 Lac             2
3.55 Crore           2
1.87 Crore           2
3.32 Crore           2
3.21 Crore           2
4.6 Crore            2
4.26 Crore           2
2.13 Crore           2
2.02 Crore           2
5.2 Crore            2
14 Crore             2
2.87 Crore           2
2.99 Crore           2
2.26 Crore           2
1.56 Crore           2
5.7 Crore            2
52.56 Lac            2
87.5 Lac             2
71 Lac               2
3.29 Crore           2
59 Lac               2
2.91 Crore           2
31.5 Lac             2
41 Lac               2
98.5 Lac             2
2.17 Crore           2
25.5 Lac             2
4.55 Crore           2
7.5 Crore            2
27.75 Lac            2
4.45 Crore           2
4.7 Crore            2
2.04 Crore           2
11 Crore             2
88.5 Lac             2
54.8 Lac             1
63.4 Lac             1
82.5 Lac             1
3.78 Crore           1
2.06 Crore           1
2.07 Crore           1
3.98 Crore           1
7.4 Crore            1
4.02 Crore           1
2.64 Crore           1
44 Lac               1
37.1 Lac             1
97.5 Lac             1
2.38 Crore           1
2.49 Crore           1
97.04 Lac            1
98.88 Lac            1
2.32 Crore           1
4.21 Crore           1
4.16 Crore           1
15 Crore             1
4.52 Crore           1
89.77 Lac            1
73.53 Lac            1
26.5 Lac             1
26.9 Lac             1
1.84 Crore           1
8.44 Crore           1
68.85 Lac            1
39.5 Lac             1
13.2 Crore           1
2.92 Crore           1
61 Lac               1
64.45 Lac            1
2.69 Crore           1
3.99 Crore           1
2.96 Crore           1
57 Lac               1
95.5 Lac             1
37.5 Lac             1
96.07 Lac            1
94.5 Lac             1
29.8 Lac             1
19 Lac               1
88.4 Lac             1
6.02 Crore           1
32.5 Lac             1
7.9 Crore            1
70.85 Lac            1
3.23 Crore           1
40.3 Lac             1
3.72 Crore           1
94.99 Lac            1
1.86 Crore           1
2.54 Crore           1
9 Crore              1
7.52 Crore           1
85.75 Lac            1
87.99 Lac            1
86.99 Lac            1
9.95 Crore           1
9.2 Crore            1
86.92 Lac            1
49.5 Lac             1
16 Lac               1
2.44 Crore           1
2.86 Crore           1
1.97 Crore           1
1.53 Crore           1
7.8 Crore            1
4.4 Crore            1
1.74 Crore           1
2.72 Crore           1
5.31 Crore           1
3.19 Crore           1
4.63 Crore           1
2.98 Crore           1
66.99 Lac            1
4.78 Crore           1
6.16 Crore           1
5.3 Crore            1
2.21 Crore           1
2.63 Crore           1
89.5 Lac             1
2.48 Crore           1
99.5 Lac             1
3.83 Crore           1
95.75 Lac            1
3.46 Crore           1
5.4 Crore            1
55.6 Lac             1
4.95 Crore           1
54.99 Lac            1
2.82 Crore           1
7.15 Crore           1
6.25 Crore           1
29.99 Lac            1
23 Lac               1
31.75 Lac            1
3.87 Crore           1
29.5 Lac             1
3.67 Crore           1
8.25 Crore           1
2.37 Crore           1
4.67 Crore           1
3.39 Crore           1
3.63 Crore           1
2.34 Crore           1
3.79 Crore           1
5.49 Crore           1
6.3 Crore            1
11.25 Crore          1
98.1 Lac             1
55.5 Lac             1
9.3 Crore            1
2.77 Crore           1
2.11 Crore           1
6.1 Crore            1
5.75 Crore           1
10 Crore             1
24.5 Lac             1
17.5 Lac             1
20.5 Lac             1
47.5 Lac             1
42.5 Lac             1
1.11 Crore           1
2.61 Crore           1
65.5 Lac             1
53.2 Lac             1
90.5 Lac             1
52.5 Lac             1
2.62 Crore           1
4.86 Crore           1
5.15 Crore           1
1.06 Crore           1
26.1 Lac             1
81 Lac               1
8.35 Crore           1
6.44 Crore           1
7.56 Crore           1
4.79 Crore           1
2.97 Crore           1
94.25 Lac            1
80.5 Lac             1
93.75 Lac            1
85.5 Lac             1
68.5 Lac             1
79.9 Lac             1
71.2 Lac             1
27.5 Lac             1
23.5 Lac             1
35.5 Lac             1
4.94 Crore           1
10.75 Crore          1
9.14 Crore           1
62.5 Lac             1
Name: count, dtype: int64

In [46]:
# obseved only 3 val - lakh ,crore , price on request
df[df['price']== 'Price on Request']

,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
25,5 BHK Flat in Sector 1 Gurgaon,the new people apartments,Price on Request,NaN,Built Up area: 4500 (418.06 sq.m.),5 Bedrooms,1 Bathroom,No Balcony,NaN,"Sector 1, Sector 1 Gurgaon, Gurgaon, Haryana",Ground of 1 Floors,NaN,undefined,"['Pooja Clinic', 'Dr. Sahil Clinic', 'Prakash ...",Best in class property available at sector 1 l...,NaN,NaN,NaN
1645,4 BHK Flat in Sector 50 Gurgaon,ss hibiscus,Price on Request,NaN,Carpet area: 4800 (445.93 sq.m.),4 Bedrooms,4 Bathrooms,3 Balconies,Servant Room,"Sector 50 Gurgaon, Gurgaon, Haryana",7th of 18 Floors,East,5 to 10 Year Old,"['Baani Square', 'SS Plaza', 'Good Earth City ...",4bedroom 4800sq.Ft middle floor apartment avai...,"['4 Fan', '8 Light', 'No AC', 'No Bed', 'No Ch...","['Lift(s)', 'Water purifier', 'Swimming Pool',...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
1973,1 BHK Flat in Sector 31 Gurgaon,raheja atlantis,Price on Request,NaN,Carpet area: 650 (60.39 sq.m.),1 Bedroom,1 Bathroom,1 Balcony,"Pooja Room,Study Room,Servant Room","Yes, Sector 31 Gurgaon, Gurgaon, Haryana",3rd of 15 Floors,East,0 to 1 Year Old,"['Huda Metro Station', 'Reliance Fresh, Indira...",It is my property and good condition and good ...,NaN,"['Feng Shui / Vaastu Compliant', 'Security / F...","['Green Area4 out of 5', 'Construction4 out of..."
2055,2 BHK Flat in Sector 79 Gurgaon,supertech araville,Price on Request,NaN,Built Up area: 1295 (120.31 sq.m.),2 Bedrooms,2 Bathrooms,No Balcony,NaN,"Sector 79, Sector 79 Gurgaon, Gurgaon, Haryana",15th of 15 Floors,NaN,undefined,NaN,"2 bath, unfurnished, 15th floor (Of 18), super...",NaN,NaN,"['Environment4 out of 5', 'Lifestyle3 out of 5..."
2358,2 BHK Flat in Sector 37D Gurgaon,the millennia 2,Price on Request,NaN,Carpet area: 552 (51.28 sq.m.),2 Bedrooms,1 Bathroom,1 Balcony,NaN,"Sector 37D Gurgaon, Gurgaon, Haryana",13rd of 13 Floors,NaN,undefined,"['Shri Balaji Hospital and Trauma Center', 'Sh...","1 bath, unfurnished, 13th floor (Of 13), at se...",NaN,NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."
2523,2 BHK Flat in Sector 95A Gurgaon,the roselia 2,Price on Request,NaN,Carpet area: 593 (55.09 sq.m.),2 Bedrooms,2 Bathrooms,2 Balconies,NaN,"Sector 95a, Pataudi Road, Sector 95A Gurgaon, ...",14th of 14 Floors,NaN,undefined,NaN,Best in class property available at sector 95a...,NaN,NaN,"['Environment5 out of 5', 'Lifestyle4.5 out of..."
2550,3 BHK Flat in Sector-2 Sohna,supertech hilltown,Price on Request,NaN,Built Up area: 1720 (159.79 sq.m.),3 Bedrooms,3 Bathrooms,3 Balconies,NaN,"Sohna Sector 2,gurgaon, Sector-2 Sohna, Gurgao...",4th of 4 Floors,North-East,undefined,NaN,"3 bath, unfurnished, 4th floor (Of 4), overloo...",NaN,NaN,NaN
2641,2 BHK Flat in Sector 95A Gurgaon,the roselia 2,Price on Request,NaN,Carpet area: 593 (55.09 sq.m.),2 Bedrooms,2 Bathrooms,2 Balconies,NaN,"Sector 95a, Pataudi Road, Sector 95A Gurgaon, ...",14th of 14 Floors,NaN,undefined,NaN,Best in class property available at sector 95a...,NaN,NaN,"['Environment5 out of 5', 'Safety5 out of 5', ..."
2960,3 BHK Flat in Sector 104 Gurgaon,godrej summit,Price on Request,NaN,Super Built up area 1647(153.01 sq.m.)Carpet a...,3 Bedrooms,3 Bathrooms,3 Balconies,NaN,"1402, Sector 104 Gurgaon, Gurgaon, Haryana",14th of 17 Floors,NaN,1 to 5 Year Old,"['MG Road Metro Station', 'The Esplanade Mall'...",We are the proud owners of this 3 bhk apartmen...,[],"['Intercom Facility', 'Lift(s)', 'Maintenance ...","['Management3 out of 5', 'Green Area4.5 out of..."
2973,4 BHK Flat in Gwal Pahari,krrish provence estate,Price on Request,NaN,Built Up area: 5800 (538.84 sq.m.),4 Bedrooms,5 Bathrooms,1 Balcony,NaN,"Gwal Pahari, Gurgaon, Haryana",17th of 24 Floors,NaN,Under Construction,"['Tniy Toons School', 'Pathways School Gurgoan...",Residential apartment for sell.Located on 17th...,NaN,NaN,NaN
2974,4 BHK Flat in Sector 95 Gurgaon,sidhartha ncr one phase,Price on Request,NaN,Super Built up area 2354(218.69 sq.m.),4 Bedrooms,4 Bathrooms,3+ Balconies,NaN,"Sector 95 Gurgaon, Gurgaon, Haryana",Ground of 3 Floors,North,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...","North facing entry, Very good layout, Excellen...",[],"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Management4 out of 5', 'Green Area4 out of 5..."

In [47]:
# since 10 - 11 rows are ther priceless so we ignore them hehe
df = df[df['price']!= 'Price on Request']

In [48]:
df.head(3)

,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Krishna Colony,maa bhagwati residency,45 Lac,"₹ 5,000/sq.ft.",Carpet area: 900 (83.61 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"Krishna Colony, Gurgaon, Haryana",4th of 4 Floors,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ..."
1,2 BHK Flat in Ashok Vihar,apna enclave,50 Lac,"₹ 7,692/sq.ft.",Carpet area: 650 (60.39 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"46b, Ashok Vihar, Gurgaon, Haryana",1st of 3 Floors,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ..."
2,2 BHK Flat in Sohna,tulsiani easy in homes,40 Lac,"₹ 6,722/sq.ft.",Carpet area: 595 (55.28 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,NaN,"Sohna, Gurgaon, Haryana",12nd of 14 Floors,NaN,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment4 out of 5', 'Safety4 out of 5', ..."

In [49]:
# making all val in crore

def convert_price(x):
    
    if type(x) == float:
        return x
    
    else:
        if x[1] == 'Lac':
            return round( float(x[0]) / 100 , 2 )
        else:
            return round( float(x[0]) , 2)

In [50]:
df['price'] = df['price'].str.split(' ').apply(convert_price)

In [51]:
df.head(2)

,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Krishna Colony,maa bhagwati residency,0.45,"₹ 5,000/sq.ft.",Carpet area: 900 (83.61 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"Krishna Colony, Gurgaon, Haryana",4th of 4 Floors,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ..."
1,2 BHK Flat in Ashok Vihar,apna enclave,0.50,"₹ 7,692/sq.ft.",Carpet area: 650 (60.39 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"46b, Ashok Vihar, Gurgaon, Haryana",1st of 3 Floors,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ..."

In [52]:
# price_per_sqft
df['price_per_sqft'].value_counts() # checking if anything is abnormal or  not

price_per_sqft
₹ 10,000/sq.ft.     19
₹ 8,000/sq.ft.      16
₹ 12,500/sq.ft.     16
₹ 5,000/sq.ft.      13
₹ 6,666/sq.ft.      13
₹ 7,500/sq.ft.      12
₹ 8,333/sq.ft.      12
₹ 6,000/sq.ft.      11
₹ 8,461/sq.ft.       9
₹ 12,000/sq.ft.      8
₹ 7,000/sq.ft.       8
₹ 9,000/sq.ft.       7
₹ 6,578/sq.ft.       6
₹ 8,928/sq.ft.       6
₹ 8,888/sq.ft.       6
₹ 9,230/sq.ft.       6
₹ 11,111/sq.ft.      6
₹ 5,500/sq.ft.       6
₹ 11,500/sq.ft.      6
₹ 7,142/sq.ft.       5
₹ 10,714/sq.ft.      5
₹ 4,444/sq.ft.       5
₹ 8,571/sq.ft.       5
₹ 7,641/sq.ft.       5
₹ 4,615/sq.ft.       5
₹ 7,407/sq.ft.       5
₹ 5,556/sq.ft.       5
₹ 6,500/sq.ft.       5
₹ 11,428/sq.ft.      5
₹ 4,666/sq.ft.       5
₹ 16,000/sq.ft.      5
₹ 8,205/sq.ft.       5
₹ 14,242/sq.ft.      5
₹ 7,692/sq.ft.       5
₹ 5,600/sq.ft.       5
₹ 5,384/sq.ft.       5
₹ 5,660/sq.ft.       4
₹ 8,139/sq.ft.       4
₹ 8,787/sq.ft.       4
₹ 13,636/sq.ft.      4
₹ 9,210/sq.ft.       4
₹ 13,750/sq.ft.      4
₹ 7,272/sq.ft.       4
₹ 8,163/sq.ft.       4
₹ 4,500/sq.ft.       4
₹ 8,474/sq.ft.       4
₹ 11,666/sq.ft.      4
₹ 10,383/sq.ft.      4
₹ 4,854/sq.ft.       4
₹ 7,317/sq.ft.       4
₹ 8,445/sq.ft.       4
₹ 8,108/sq.ft.       4
₹ 8,432/sq.ft.       4
₹ 8,043/sq.ft.       4
₹ 15,000/sq.ft.      4
₹ 10,416/sq.ft.      4
₹ 6,250/sq.ft.       4
₹ 7,250/sq.ft.       4
₹ 7,496/sq.ft.       4
₹ 15,384/sq.ft.      4
₹ 8,358/sq.ft.       4
₹ 16,666/sq.ft.      4
₹ 4,814/sq.ft.       4
₹ 9,822/sq.ft.       4
₹ 9,090/sq.ft.       4
₹ 14,418/sq.ft.      4
₹ 8,500/sq.ft.       4
₹ 7,812/sq.ft.       4
₹ 13,913/sq.ft.      4
₹ 8,484/sq.ft.       4
₹ 6,735/sq.ft.       4
₹ 8,784/sq.ft.       4
₹ 4,687/sq.ft.       4
₹ 8,080/sq.ft.       3
₹ 13,000/sq.ft.      3
₹ 7,541/sq.ft.       3
₹ 6,593/sq.ft.       3
₹ 10,139/sq.ft.      3
₹ 9,615/sq.ft.       3
₹ 5,856/sq.ft.       3
₹ 6,470/sq.ft.       3
₹ 10,204/sq.ft.      3
₹ 5,735/sq.ft.       3
₹ 5,833/sq.ft.       3
₹ 6,387/sq.ft.       3
₹ 5,325/sq.ft.       3
₹ 7,179/sq.ft.       3
₹ 14,254/sq.ft.      3
₹ 8,750/sq.ft.       3
₹ 14,000/sq.ft.      3
₹ 4,800/sq.ft.       3
₹ 8,181/sq.ft.       3
₹ 8,215/sq.ft.       3
₹ 5,238/sq.ft.       3
₹ 16,470/sq.ft.      3
₹ 7,948/sq.ft.       3
₹ 6,818/sq.ft.       3
₹ 8,620/sq.ft.       3
₹ 7,150/sq.ft.       3
₹ 6,921/sq.ft.       3
₹ 7,586/sq.ft.       3
₹ 7,083/sq.ft.       3
₹ 8,078/sq.ft.       3
₹ 7,865/sq.ft.       3
₹ 7,400/sq.ft.       3
₹ 6,476/sq.ft.       3
₹ 4,820/sq.ft.       3
₹ 8,222/sq.ft.       3
₹ 7,750/sq.ft.       3
₹ 9,900/sq.ft.       3
₹ 9,473/sq.ft.       3
₹ 5,878/sq.ft.       3
₹ 5,397/sq.ft.       3
₹ 6,542/sq.ft.       3
₹ 8,606/sq.ft.       3
₹ 13,392/sq.ft.      3
₹ 8,886/sq.ft.       3
₹ 8,389/sq.ft.       3
₹ 8,450/sq.ft.       3
₹ 6,667/sq.ft.       3
₹ 4,105/sq.ft.       3
₹ 9,904/sq.ft.       3
₹ 5,319/sq.ft.       3
₹ 6,644/sq.ft.       3
₹ 9,500/sq.ft.       3
₹ 8,532/sq.ft.       3
₹ 9,011/sq.ft.       3
₹ 5,555/sq.ft.       3
₹ 7,056/sq.ft.       3
₹ 7,302/sq.ft.       3
₹ 10,500/sq.ft.      3
₹ 10,638/sq.ft.      3
₹ 14,430/sq.ft.      3
₹ 11,363/sq.ft.      3
₹ 4,210/sq.ft.       3
₹ 16,969/sq.ft.      3
₹ 13,870/sq.ft.      3
₹ 4,513/sq.ft.       3
₹ 7,467/sq.ft.       3
₹ 8,604/sq.ft.       3
₹ 8,148/sq.ft.       3
₹ 11,000/sq.ft.      3
₹ 9,972/sq.ft.       3
₹ 6,086/sq.ft.       3
₹ 7,954/sq.ft.       3
₹ 6,404/sq.ft.       3
₹ 7,549/sq.ft.       3
₹ 10,555/sq.ft.      3
₹ 6,421/sq.ft.       3
₹ 8,400/sq.ft.       3
₹ 13,108/sq.ft.      2
₹ 8,159/sq.ft.       2
₹ 4,857/sq.ft.       2
₹ 3,911/sq.ft.       2
₹ 5,056/sq.ft.       2
₹ 11,412/sq.ft.      2
₹ 14,237/sq.ft.      2
₹ 6,315/sq.ft.       2
₹ 6,053/sq.ft.       2
₹ 12,212/sq.ft.      2
₹ 20,687/sq.ft.      2
₹ 4,856/sq.ft.       2
₹ 6,987/sq.ft.       2
₹ 13,076/sq.ft.      2
₹ 8,433/sq.ft.       2
₹ 6,333/sq.ft.       2
₹ 7,490/sq.ft.       2
₹ 8,670/sq.ft.       2
₹ 11,715/sq.ft.      2
₹ 6,153/sq.ft.       2
₹ 9,074/sq.ft.       2
₹ 6,373/sq.ft.       2
₹ 18,271/sq.ft.      2
₹ 5,896/sq.ft.       2
₹ 8,252/sq.ft.       2
₹ 16,985/sq.ft.      2
₹ 6,422/sq.ft.       2
₹ 6,896/sq.ft.       2
₹ 7,765/sq.ft.       2
₹ 4,909/sq.ft.       2
₹ 9,978/sq.ft.       2
₹ 8,974/sq.ft.       2
₹ 5,513/sq.ft.       2
₹ 8,897/sq.ft.       2
₹ 4,327/sq.ft.       2
₹ 6,402/sq.ft.       2
₹ 8,632/sq.ft.       2
₹ 9,020/sq.ft.       2
₹ 15,263/sq.ft.      2
₹ 6,938/sq.ft.       2
₹ 16,747/sq.ft.      2
₹ 8,290/sq.ft.       2
₹ 8,024/sq.ft.       2
₹ 8,519/sq.ft.       2
₹ 7,174/sq.ft.       2
₹ 7,350/sq.ft.       2
₹ 8,412/sq.ft.       2
₹ 8,536/sq.ft.       2
₹ 7,359/sq.ft.       2
₹ 8,600/sq.ft.       2
₹ 7,945/sq.ft.       2
₹ 10,936/sq.ft.      2
₹ 10,516/sq.ft.      2
₹ 16,858/sq.ft.      2
₹ 8,410/sq.ft.       2
₹ 8,453/sq.ft.       2
₹ 13,430/sq.ft.      2
₹ 16,608/sq.ft.      2
₹ 5,649/sq.ft.       2
₹ 21,538/sq.ft.      2
₹ 19,000/sq.ft.      2
₹ 15,551/sq.ft.      2
₹ 9,854/sq.ft.       2
₹ 6,406/sq.ft.       2
₹ 11,125/sq.ft.      2
₹ 6,353/sq.ft.       2
₹ 15,294/sq.ft.      2
₹ 13,991/sq.ft.      2
₹ 8,279/sq.ft.       2
₹ 200,000/sq.ft.     2
₹ 8,324/sq.ft.       2
₹ 14,285/sq.ft.      2
₹ 5,528/sq.ft.       2
₹ 11,505/sq.ft.      2
₹ 9,922/sq.ft.       2
₹ 6,049/sq.ft.       2
₹ 9,797/sq.ft.       2
₹ 9,672/sq.ft.       2
₹ 5,671/sq.ft.       2
₹ 8,835/sq.ft.       2
₹ 15,416/sq.ft.      2
₹ 9,743/sq.ft.       2
₹ 7,610/sq.ft.       2
₹ 5,982/sq.ft.       2
₹ 7,716/sq.ft.       2
₹ 5,839/sq.ft.       2
₹ 11,765/sq.ft.      2
₹ 17,039/sq.ft.      2
₹ 8,846/sq.ft.       2
₹ 4,761/sq.ft.       2
₹ 6,465/sq.ft.       2
₹ 14,785/sq.ft.      2
₹ 12,022/sq.ft.      2
₹ 8,376/sq.ft.       2
₹ 19,767/sq.ft.      2
₹ 6,839/sq.ft.       2
₹ 6,141/sq.ft.       2
₹ 11,336/sq.ft.      2
₹ 7,908/sq.ft.       2
₹ 6,679/sq.ft.       2
₹ 7,058/sq.ft.       2
₹ 9,007/sq.ft.       2
₹ 8,733/sq.ft.       2
₹ 8,834/sq.ft.       2
₹ 9,025/sq.ft.       2
₹ 6,313/sq.ft.       2
₹ 15,195/sq.ft.      2
₹ 11,694/sq.ft.      2
₹ 8,305/sq.ft.       2
₹ 5,150/sq.ft.       2
₹ 9,620/sq.ft.       2
₹ 9,642/sq.ft.       2
₹ 6,647/sq.ft.       2
₹ 5,177/sq.ft.       2
₹ 6,825/sq.ft.       2
₹ 9,139/sq.ft.       2
₹ 11,727/sq.ft.      2
₹ 10,489/sq.ft.      2
₹ 6,254/sq.ft.       2
₹ 6,571/sq.ft.       2
₹ 5,929/sq.ft.       2
₹ 5,820/sq.ft.       2
₹ 14,303/sq.ft.      2
₹ 14,683/sq.ft.      2
₹ 5,980/sq.ft.       2
₹ 13,343/sq.ft.      2
₹ 9,791/sq.ft.       2
₹ 5,828/sq.ft.       2
₹ 7,223/sq.ft.       2
₹ 6,811/sq.ft.       2
₹ 8,283/sq.ft.       2
₹ 6,774/sq.ft.       2
₹ 15,454/sq.ft.      2
₹ 9,950/sq.ft.       2
₹ 11,250/sq.ft.      2
₹ 6,692/sq.ft.       2
₹ 4,307/sq.ft.       2
₹ 5,252/sq.ft.       2
₹ 7,097/sq.ft.       2
₹ 13,928/sq.ft.      2
₹ 7,850/sq.ft.       2
₹ 6,076/sq.ft.       2
₹ 7,817/sq.ft.       2
₹ 10,237/sq.ft.      2
₹ 4,080/sq.ft.       2
₹ 5,808/sq.ft.       2
₹ 5,564/sq.ft.       2
₹ 6,029/sq.ft.       2
₹ 10,651/sq.ft.      2
₹ 9,433/sq.ft.       2
₹ 7,863/sq.ft.       2
₹ 9,589/sq.ft.       2
₹ 5,725/sq.ft.       2
₹ 6,243/sq.ft.       2
₹ 9,565/sq.ft.       2
₹ 7,751/sq.ft.       2
₹ 7,758/sq.ft.       2
₹ 15,500/sq.ft.      2
₹ 10,545/sq.ft.      2
₹ 8,411/sq.ft.       2
₹ 11,574/sq.ft.      2
₹ 19,747/sq.ft.      2
₹ 19,882/sq.ft.      2
₹ 3,695/sq.ft.       2
₹ 16,363/sq.ft.      2
₹ 5,683/sq.ft.       2
₹ 9,550/sq.ft.       2
₹ 5,517/sq.ft.       2
₹ 8,756/sq.ft.       2
₹ 8,947/sq.ft.       2
₹ 9,482/sq.ft.       2
₹ 5,599/sq.ft.       2
₹ 4,745/sq.ft.       2
₹ 8,237/sq.ft.       2
₹ 5,674/sq.ft.       2
₹ 6,588/sq.ft.       2
₹ 6,655/sq.ft.       2
₹ 14,615/sq.ft.      2
₹ 9,306/sq.ft.       2
₹ 7,608/sq.ft.       2
₹ 12,444/sq.ft.      2
₹ 10,699/sq.ft.      2
₹ 9,022/sq.ft.       2
₹ 12,012/sq.ft.      2
₹ 9,105/sq.ft.       2
₹ 7,185/sq.ft.       2
₹ 7,878/sq.ft.       2
₹ 7,449/sq.ft.       2
₹ 8,031/sq.ft.       2
₹ 9,128/sq.ft.       2
₹ 5,825/sq.ft.       2
₹ 10,553/sq.ft.      2
₹ 9,742/sq.ft.       2
₹ 6,382/sq.ft.       2
₹ 5,588/sq.ft.       2
₹ 7,987/sq.ft.       2
₹ 8,424/sq.ft.       2
₹ 5,658/sq.ft.       2
₹ 6,455/sq.ft.       2
₹ 5,454/sq.ft.       2
₹ 5,744/sq.ft.       2
₹ 8,100/sq.ft.       2
₹ 8,294/sq.ft.       2
₹ 8,814/sq.ft.       2
₹ 7,014/sq.ft.       2
₹ 10,596/sq.ft.      2
₹ 8,518/sq.ft.       2
₹ 8,457/sq.ft.       2
₹ 3,477/sq.ft.       2
₹ 12,222/sq.ft.      2
₹ 18,518/sq.ft.      2
₹ 13,709/sq.ft.      2
₹ 6,428/sq.ft.       2
₹ 5,100/sq.ft.       2
₹ 11,992/sq.ft.      2
₹ 8,903/sq.ft.       2
₹ 13,270/sq.ft.      2
₹ 6,209/sq.ft.       2
₹ 14,545/sq.ft.      2
₹ 7,846/sq.ft.       2
₹ 6,325/sq.ft.       2
₹ 6,739/sq.ft.       2
₹ 7,297/sq.ft.       2
₹ 11,333/sq.ft.      2
₹ 10,666/sq.ft.      2
₹ 11,627/sq.ft.      2
₹ 6,983/sq.ft.       2
₹ 7,200/sq.ft.       2
₹ 5,424/sq.ft.       2
₹ 5,882/sq.ft.       2
₹ 10,601/sq.ft.      2
₹ 8,972/sq.ft.       2
₹ 9,600/sq.ft.       2
₹ 7,585/sq.ft.       2
₹ 10,384/sq.ft.      2
₹ 9,876/sq.ft.       2
₹ 9,909/sq.ft.       2
₹ 13,500/sq.ft.      2
₹ 7,857/sq.ft.       2
₹ 6,061/sq.ft.       2
₹ 6,429/sq.ft.       2
₹ 5,111/sq.ft.       2
₹ 6,377/sq.ft.       2
₹ 6,538/sq.ft.       2
₹ 6,985/sq.ft.       2
₹ 5,786/sq.ft.       2
₹ 15,998/sq.ft.      2
₹ 7,727/sq.ft.       2
₹ 5,189/sq.ft.       2
₹ 8,075/sq.ft.       2
₹ 9,851/sq.ft.       2
₹ 6,950/sq.ft.       2
₹ 41,245/sq.ft.      2
₹ 7,574/sq.ft.       2
₹ 6,510/sq.ft.       2
₹ 9,286/sq.ft.       2
₹ 5,797/sq.ft.       2
₹ 5,714/sq.ft.       2
₹ 15,151/sq.ft.      2
₹ 6,200/sq.ft.       2
₹ 5,038/sq.ft.       2
₹ 10,531/sq.ft.      2
₹ 6,686/sq.ft.       2
₹ 6,024/sq.ft.       2
₹ 9,333/sq.ft.       2
₹ 8,006/sq.ft.       2
₹ 11,529/sq.ft.      2
₹ 8,609/sq.ft.       2
₹ 10,018/sq.ft.      2
₹ 6,217/sq.ft.       2
₹ 7,530/sq.ft.       2
₹ 6,506/sq.ft.       2
₹ 7,627/sq.ft.       2
₹ 9,027/sq.ft.       2
₹ 6,967/sq.ft.       2
₹ 6,420/sq.ft.       2
₹ 10,526/sq.ft.      2
₹ 5,405/sq.ft.       2
₹ 13,769/sq.ft.      2
₹ 11,755/sq.ft.      2
₹ 6,789/sq.ft.       2
₹ 7,780/sq.ft.       2
₹ 7,782/sq.ft.       2
₹ 9,146/sq.ft.       2
₹ 7,396/sq.ft.       2
₹ 6,111/sq.ft.       2
₹ 5,284/sq.ft.       2
₹ 9,062/sq.ft.       2
₹ 5,641/sq.ft.       2
₹ 8,310/sq.ft.       2
₹ 6,569/sq.ft.       2
₹ 5,521/sq.ft.       2
₹ 8,618/sq.ft.       2
₹ 11,724/sq.ft.      2
₹ 6,812/sq.ft.       2
₹ 5,128/sq.ft.       2
₹ 8,582/sq.ft.       2
₹ 18,000/sq.ft.      2
₹ 8,053/sq.ft.       2
₹ 10,599/sq.ft.      2
₹ 6,338/sq.ft.       2
₹ 8,524/sq.ft.       2
₹ 9,449/sq.ft.       2
₹ 8,035/sq.ft.       2
₹ 9,166/sq.ft.       2
₹ 8,036/sq.ft.       2
₹ 8,611/sq.ft.       2
₹ 8,504/sq.ft.       2
₹ 6,178/sq.ft.       2
₹ 14,257/sq.ft.      2
₹ 9,259/sq.ft.       2
₹ 14,214/sq.ft.      2
₹ 14,583/sq.ft.      2
₹ 9,182/sq.ft.       2
₹ 6,927/sq.ft.       2
₹ 6,616/sq.ft.       2
₹ 7,884/sq.ft.       2
₹ 12,782/sq.ft.      2
₹ 6,722/sq.ft.       2
₹ 9,677/sq.ft.       2
₹ 8,072/sq.ft.       2
₹ 6,702/sq.ft.       2
₹ 8,517/sq.ft.       2
₹ 8,720/sq.ft.       2
₹ 12,250/sq.ft.      2
₹ 10,476/sq.ft.      2
₹ 4,000/sq.ft.       2
₹ 5,681/sq.ft.       2
₹ 12,777/sq.ft.      2
₹ 13,224/sq.ft.      2
₹ 14,800/sq.ft.      2
₹ 9,452/sq.ft.       2
₹ 58/sq.ft.          2
₹ 8,166/sq.ft.       2
₹ 7,631/sq.ft.       2
₹ 10,370/sq.ft.      2
₹ 7,796/sq.ft.       2
₹ 11,726/sq.ft.      2
₹ 5,463/sq.ft.       2
₹ 14,478/sq.ft.      2
₹ 13,333/sq.ft.      2
₹ 4,651/sq.ft.       2
₹ 9,263/sq.ft.       2
₹ 5,614/sq.ft.       2
₹ 9,135/sq.ft.       2
₹ 7,825/sq.ft.       2
₹ 17,619/sq.ft.      2
₹ 4,271/sq.ft.       2
₹ 6,134/sq.ft.       2
₹ 6,859/sq.ft.       2
₹ 6,190/sq.ft.       2
₹ 8,206/sq.ft.       2
₹ 13,281/sq.ft.      2
₹ 6,206/sq.ft.       2
₹ 11,700/sq.ft.      2
₹ 11,516/sq.ft.      2
₹ 16,960/sq.ft.      2
₹ 7,391/sq.ft.       2
₹ 10,603/sq.ft.      2
₹ 7,225/sq.ft.       2
₹ 7,248/sq.ft.       2
₹ 11,028/sq.ft.      2
₹ 6,189/sq.ft.       2
₹ 6,551/sq.ft.       2
₹ 5,291/sq.ft.       2
₹ 18,181/sq.ft.      2
₹ 5,899/sq.ft.       2
₹ 13,383/sq.ft.      2
₹ 6,597/sq.ft.       2
₹ 8,521/sq.ft.       2
₹ 6,318/sq.ft.       2
₹ 18,688/sq.ft.      1
₹ 10,754/sq.ft.      1
₹ 12,791/sq.ft.      1
₹ 10,309/sq.ft.      1
₹ 6,319/sq.ft.       1
₹ 5,296/sq.ft.       1
₹ 15,102/sq.ft.      1
₹ 9,531/sq.ft.       1
₹ 13,953/sq.ft.      1
₹ 17,378/sq.ft.      1
₹ 7,679/sq.ft.       1
₹ 8,558/sq.ft.       1
₹ 10,924/sq.ft.      1
₹ 10,306/sq.ft.      1
₹ 7,931/sq.ft.       1
₹ 8,124/sq.ft.       1
₹ 14,632/sq.ft.      1
₹ 14,658/sq.ft.      1
₹ 5,813/sq.ft.       1
₹ 9,002/sq.ft.       1
₹ 9,696/sq.ft.       1
₹ 11,209/sq.ft.      1
₹ 9,912/sq.ft.       1
₹ 6,194/sq.ft.       1
₹ 9/sq.ft.           1
₹ 4,108/sq.ft.       1
₹ 15,262/sq.ft.      1
₹ 5,739/sq.ft.       1
₹ 3,650/sq.ft.       1
₹ 8,095/sq.ft.       1
₹ 4,179/sq.ft.       1
₹ 4,106/sq.ft.       1
₹ 8,982/sq.ft.       1
₹ 6,077/sq.ft.       1
₹ 13,921/sq.ft.      1
₹ 3,713/sq.ft.       1
₹ 3,664/sq.ft.       1
₹ 4,545/sq.ft.       1
₹ 14,603/sq.ft.      1
₹ 22,346/sq.ft.      1
₹ 22,222/sq.ft.      1
₹ 8,494/sq.ft.       1
₹ 12,272/sq.ft.      1
₹ 20,666/sq.ft.      1
₹ 15,124/sq.ft.      1
₹ 9,236/sq.ft.       1
₹ 12,009/sq.ft.      1
₹ 15,560/sq.ft.      1
₹ 14,358/sq.ft.      1
₹ 6,554/sq.ft.       1
₹ 17,543/sq.ft.      1
₹ 4,886/sq.ft.       1
₹ 6,033/sq.ft.       1
₹ 6,485/sq.ft.       1
₹ 10,627/sq.ft.      1
₹ 6,648/sq.ft.       1
₹ 9,380/sq.ft.       1
₹ 5,621/sq.ft.       1
₹ 18,392/sq.ft.      1
₹ 7,779/sq.ft.       1
₹ 8,986/sq.ft.       1
₹ 6,881/sq.ft.       1
₹ 7,164/sq.ft.       1
₹ 9,219/sq.ft.       1
₹ 4,971/sq.ft.       1
₹ 11,497/sq.ft.      1
₹ 11,407/sq.ft.      1
₹ 4,219/sq.ft.       1
₹ 10,094/sq.ft.      1
₹ 9,714/sq.ft.       1
₹ 7,988/sq.ft.       1
₹ 11,074/sq.ft.      1
₹ 6,849/sq.ft.       1
₹ 9,076/sq.ft.       1
₹ 10,483/sq.ft.      1
₹ 6,272/sq.ft.       1
₹ 10,408/sq.ft.      1
₹ 10,257/sq.ft.      1
₹ 10,017/sq.ft.      1
₹ 13,425/sq.ft.      1
₹ 10,031/sq.ft.      1
₹ 8,349/sq.ft.       1
₹ 14,783/sq.ft.      1
₹ 8,674/sq.ft.       1
₹ 10,101/sq.ft.      1
₹ 20,707/sq.ft.      1
₹ 10,172/sq.ft.      1
₹ 10,888/sq.ft.      1
₹ 11,094/sq.ft.      1
₹ 7,917/sq.ft.       1
₹ 8,953/sq.ft.       1
₹ 4,375/sq.ft.       1
₹ 11,854/sq.ft.      1
₹ 11,869/sq.ft.      1
₹ 591/sq.ft.         1
₹ 4,941/sq.ft.       1
₹ 3,671/sq.ft.       1
₹ 14,680/sq.ft.      1
₹ 23,344/sq.ft.      1
₹ 7,066/sq.ft.       1
₹ 7,227/sq.ft.       1
₹ 10,452/sq.ft.      1
₹ 5,904/sq.ft.       1
₹ 17,271/sq.ft.      1
₹ 7,006/sq.ft.       1
₹ 9,264/sq.ft.       1
₹ 9,370/sq.ft.       1
₹ 13,522/sq.ft.      1
₹ 9,130/sq.ft.       1
₹ 7,068/sq.ft.       1
₹ 13,936/sq.ft.      1
₹ 7,561/sq.ft.       1
₹ 11,178/sq.ft.      1
₹ 12,489/sq.ft.      1
₹ 14,379/sq.ft.      1
₹ 8,026/sq.ft.       1
₹ 4,729/sq.ft.       1
₹ 11,538/sq.ft.      1
₹ 6,176/sq.ft.       1
₹ 6,256/sq.ft.       1
₹ 12,420/sq.ft.      1
₹ 7,293/sq.ft.       1
₹ 5,329/sq.ft.       1
₹ 6,751/sq.ft.       1
₹ 16,230/sq.ft.      1
₹ 4,933/sq.ft.       1
₹ 11,559/sq.ft.      1
₹ 11,525/sq.ft.      1
₹ 9,519/sq.ft.       1
₹ 4,587/sq.ft.       1
₹ 9,513/sq.ft.       1
₹ 5,950/sq.ft.       1
₹ 5,041/sq.ft.       1
₹ 6,778/sq.ft.       1
₹ 8,554/sq.ft.       1
₹ 8,487/sq.ft.       1
₹ 7,654/sq.ft.       1
₹ 15,130/sq.ft.      1
₹ 15,901/sq.ft.      1
₹ 10,134/sq.ft.      1
₹ 8,622/sq.ft.       1
₹ 10,578/sq.ft.      1
₹ 11,061/sq.ft.      1
₹ 10,656/sq.ft.      1
₹ 7,360/sq.ft.       1
₹ 11,605/sq.ft.      1
₹ 5,590/sq.ft.       1
₹ 6,926/sq.ft.       1
₹ 5,910/sq.ft.       1
₹ 9,843/sq.ft.       1
₹ 13,480/sq.ft.      1
₹ 4,927/sq.ft.       1
₹ 8,557/sq.ft.       1
₹ 8,120/sq.ft.       1
₹ 14,795/sq.ft.      1
₹ 6,951/sq.ft.       1
₹ 9,136/sq.ft.       1
₹ 11,944/sq.ft.      1
₹ 14,267/sq.ft.      1
₹ 8,737/sq.ft.       1
₹ 6,905/sq.ft.       1
₹ 5,076/sq.ft.       1
₹ 13,575/sq.ft.      1
₹ 6,346/sq.ft.       1
₹ 3,516/sq.ft.       1
₹ 4,821/sq.ft.       1
₹ 9,583/sq.ft.       1
₹ 9,639/sq.ft.       1
₹ 9,252/sq.ft.       1
₹ 10,071/sq.ft.      1
₹ 11,190/sq.ft.      1
₹ 4,931/sq.ft.       1
₹ 8,042/sq.ft.       1
₹ 7,321/sq.ft.       1
₹ 8,707/sq.ft.       1
₹ 10,773/sq.ft.      1
₹ 6,998/sq.ft.       1
₹ 8,907/sq.ft.       1
₹ 8,920/sq.ft.       1
₹ 6,083/sq.ft.       1
₹ 6,113/sq.ft.       1
₹ 6,894/sq.ft.       1
₹ 4,869/sq.ft.       1
₹ 8,111/sq.ft.       1
₹ 7,760/sq.ft.       1
₹ 8,446/sq.ft.       1
₹ 7,547/sq.ft.       1
₹ 4,579/sq.ft.       1
₹ 5,443/sq.ft.       1
₹ 8,856/sq.ft.       1
₹ 8,840/sq.ft.       1
₹ 13,296/sq.ft.      1
₹ 9,734/sq.ft.       1
₹ 5,479/sq.ft.       1
₹ 11,989/sq.ft.      1
₹ 8,297/sq.ft.       1
₹ 4,458/sq.ft.       1
₹ 7,714/sq.ft.       1
₹ 4,868/sq.ft.       1
₹ 7,769/sq.ft.       1
₹ 8,040/sq.ft.       1
₹ 7,103/sq.ft.       1
₹ 5,931/sq.ft.       1
₹ 10,723/sq.ft.      1
₹ 11,923/sq.ft.      1
₹ 6,159/sq.ft.       1
₹ 8,790/sq.ft.       1
₹ 6,979/sq.ft.       1
₹ 11,386/sq.ft.      1
₹ 11,423/sq.ft.      1
₹ 15,360/sq.ft.      1
₹ 4,923/sq.ft.       1
₹ 9,125/sq.ft.       1
₹ 9,664/sq.ft.       1
₹ 8,052/sq.ft.       1
₹ 7,951/sq.ft.       1
₹ 8,734/sq.ft.       1
₹ 11,442/sq.ft.      1
₹ 13,984/sq.ft.      1
₹ 6,556/sq.ft.       1
₹ 4,404/sq.ft.       1
₹ 16,445/sq.ft.      1
₹ 7,262/sq.ft.       1
₹ 5,952/sq.ft.       1
₹ 6,562/sq.ft.       1
₹ 11,725/sq.ft.      1
₹ 5,965/sq.ft.       1
₹ 6,587/sq.ft.       1
₹ 7,010/sq.ft.       1
₹ 5,625/sq.ft.       1
₹ 10,418/sq.ft.      1
₹ 6,137/sq.ft.       1
₹ 11,600/sq.ft.      1
₹ 5,571/sq.ft.       1
₹ 7,171/sq.ft.       1
₹ 10,903/sq.ft.      1
₹ 15,982/sq.ft.      1
₹ 8,266/sq.ft.       1
₹ 10,163/sq.ft.      1
₹ 7,402/sq.ft.       1
₹ 5,958/sq.ft.       1
₹ 6,768/sq.ft.       1
₹ 8,700/sq.ft.       1
₹ 10,482/sq.ft.      1
₹ 5,413/sq.ft.       1
₹ 5,720/sq.ft.       1
₹ 4,778/sq.ft.       1
₹ 9,856/sq.ft.       1
₹ 11,963/sq.ft.      1
₹ 10,697/sq.ft.      1
₹ 7,453/sq.ft.       1
₹ 7,882/sq.ft.       1
₹ 8,802/sq.ft.       1
₹ 6,435/sq.ft.       1
₹ 10,058/sq.ft.      1
₹ 8,387/sq.ft.       1
₹ 7,872/sq.ft.       1
₹ 8,404/sq.ft.       1
₹ 11,741/sq.ft.      1
₹ 14,838/sq.ft.      1
₹ 9,569/sq.ft.       1
₹ 19,943/sq.ft.      1
₹ 10,205/sq.ft.      1
₹ 13,989/sq.ft.      1
₹ 11,654/sq.ft.      1
₹ 11,346/sq.ft.      1
₹ 6,502/sq.ft.       1
₹ 8,123/sq.ft.       1
₹ 8,264/sq.ft.       1
₹ 11,251/sq.ft.      1
₹ 20,995/sq.ft.      1
₹ 9,371/sq.ft.       1
₹ 17,729/sq.ft.      1
₹ 10,283/sq.ft.      1
₹ 9,701/sq.ft.       1
₹ 9,102/sq.ft.       1
₹ 9,459/sq.ft.       1
₹ 17,691/sq.ft.      1
₹ 4,637/sq.ft.       1
₹ 8,347/sq.ft.       1
₹ 10,491/sq.ft.      1
₹ 10,375/sq.ft.      1
₹ 13,177/sq.ft.      1
₹ 7,891/sq.ft.       1
₹ 9,016/sq.ft.       1
₹ 6,870/sq.ft.       1
₹ 8,240/sq.ft.       1
₹ 11,920/sq.ft.      1
₹ 10,004/sq.ft.      1
₹ 6,552/sq.ft.       1
₹ 5,265/sq.ft.       1
₹ 8,850/sq.ft.       1
₹ 11,276/sq.ft.      1
₹ 9,218/sq.ft.       1
₹ 2,666/sq.ft.       1
₹ 6,022/sq.ft.       1
₹ 8,970/sq.ft.       1
₹ 8,522/sq.ft.       1
₹ 2,051/sq.ft.       1
₹ 6,914/sq.ft.       1
₹ 10,815/sq.ft.      1
₹ 6,601/sq.ft.       1
₹ 9,745/sq.ft.       1
₹ 5,495/sq.ft.       1
₹ 4,478/sq.ft.       1
₹ 5,719/sq.ft.       1
₹ 7,604/sq.ft.       1
₹ 12,912/sq.ft.      1
₹ 13,126/sq.ft.      1
₹ 4,512/sq.ft.       1
₹ 5,777/sq.ft.       1
₹ 4,694/sq.ft.       1
₹ 6,598/sq.ft.       1
₹ 4,591/sq.ft.       1
₹ 14,652/sq.ft.      1
₹ 3,692/sq.ft.       1
₹ 6,185/sq.ft.       1
₹ 5,220/sq.ft.       1
₹ 13,608/sq.ft.      1
₹ 14,009/sq.ft.      1
₹ 5,039/sq.ft.       1
₹ 4,325/sq.ft.       1
₹ 5,013/sq.ft.       1
₹ 19,444/sq.ft.      1
₹ 5,666/sq.ft.       1
₹ 4,453/sq.ft.       1
₹ 7,422/sq.ft.       1
₹ 8,515/sq.ft.       1
₹ 3,600/sq.ft.       1
₹ 4,977/sq.ft.       1
₹ 9,879/sq.ft.       1
₹ 4,250/sq.ft.       1
₹ 7,389/sq.ft.       1
₹ 4,716/sq.ft.       1
₹ 5,933/sq.ft.       1
₹ 15,178/sq.ft.      1
₹ 13,975/sq.ft.      1
₹ 7,754/sq.ft.       1
₹ 5,261/sq.ft.       1
₹ 8,990/sq.ft.       1
₹ 14,754/sq.ft.      1
₹ 12,408/sq.ft.      1
₹ 4,470/sq.ft.       1
₹ 14,551/sq.ft.      1
₹ 6,526/sq.ft.       1
₹ 15,267/sq.ft.      1
₹ 2,638/sq.ft.       1

In [59]:
# split on / , take 0th element rs.-->'' and ,--->'' , strip right left convert float bcoz none val
df['price_per_sqft'] = df['price_per_sqft'].str.split('/').str.get(0).str.replace('₹','').str.replace(',','').str.strip().astype('float')

In [60]:
df.head(2)

,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Krishna Colony,maa bhagwati residency,0.45,5000.0,Carpet area: 900 (83.61 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"Krishna Colony, Gurgaon, Haryana",4th of 4 Floors,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ..."
1,2 BHK Flat in Ashok Vihar,apna enclave,0.50,7692.0,Carpet area: 650 (60.39 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"46b, Ashok Vihar, Gurgaon, Haryana",1st of 3 Floors,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ..."

In [61]:
# areaWithType --> very dangerous col. let's skip it for now hehe^^
df['areaWithType']

0                          Carpet area: 900 (83.61 sq.m.)
1                          Carpet area: 650 (60.39 sq.m.)
2                          Carpet area: 595 (55.28 sq.m.)
3                        Carpet area: 1200 (111.48 sq.m.)
4                  Super Built up area 1345(124.95 sq.m.)
5                        Built Up area: 654 (60.76 sq.m.)
6                  Super Built up area 1500(139.35 sq.m.)
7                        Carpet area: 2290 (212.75 sq.m.)
8       Built Up area: 1350 (125.42 sq.m.)Carpet area:...
9                      Built Up area: 2813 (261.34 sq.m.)
10                        Carpet area: 1075 (99.87 sq.m.)
11                         Carpet area: 519 (48.22 sq.m.)
12                        Carpet area: 1945 (180.7 sq.m.)
13                 Super Built up area 1385(128.67 sq.m.)
14                 Super Built up area 1300(120.77 sq.m.)
15      Built Up area: 2343 (217.67 sq.m.)Carpet area:...
16                       Built Up area: 639 (59.37 sq.m.)
17                         Carpet area: 915 (85.01 sq.m.)
18                      Carpet area: 577.11 (53.62 sq.m.)
19                  Super Built up area 2100(195.1 sq.m.)
20                       Carpet area: 1103 (102.47 sq.m.)
21                 Super Built up area 2150(199.74 sq.m.)
22                 Super Built up area 1103(102.47 sq.m.)
23                       Carpet area: 2025 (188.13 sq.m.)
24                 Super Built up area 2217(205.97 sq.m.)
26                         Carpet area: 531 (49.33 sq.m.)
27      Built Up area: 3355 (311.69 sq.m.)Carpet area:...
28                       Carpet area: 2880 (267.56 sq.m.)
29                         Carpet area: 750 (69.68 sq.m.)
30      Built Up area: 1056 (98.11 sq.m.)Carpet area: ...
31                          Carpet area: 66 (55.18 sq.m.)
32      Super Built up area 3200(297.29 sq.m.)Carpet a...
33                      Carpet area: 625.47 (58.11 sq.m.)
34                     Built Up area: 1300 (120.77 sq.m.)
35                       Carpet area: 1300 (120.77 sq.m.)
36                 Super Built up area 1180(109.63 sq.m.)
37      Super Built up area 2030(188.59 sq.m.)Carpet a...
38      Super Built up area 655(60.85 sq.m.)Carpet are...
39      Super Built up area 1365(126.81 sq.m.)Built Up...
40                       Carpet area: 1320 (122.63 sq.m.)
41                       Carpet area: 1210 (112.41 sq.m.)
42                       Carpet area: 2002 (185.99 sq.m.)
43                 Super Built up area 1960(182.09 sq.m.)
44                         Carpet area: 700 (65.03 sq.m.)
45      Built Up area: 1210.73 (112.48 sq.m.)Carpet ar...
46                       Carpet area: 2727 (253.35 sq.m.)
47                       Carpet area: 1385 (128.67 sq.m.)
48                       Carpet area: 1829 (169.92 sq.m.)
49                        Carpet area: 2100 (195.1 sq.m.)
50                       Carpet area: 1650 (153.29 sq.m.)
51                       Carpet area: 1100 (102.19 sq.m.)
52                       Carpet area: 1530 (142.14 sq.m.)
53                       Carpet area: 1120 (104.05 sq.m.)
54                       Carpet area: 1250 (116.13 sq.m.)
55                       Carpet area: 2651 (246.29 sq.m.)
56                         Carpet area: 460 (42.74 sq.m.)
57                         Carpet area: 450 (41.81 sq.m.)
58                 Super Built up area 1570(145.86 sq.m.)
59                  Super Built up area 1198(111.3 sq.m.)
60      Super Built up area 900(83.61 sq.m.)Carpet are...
61      Super Built up area 1450(134.71 sq.m.)Carpet a...
62                 Super Built up area 1897(176.24 sq.m.)
63      Super Built up area 1260(117.06 sq.m.)Carpet a...
64                 Super Built up area 1725(160.26 sq.m.)
65                 Super Built up area 2200(204.39 sq.m.)
66                 Super Built up area 1875(174.19 sq.m.)
67                 Super Built up area 2250(209.03 sq.m.)
68               Super Built up area 1056.58(98.16 sq.m.)
69                   Super Built up area 560(52.03 sq.m.)
70      Built Up area: 990 (91.97 sq.m.)Carpet area: 9...
71                 Super Built up area 1370(127.28 sq.m.)
72                      Carpet area: 531.57 (49.38 sq.m.)
73      Super Built up area 575(53.42 sq.m.)Carpet are...
74                        Carpet area: 1452 (134.9 sq.m.)
75                        Carpet area: 1423 (132.2 sq.m.)
76                         Carpet area: 640 (59.46 sq.m.)
77                         Carpet area: 822 (76.37 sq.m.)
78                 Super Built up area 2159(200.58 sq.m.)
79                 Super Built up area 1950(181.16 sq.m.)
80      Built Up area: 1300 (120.77 sq.m.)Carpet area:...
81      Built Up area: 1423 (132.2 sq.m.)Carpet area: ...
82                     Carpet area: 58141 (5401.48 sq.m.)
83                 Super Built up area 3670(340.95 sq.m.)
84                   Super Built up area 1000(92.9 sq.m.)
85      Built Up area: 743 (69.03 sq.m.)Carpet area: 6...
86      Super Built up area 2250(209.03 sq.m.)Carpet a...
87                       Carpet area: 2177 (202.25 sq.m.)
88                         Carpet area: 650 (60.39 sq.m.)
89                         Carpet area: 900 (83.61 sq.m.)
90                       Carpet area: 1118 (103.87 sq.m.)
91      Built Up area: 1433 (133.13 sq.m.)Carpet area:...
92                 Super Built up area 1120(104.05 sq.m.)
93                     Built Up area: 1120 (104.05 sq.m.)
94                     Built Up area: 1996 (185.43 sq.m.)
95                       Carpet area: 1080 (100.34 sq.m.)
96                 Super Built up area 2727(253.35 sq.m.)
97                  Super Built up area 1789(166.2 sq.m.)
98                       Carpet area: 1380 (128.21 sq.m.)
99                     Built Up area: 1540 (143.07 sq.m.)
100     Super Built up area 1629(151.34 sq.m.)Carpet a...
101                Super Built up area 1828(169.83 sq.m.)
102                      Carpet area: 1950 (181.16 sq.m.)
103                      Carpet area: 1200 (111.48 sq.m.)
104                         Carpet area: 324 (30.1 sq.m.)
105     Super Built up area 2000(185.81 sq.m.)Built Up...
106                      Carpet area: 1929 (179.21 sq.m.)
107                                Super Built up area 89
108     Super Built up area 700(65.03 sq.m.)Carpet are...
109     Built Up area: 965 (89.65 sq.m.)Carpet area: 6...
110     Super Built up area 524(48.68 sq.m.)Carpet are...
111                     Carpet area: 581.41 (54.01 sq.m.)
112     Super Built up area 1197.8(111.28 sq.m.)Carpet...
113                 Super Built up area 1310(121.7 sq.m.)
114                  Carpet area: 569243 (52884.41 sq.m.)
115                        Carpet area: 750 (69.68 sq.m.)
116                      Carpet area: 1557 (144.65 sq.m.)
117                Super Built up area 1440(133.78 sq.m.)
118                      Carpet area: 2597 (241.27 sq.m.)
119     Super Built up area 1940(180.23 sq.m.)Carpet a...
120                        Carpet area: 567 (52.68 sq.m.)
121     Super Built up area 623(57.88 sq.m.)Carpet are...
122                        Carpet area: 629 (58.44 sq.m.)
123                 Super Built up area 1423(132.2 sq.m.)
124     Super Built up area 1450(134.71 sq.m.)Carpet a...
125                Super Built up area 1400(130.06 sq.m.)
126                Super Built up area 2000(185.81 sq.m.)
127                      Carpet area: 1276 (118.54 sq.m.)
128                Super Built up area 1276(118.54 sq.m.)
129                    Built Up area: 1259 (116.96 sq.m.)
130                Super Built up area 1640(152.36 sq.m.)
131                      Built Up area: 610 (56.67 sq.m.)
132                Super Built up area 1690(157.01 sq.m.)
133                     Carpet area: 481.74 (44.76 sq.m.)
134                        Carpet area: 531 (49.33 sq.m.)
135                 Super Built up area 215(179.77 sq.m.)
136     Super Built up area 1950(181.16 sq.m.)Built Up...
137                        Carpet area: 591 (54.91 sq.m.)
138                  Super Built up area 546(50.73 sq.m.)
139     Super Built up area 1530(142.14 sq.m.)Built Up...
140                      Carpet area: 1910 (177.44 sq.m.)
141                 Super Built up area 1789(166.2 sq.m.)
142                    Built Up area: 2040 (189.52 sq.m.)
143     Super Built up area 4350(404.13 sq.m.)Carpet a...
144     Super Built up area 2500(232.26 sq.m.)Built Up...
145                           Carpet area: 958 (89 sq.m.)
146                      Carpet area: 1225 (113.81 sq.m.)
147     Super Built up area 1751(162.67 sq.m.)Carpet a...
148                Super Built up area 1689(156.91 sq.m.)
149                        Carpet area: 700 (65.03 sq.m.)
150                Super Built up area 1828(169.83 sq.m.)
151                  Super Built up area 810(75.25 sq.m.)
152     Built Up area: 1440 (133.78 sq.m.)Carpet area:...
153                  Super Built up area 1000(92.9 sq.m.)
154     Built Up area: 1468 (136.38 sq.m.)Carpet area:...
155     Super Built up area 2191(203.55 sq.m.)Built Up...
156                        Carpet area: 626 (58.16 sq.m.)
157     Built Up area: 1570 (145.86 sq.m.)Carpet area:...
158                      Carpet area: 1800 (167.23 sq.m.)
159                        Carpet area: 520 (48.31 sq.m.)
160                Super Built up area 1828(169.83 sq.m.)
161              Built Up area: 118 Carpet area: 86 sq.m.
162                      Carpet area: 1630 (151.43 sq.m.)
163     Super Built up area 1275(118.45 sq.m.)Carpet a...
164                        Carpet area: 514 (47.75 sq.m.)
165     Super Built up area 1735(161.19 sq.m.)Carpet a...
166                      Carpet area: 2300 (213.68 sq.m.)
167                   Super Built up area 380(35.3 sq.m.)
168                      Carpet area: 1105 (102.66 sq.m.)
169                Super Built up area 1365(126.81 sq.m.)
170                Super Built up area 1313(121.98 sq.m.)
171                Super Built up area 1252(116.31 sq.m.)
172     Built Up area: 1000 (92.9 sq.m.)Carpet area: 6...
173                      Carpet area: 4500 (418.06 sq.m.)
174                Super Built up area 1850(171.87 sq.m.)
175                Super Built up area 2364(219.62 sq.m.)
176                Super Built up area 2727(253.35 sq.m.)
177                      Carpet area: 2800 (260.13 sq.m.)
178                      Carpet area: 1180 (109.63 sq.m.)
179                Super Built up area 1865(173.26 sq.m.)
180                      Carpet area: 1537 (142.79 sq.m.)
181                    Built Up area: 1758 (163.32 sq.m.)
182                Super Built up area 2408(223.71 sq.m.)
183                      Built Up area: 826 (76.74 sq.m.)
184                Super Built up area 1262(117.24 sq.m.)
185                      Carpet area: 2215 (205.78 sq.m.)
186                                    Carpet area: 127.3
187     Built Up area: 1430 (132.85 sq.m.)Carpet area:...
188     Super Built up area 585(54.35 sq.m.)Carpet are...
189                      Built Up area: 700 (65.03 sq.m.)
190                      Built Up area: 587 (54.53 sq.m.)
191     Super Built up area 1534(142.51 sq.m.)Built Up...
192                        Carpet area: 946 (87.89 sq.m.)
193                      Carpet area: 2298 (213.49 sq.m.)
194                Super Built up area 1320(122.63 sq.m.)
195                      Carpet area: 2400 (222.97 sq.m.)
196                      Carpet area: 1262 (117.24 sq.m.)
197                    Built Up area: 1433 (133.13 sq.m.)
198     Built Up area: 743 (69.03 sq.m.)Carpet area: 5...
199     Built Up area: 750 (69.68 sq.m.)Carpet area: 6...
200     Built Up area: 1200 (111.48 sq.m.)Carpet area:...
201     Built Up area: 950 (88.26 sq.m.)Carpet area: 7...
202                    Built Up area: 2400 (222.97 sq.m.)
203                Super Built up area 1999(185.71 sq.m.)
204                      Carpet area: 2302 (213.86 sq.m.)
205                        Carpet area: 710 (65.96 sq.m.)
206     Super Built up area 1000(92.9 sq.m.)Carpet are...
207                       Carpet area: 1069 (99.31 sq.m.)
208                Super Built up area 1433(133.13 sq.m.)
209     Built Up area: 546 (50.73 sq.m.)Carpet area: 4...
210                  Super Built up area 600(55.74 sq.m.)
211                        Carpet area: 780 (72.46 sq.m.)
212             Super Built up area 1252.13(116.33 sq.m.)
213                        Carpet area: 850 (78.97 sq.m.)
214     Super Built up area 1285(119.38 sq.m.)Built Up...
215                      Carpet area: 1400 (130.06 sq.m.)
216     Super Built up area 1452(134.9 sq.m.)Carpet ar...
217                Super Built up area 1828(169.83 sq.m.)
218                Super Built up area 2040(189.52 sq.m.)
219                      Carpet area: 5140 (477.52 sq.m.)
220                Super Built up area 1828(169.83 sq.m.)
221                Super Built up area 1261(117.15 sq.m.)
222                Super Built up area 1828(169.83 sq.m.)
223                    Built Up area: 2900 (269.42 sq.m.)
224                        Carpet area: 990 (91.97 sq.m.)
225               Super Built up area 568.46(52.81 sq.m.)
226                Super Built up area 1364(126.72 sq.m.)
227                 Super Built up area 1620(150.5 sq.m.)
228     Super Built up area 1310(121.7 sq.m.)Built Up ...
229                Super Built up area 1295(120.31 sq.m.)
230                        Carpet area: 680 (63.17 sq.m.)
231                Super Built up area 1579(146.69 sq.m.)
232                  Super Built up area 903(83.89 sq.m.)
233                    Built Up area: 1150 (106.84 sq.m.)
234                       Carpet area: 1945 (180.7 sq.m.)
235                      Carpet area: 1600 (148.64 sq.m.)
236     Super Built up area 1110(103.12 sq.m.)Built Up...
237                      Carpet area: 2025 (188.13 sq.m.)
238                      Carpet area: 1200 (111.48 sq.m.)
239                Super Built up area 1660(154.22 sq.m.)
240     Super Built up area 583(54.16 sq.m.)Built Up a...
241                    Built Up area: 1622 (150.69 sq.m.)
242                        Carpet area: 900 (83.61 sq.m.)
243     Super Built up area 1081(100.43 sq.m.)Carpet a...
244                Super Built up area 1485(137.96 sq.m.)
245                      Carpet area: 2050 (190.45 sq.m.)
246                       Carpet area: 1775 (164.9 sq.m.)
247     Super Built up area 850(78.97 sq.m.)Built Up a...
248                      Carpet area: 1433 (133.13 sq.m.)
249     Super Built up area 915(85.01 sq.m.)Carpet are...
250                Super Built up area 2940(273.13 sq.m.)
251                        Carpet area: 675 (62.71 sq.m.)
252                      Carpet area: 1151 (106.93 sq.m.)
253                Super Built up area 1260(117.06 sq.m.)
254                        Carpet area: 800 (74.32 sq.m.)
255                      Carpet area: 1600 (148.64 sq.m.)
256     Super Built up area 2350(218.32 sq.m.)Built Up...
257                      Carpet area: 1340 (124.49 sq.m.)
258                      Carpet area: 1350 (125.42 sq.m.)
259                Super Built up area 2905(269.88 sq.m.)
260                        Carpet area: 716 (66.52 sq.m.)
261                      Carpet area: 2800 (260.13 sq.m.)
262                      Carpet area: 1575 (146.32 sq.m.)
263     Super Built up area 1549(143.91 sq.m.)Carpet a...
264                Super Built up area 2467(229.19 sq.m.)
265                Super Built up area 1351(125.51 sq.m.)
266                Super Built up area 1365(126.81 sq.m.)
267                     Built Up area: 140 (117.06 sq.m.)
268                Super Built up area 1565(145.39 sq.m.)
269     Super Built up area 1295(120.31 sq.m.)Carpet a...
270                Super Built up area 1361(126.44 sq.m.)
271                      Carpet area: 1326 (123.19 sq.m.)
272                Super Built up area 1960(182.09 sq.m.)
273                        Carpet area: 997 (92.62 sq.m.)
274                     Built Up area: 1310 (121.7 sq.m.)
275                     Built Up area: 1310 (121.7 sq.m.)
276                Super Built up area 1095(101.73 sq.m.)
277     Super Built up area 1380(128.21 sq.m.)Built Up...
278                     Built Up area: 1423 (132.2 sq.m.)
279                      Built Up area: 700 (65.03 sq.m.)
280                    Built Up area: 1997 (185.53 sq.m.)
281                    Built Up area: 1523 (141.49 sq.m.)
282                    Built Up area: 1382 (128.39 sq.m.)
283     Built Up area: 804 (74.69 sq.m.)Carpet area: 6...
284                    Built Up area: 3350 (311.23 sq.m.)
285     Super Built up area 2408(223.71 sq.m.)Built Up...
287                Super Built up area 2600(241.55 sq.m.)
288     Built Up area: 2200 (204.39 sq.m.)Carpet area:...
289                      Carpet area: 3844 (357.12 sq.m.)
290                Super Built up area 1780(165.37 sq.m.)
291     Super Built up area 2000(185.81 sq.m.)Carpet a...
292                      Carpet area: 4328 (402.08 sq.m.)
293                      Carpet area: 1750 (162.58 sq.m.)
294                         Carpet area: 761 (70.7 sq.m.)
295                       Carpet area: 2452 (227.8 sq.m.)
296                       Carpet area: 1508 (140.1 sq.m.)
297     Super Built up area 1500(139.35 sq.m.)Carpet a...
298                Super Built up area 1407(130.71 sq.m.)
299                Super Built up area 1630(151.43 sq.m.)
300                        Carpet area: 745 (69.21 sq.m.)
301                      Carpet area: 1806 (167.78 sq.m.)
302               Built Up area: 97 Carpet area: 92 sq.m.
303                      Carpet area: 1450 (134.71 sq.m.)
304                Super Built up area 1100(102.19 sq.m.)
305                      Carpet area: 2300 (213.68 sq.m.)
306                Super Built up area 2786(258.83 sq.m.)
307     Built Up area: 1852 (172.06 sq.m.)Carpet area:...
308                    Carpet area: 1249.65 (116.1 sq.m.)
309                Super Built up area 2605(242.01 sq.m.)
310                      Carpet area: 1549 (143.91 sq.m.)
311     Super Built up area 1650(153.29 sq.m.)Carpet a...
312                      Carpet area: 1671 (155.24 sq.m.)
313                Super Built up area 1350(125.42 sq.m.)
314     Built Up area: 2060 (191.38 sq.m.)Carpet area:...
315                      Carpet area: 2000 (185.81 sq.m.)
316                       Carpet area: 2100 (195.1 sq.m.)
317                      Carpet area: 2750 (255.48 sq.m.)
318                Super Built up area 1572(146.04 sq.m.)
319     Super Built up area 1870(173.73 sq.m.)Built Up...
320     Built Up area: 2200 (204.39 sq.m.)Carpet area:...
321                      Carpet area: 3844 (357.12 sq.m.)
322                Super Built up area 1780(165.37 sq.m.)
323     Super Built up area 2000(185.81 sq.m.)Carpet a...
324                       Carpet area: 2452 (227.8 sq.m.)
325                       Carpet area: 1508 (140.1 sq.m.)
326                Super Built up area 1407(130.71 sq.m.)
327                        Carpet area: 745 (69.21 sq.m.)
328                      Carpet area: 1806 (167.78 sq.m.)
329               Built Up area: 97 Carpet area: 92 sq.m.
330                      Carpet area: 1450 (134.71 sq.m.)
331                Super Built up area 1100(102.19 sq.m.)
332                      Carpet area: 2300 (213.68 sq.m.)
333                Super Built up area 2786(258.83 sq.m.)
334     Built Up area: 1852 (172.06 sq.m.)Carpet area:...
335                Super Built up area 2605(242.01 sq.m.)
336     Super Built up area 1650(153.29 sq.m.)Carpet a...
337                Super Built up area 1350(125.42 sq.m.)
338                      Carpet area: 2000 (185.81 sq.m.)
339                       Carpet area: 2100 (195.1 sq.m.)
340                Super Built up area 1572(146.04 sq.m.)
341                Super Built up area 2892(268.68 sq.m.)
342                Super Built up area 2143(199.09 sq.m.)
343                      Carpet area: 1304 (121.15 sq.m.)
344     Super Built up area 1758(163.32 sq.m.)Carpet a...
345     Built Up area: 1250 (116.13 sq.m.)Carpet area:...

In [62]:
#bedroom
df['bedRoom'].value_counts()

bedRoom
3 Bedrooms    1435
2 Bedrooms     944
4 Bedrooms     477
1 Bedroom      104
5 Bedrooms      31
6 Bedrooms       3
Name: count, dtype: int64

In [64]:
df[df['bedRoom'].isnull()]

,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
2923,3 BHK Flat in Sector 99A Gurgaon,pareena coban residences,NaN,5759.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2924,1 BHK Flat in Golf Course Ext Road,ikon tower baani city centre,NaN,12437.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2925,2 BHK Flat in Sector 89 Gurgaon,greenopolis,NaN,4820.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2927,4 BHK Flat in C Block Sushant Lok Phase 1,maple heights,NaN,8888.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2928,2 BHK Flat in Sector 99 Gurgaon,assotech blith,NaN,6593.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2994,4 BHK Flat in DLF Phase 4,chanderlok society,NaN,7234.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [65]:
# remove these rows since i can't fill these many rows
df = df[~df['bedRoom'].isnull()]

In [71]:
# int val convert 
df['bedRoom']= df['bedRoom'].str.split(' ').str.get(0).str.strip().astype('int')

In [72]:
# bathroom
df['bathroom'].value_counts()

bathroom
2 Bathrooms    1043
3 Bathrooms     987
4 Bathrooms     636
5 Bathrooms     169
1 Bathroom      112
6 Bathrooms      42
7 Bathrooms       5
Name: count, dtype: int64

In [77]:
df['bathroom'].isnull().sum() # no empty row

0

In [78]:
df['bathroom']= df['bathroom'].str.split(' ').str.get(0).str.strip().astype('int')

In [79]:
# balcony
df['balcony'].value_counts() # 3+ is present

balcony
3 Balconies     973
3+ Balconies    861
2 Balconies     748
1 Balcony       315
No Balcony       97
Name: count, dtype: int64

In [80]:
df['balcony'].isnull().sum() # no empty row

0

In [85]:
df['balcony'] = df['balcony'].str.split(' ').str.get(0).str.replace('No','0')

In [86]:
df.head(2)

,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Krishna Colony,maa bhagwati residency,0.45,5000.0,Carpet area: 900 (83.61 sq.m.),2,2,1,NaN,"Krishna Colony, Gurgaon, Haryana",4th of 4 Floors,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ..."
1,2 BHK Flat in Ashok Vihar,apna enclave,0.50,7692.0,Carpet area: 650 (60.39 sq.m.),2,2,1,NaN,"46b, Ashok Vihar, Gurgaon, Haryana",1st of 3 Floors,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ..."

In [89]:
# additional room
df['additionalRoom'].value_counts()

additionalRoom
Servant Room                                     629
Study Room                                       232
Others                                           178
Pooja Room                                       132
Study Room,Servant Room                           81
Store Room                                        76
Pooja Room,Servant Room                           60
Servant Room,Others                               52
Servant Room,Pooja Room                           30
Study Room,Others                                 27
Pooja Room,Study Room,Servant Room,Others         25
Pooja Room,Study Room,Servant Room                24
Servant Room,Store Room                           19
Pooja Room,Study Room                             13
Pooja Room,Study Room,Servant Room,Store Room     12
Study Room,Pooja Room                              8
Servant Room,Study Room                            8
Study Room,Servant Room,Store Room                 7
Pooja Room,Store Room                              6
Pooja Room,Others                                  6
Others,Servant Room                                6
Servant Room,Study Room,Pooja Room,Store Room      6
Pooja Room,Servant Room,Others                     6
Study Room,Servant Room,Others                     5
Pooja Room,Store Room,Study Room,Servant Room      4
Pooja Room,Study Room,Store Room                   4
Servant Room,Pooja Room,Study Room,Store Room      3
Study Room,Pooja Room,Store Room                   3
Store Room,Servant Room                            3
Servant Room,Study Room,Store Room                 2
Pooja Room,Study Room,Others                       2
Study Room,Pooja Room,Servant Room                 2
Servant Room,Others,Store Room,Pooja Room          2
Servant Room,Others,Pooja Room                     2
Study Room,Servant Room,Pooja Room,Store Room      2
Others,Study Room                                  1
Servant Room,Study Room,Others                     1
Servant Room,Pooja Room,Study Room                 1
Servant Room,Study Room,Pooja Room                 1
Store Room,Pooja Room,Servant Room                 1
Servant Room,Pooja Room,Store Room,Study Room      1
Study Room,Store Room                              1
Store Room,Study Room                              1
Servant Room,Pooja Room,Store Room                 1
Study Room,Servant Room,Store Room,Pooja Room      1
Study Room,Servant Room,Pooja Room                 1
Pooja Room,Servant Room,Study Room,Store Room      1
Pooja Room,Study Room,Store Room,Servant Room      1
Store Room,Pooja Room                              1
Name: count, dtype: int64

In [92]:
df['additionalRoom'].value_counts().shape #too many categories sso just waiting

(49,)

In [93]:
df['additionalRoom'].isnull().sum()

1303

In [94]:
df['additionalRoom'].fillna('not available', inplace = True)
df['additionalRoom'] = df['additionalRoom'].str.lower().str.strip()

In [95]:
df.head(3)

,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Krishna Colony,maa bhagwati residency,0.45,5000.0,Carpet area: 900 (83.61 sq.m.),2,2,1,not available,"Krishna Colony, Gurgaon, Haryana",4th of 4 Floors,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ..."
1,2 BHK Flat in Ashok Vihar,apna enclave,0.50,7692.0,Carpet area: 650 (60.39 sq.m.),2,2,1,not available,"46b, Ashok Vihar, Gurgaon, Haryana",1st of 3 Floors,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ..."
2,2 BHK Flat in Sohna,tulsiani easy in homes,0.40,6722.0,Carpet area: 595 (55.28 sq.m.),2,2,3,not available,"Sohna, Gurgaon, Haryana",12nd of 14 Floors,NaN,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment4 out of 5', 'Safety4 out of 5', ..."

In [96]:
# address is bit complex on hold ( observed froom EXCEL)
# floorNum
df['floorNum'].value_counts()

floorNum
2nd   of 4 Floors           74
3rd   of 4 Floors           71
4th   of 4 Floors           62
1st   of 4 Floors           61
12nd   of 14 Floors         49
14th   of 14 Floors         48
Ground of 14 Floors         40
10th   of 14 Floors         35
7th   of 14 Floors          35
8th   of 14 Floors          34
4th   of 14 Floors          28
6th   of 14 Floors          27
2nd   of 2 Floors           26
1st   of 14 Floors          26
3rd   of 3 Floors           26
3rd   of 14 Floors          24
5th   of 14 Floors          24
8th   of 19 Floors          24
11st   of 14 Floors         23
1st   of 1 Floors           23
9th   of 14 Floors          23
9th   of 9 Floors           23
5th   of 12 Floors          22
2nd   of 3 Floors           22
2nd   of 14 Floors          21
8th   of 18 Floors          20
10th   of 19 Floors         18
6th   of 18 Floors          18
10th   of 18 Floors         17
9th   of 13 Floors          17
7th   of 15 Floors          17
12nd   of 12 Floors         17
Ground of 1 Floors          17
7th   of 18 Floors          17
3rd   of 18 Floors          16
5th   of 15 Floors          16
9th   of 15 Floors          15
1st   of 3 Floors           15
2nd   of 12 Floors          15
6th   of 12 Floors          15
6th   of 19 Floors          14
Ground of 4 Floors          13
10th   of 26 Floors         13
3rd   of 13 Floors          13
7th   of 7 Floors           13
6th   of 10 Floors          13
6th   of 15 Floors          12
1st   of 2 Floors           12
5th   of 5 Floors           12
10th   of 10 Floors         12
11st   of 18 Floors         11
17th   of 17 Floors         11
4th   of 10 Floors          11
9th   of 26 Floors          11
15th   of 19 Floors         11
9th   of 24 Floors          11
6th   of 6 Floors           11
16th   of 19 Floors         11
8th   of 12 Floors          11
4th   of 13 Floors          11
8th   of 8 Floors           11
3rd   of 5 Floors           10
7th   of 26 Floors          10
4th   of 12 Floors          10
7th   of 13 Floors          10
2nd   of 19 Floors          10
7th   of 21 Floors          10
12nd   of 18 Floors         10
6th   of 13 Floors          10
4th   of 15 Floors          10
3rd   of 9 Floors           10
10th   of 12 Floors         10
1st   of 26 Floors          10
18th   of 19 Floors          9
8th   of 15 Floors           9
14th   of 19 Floors          9
14th   of 15 Floors          9
12nd   of 17 Floors          9
5th   of 18 Floors           9
3rd   of 12 Floors           9
6th   of 16 Floors           9
7th   of 17 Floors           9
7th   of 12 Floors           9
13rd   of 14 Floors          9
8th   of 22 Floors           9
9th   of 20 Floors           9
15th   of 29 Floors          9
6th   of 26 Floors           9
5th   of 9 Floors            8
2nd   of 8 Floors            8
9th   of 18 Floors           8
8th   of 24 Floors           8
10th   of 17 Floors          8
12nd   of 19 Floors          8
10th   of 13 Floors          8
8th   of 26 Floors           8
1st   of 19 Floors           8
2nd   of 15 Floors           8
4th   of 26 Floors           8
12nd   of 26 Floors          8
3rd   of 19 Floors           8
8th   of 13 Floors           8
12nd   of 24 Floors          8
2nd   of 5 Floors            8
5th   of 13 Floors           8
9th   of 12 Floors           8
14th   of 24 Floors          8
7th   of 19 Floors           7
10th   of 21 Floors          7
3rd   of 15 Floors           7
11st   of 13 Floors          7
2nd   of 13 Floors           7
5th   of 29 Floors           7
1st   of 13 Floors           7
8th   of 21 Floors           7
11st   of 24 Floors          7
8th   of 10 Floors           7
11st   of 26 Floors          7
11st   of 11 Floors          7
5th   of 20 Floors           7
13rd   of 13 Floors          7
12nd   of 15 Floors          7
2nd   of 10 Floors           7
12nd   of 13 Floors          7
4th   of 19 Floors           7
9th   of 19 Floors           7
2nd   of 17 Floors           7
16th   of 16 Floors          7
16th   of 18 Floors          6
1st   of 5 Floors            6
11st   of 12 Floors          6
10th   of 29 Floors          6
14th   of 27 Floors          6
4th   of 17 Floors           6
5th   of 22 Floors           6
5th   of 25 Floors           6
7th   of 20 Floors           6
1st   of 10 Floors           6
4th   of 18 Floors           6
10th   of 15 Floors          6
10th   of 20 Floors          6
Ground of 15 Floors          6
11st   of 19 Floors          6
Ground of 3 Floors           6
2nd   of 20 Floors           6
19th   of 19 Floors          6
Ground of 16 Floors          6
17th   of 19 Floors          6
3rd   of 25 Floors           6
15th   of 15 Floors          6
6th   of 9 Floors            6
12nd   of 22 Floors          6
5th   of 10 Floors           6
9th   of 22 Floors           5
10th   of 25 Floors          5
7th   of 27 Floors           5
Ground of 19 Floors          5
14th   of 29 Floors          5
12nd   of 29 Floors          5
15th   of 28 Floors          5
4th   of 22 Floors           5
3rd   of 20 Floors           5
9th   of 30 Floors           5
4th   of 9 Floors            5
6th   of 17 Floors           5
11st   of 16 Floors          5
4th   of 27 Floors           5
11st   of 29 Floors          5
6th   of 11 Floors           5
5th   of 19 Floors           5
8th   of 30 Floors           5
15th   of 18 Floors          5
1st   of 15 Floors           5
12nd   of 21 Floors          5
15th   of 21 Floors          5
7th   of 8 Floors            5
9th   of 11 Floors           5
8th   of 9 Floors            5
14th   of 16 Floors          5
11st   of 25 Floors          5
18th   of 29 Floors          5
5th   of 8 Floors            5
Ground of 12 Floors          5
10th   of 27 Floors          5
1st   of 7 Floors            5
10th   of 24 Floors          5
6th   of 20 Floors           5
16th   of 26 Floors          5
11st   of 30 Floors          5
Ground of 21 Floors          5
1st   of 12 Floors           5
25th   of 25 Floors          4
20th   of 26 Floors          4
13rd   of 19 Floors          4
13rd   of 25 Floors          4
13rd   of 21 Floors          4
17th   of 25 Floors          4
8th   of 16 Floors           4
17th   of 26 Floors          4
7th   of 11 Floors           4
7th   of 24 Floors           4
12nd   of 30 Floors          4
15th   of 16 Floors          4
6th   of 30 Floors           4
15th   of 23 Floors          4
5th   of 16 Floors           4
Ground of 17 Floors          4
2nd   of 9 Floors            4
15th   of 25 Floors          4
14th   of 26 Floors          4
17th   of 18 Floors          4
Ground of 13 Floors          4
8th   of 20 Floors           4
5th   of 23 Floors           4
5th   of 24 Floors           4
3rd   of 22 Floors           4
15th   of 26 Floors          4
2nd   of 11 Floors           4
22nd   of 30 Floors          4
3rd   of 10 Floors           4
3rd   of 17 Floors           4
17th   of 24 Floors          4
15th   of 32 Floors          4
7th   of 9 Floors            4
3rd   of 11 Floors           4
20th   of 20 Floors          4
23rd   of 26 Floors          4
18th   of 32 Floors          4
14th   of 21 Floors          4
2nd   of 16 Floors           4
7th   of 10 Floors           4
19th   of 40 Floors          4
9th   of 10 Floors           4
12nd   of 16 Floors          4
14th   of 17 Floors          4
4th   of 8 Floors            4
11st   of 17 Floors          4
11st   of 15 Floors          4
14th   of 18 Floors          4
19th   of 24 Floors          4
1st   of 18 Floors           4
11st   of 20 Floors          4
22nd   of 24 Floors          4
3rd   of 26 Floors           3
3rd   of 16 Floors           3
10th   of 16 Floors          3
13rd   of 15 Floors          3
10th   of 28 Floors          3
12nd   of 23 Floors          3
4th   of 20 Floors           3
2nd   of 26 Floors           3
31st   of 32 Floors          3
1st   of 11 Floors           3
8th   of 17 Floors           3
21st   of 24 Floors          3
19th   of 21 Floors          3
17th   of 30 Floors          3
1st   of 35 Floors           3
4th   of 21 Floors           3
27th   of 27 Floors          3
14th   of 32 Floors          3
11st   of 27 Floors          3
10th   of 23 Floors          3
2nd   of 22 Floors           3
24th   of 24 Floors          3
21st   of 22 Floors          3
17th   of 20 Floors          3
4th   of 16 Floors           3
6th   of 29 Floors           3
6th   of 24 Floors           3
8th   of 25 Floors           3
30th   of 32 Floors          3
19th   of 30 Floors          3
4th   of 29 Floors           3
17th   of 29 Floors          3
18th   of 18 Floors          3
6th   of 21 Floors           3
5th   of 17 Floors           3
1st   of 25 Floors           3
5th   of 26 Floors           3
19th   of 29 Floors          3
18th   of 30 Floors          3
23rd   of 23 Floors          3
12nd   of 27 Floors          3
18th   of 26 Floors          3
8th   of 11 Floors           3
6th   of 22 Floors           3
6th   of 23 Floors           3
7th   of 23 Floors           3
15th   of 20 Floors          3
15th   of 40 Floors          3
15th   of 22 Floors          3
Ground of 18 Floors          3
16th   of 20 Floors          3
9th   of 21 Floors           3
3rd   of 8 Floors            3
6th   of 8 Floors            3
15th   of 39 Floors          3
20th   of 28 Floors          3
8th   of 40 Floors           3
Ground of 26 Floors          3
10th   of 30 Floors          3
26th   of 30 Floors          3
5th   of 30 Floors           3
9th   of 16 Floors           3
9th   of 40 Floors           3
11st   of 23 Floors          2
Lower Ground of 4 Floors     2
2nd   of 40 Floors           2
23rd   of 29 Floors          2
21st   of 27 Floors          2
13rd   of 20 Floors          2
9th   of 29 Floors           2
10th   of 40 Floors          2
25th   of 29 Floors          2
7th   of 22 Floors           2
13rd   of 30 Floors          2
4th   of 34 Floors           2
8th   of 23 Floors           2
9th   of 27 Floors           2
19th   of 27 Floors          2
3rd   of 24 Floors           2
27th   of 29 Floors          2
2nd   of 28 Floors           2
40th   of 40 Floors          2
17th   of 23 Floors          2
4th   of 7 Floors            2
15th   of 24 Floors          2
2nd   of 18 Floors           2
2nd   of 7 Floors            2
2nd   of 25 Floors           2
24th   of 30 Floors          2
2nd   of 6 Floors            2
20th   of 22 Floors          2
22nd   of 25 Floors          2
2nd   of 32 Floors           2
43   of 47 Floors            2
1st   of 30 Floors           2
1st   of 20 Floors           2
15th   of 31 Floors          2
1st   of 8 Floors            2
11st   of 21 Floors          2
23rd   of 34 Floors          2
16th   of 34 Floors          2
18th   of 24 Floors          2
16th   of 30 Floors          2
16th   of 27 Floors          2
7th   of 30 Floors           2
14th   of 20 Floors          2
19th   of 20 Floors          2
16th   of 21 Floors          2
8th   of 34 Floors           2
25th   of 30 Floors          2
16th   of 24 Floors          2
20th   of 23 Floors          2
16th   of 36 Floors          2
9th   of 28 Floors           2
2nd   of 24 Floors           2
1st   of 17 Floors           2
3rd   of 33 Floors           2
8th   of 32 Floors           2
10th   of 32 Floors          2
Ground of 51 Floors          2
39th   of 40 Floors          2
28th   of 30 Floors          2
7th   of 16 Floors           2
13rd   of 40 Floors          2
20th   of 25 Floors          2
9th   of 17 Floors           2
4th   of 5 Floors            2
12nd   of 25 Floors          2
1st   of 24 Floors           2
6th   of 31 Floors           2
7th   of 29 Floors           2
1st   of 22 Floors           2
10th   of 22 Floors          2
5th   of 11 Floors           2
2nd   of 21 Floors           2
17th   of 33 Floors          2
8th   of 28 Floors           2
10th   of 11 Floors          2
Ground of 23 Floors          2
8th   of 29 Floors           2
3rd   of 27 Floors           2
14th   of 28 Floors          2
3rd   of 32 Floors           2
15th   of 17 Floors          2
16th   of 32 Floors          2
3rd   of 29 Floors           2
18th   of 21 Floors          2
15th   of 45 Floors          2
7th   of 36 Floors           2
1st   of 16 Floors           2
4th   of 11 Floors           2
5th   of 35 Floors           1
13rd   of 34 Floors          1
3rd   of 28 Floors           1
12nd   of 40 Floors          1
7th   of 40 Floors           1
13rd   of 26 Floors          1
17th   of 28 Floors          1
18th   of 35 Floors          1
22nd   of 40 Floors          1
14th   of 25 Floors          1
Ground of 2 Floors           1
16th   of 41 Floors          1
13rd   of 22 Floors          1
3rd   of 7 Floors            1
17th   of 31 Floors          1
Ground of 40 Floors          1
Ground of 5 Floors           1
21st   of 23 Floors          1
Ground of 22 Floors          1
10th   of 33 Floors          1
3rd   of 30 Floors           1
3rd   of 31 Floors           1
Lower Ground of 1 Floors     1
19th   of 32 Floors          1
Ground of 6 Floors           1
13rd   of 17 Floors          1
20th   of 24 Floors          1
45   of 47 Floors            1
22nd   of 23 Floors          1
30th   of 34 Floors          1
Ground of 25 Floors          1
16th   of 45 Floors          1
1st   of 6 Floors            1
9th   of 25 Floors           1
13rd   of 47 Floors          1
5th   of 36 Floors           1
34th   of 34 Floors          1
34th   of 42 Floors          1
9th   of 23 Floors           1
29th   of 39 Floors          1
33rd   of 33 Floors          1
27th   of 30 Floors          1
4th   of 6 Floors            1
7th   of 28 Floors           1
8th   of 35 Floors           1
Ground of 29 Floors          1
16th   of 35 Floors          1
44   of 47 Floors            1
5th   of 6 Floors            1
22nd   of 26 Floors          1
3rd   of 36 Floors           1
29th   of 29 Floors          1
16th   of 31 Floors          1
5th   of 21 Floors           1
14th   of 41 Floors          1
5th   of 34 Floors           1
24th   of 36 Floors          1
17th   of 22 Floors          1
21st   of 36 Floors          1
23rd   of 24 Floors          1
18th   of 22 Floors          1
Basement of 13 Floors        1
12nd   of 34 Floors          1
17th   of 47 Floors          1
18th   of 20 Floors          1
24th   of 27 Floors          1
21st   of 26 Floors          1
26th   of 47 Floors          1
7th   of 25 Floors           1
Ground of 11 Floors          1
8th   of 42 Floors           1
26th   of 34 Floors          1
21st   of 29 Floors          1
14th   of 22 Floors          1
33rd   of 42 Floors          1
1st   of 44 Floors           1
24th   of 31 Floors          1
24th   of 51 Floors          1
11st   of 22 Floors          1
2nd   of 36 Floors           1
19th   of 31 Floors          1
16th   of 51 Floors          1
25th   of 36 Floors          1
21st   of 28 Floors          1
7th   of 42 Floors           1
10th   of 51 Floors          1
15th   of 30 Floors          1
Ground of 24 Floors          1
35th   of 35 Floors          1
10th   of 39 Floors          1
33rd   of 48 Floors          1
21st   of 41 Floors          1
32nd   of 32 Floors          1
32nd   of 55 Floors          1
20th   of 32 Floors          1
Basement of 28 Floors        1
19th   of 41 Floors          1
20th   of 34 Floors          1
29th   of 31 Floors          1
16th   of 22 Floors          1
18th   of 25 Floors          1
23rd   of 28 Floors          1
11st   of 36 Floors          1
28th   of 28 Floors          1
Basement of 4 Floors         1
2nd   of 34 Floors           1
4th   of 40 Floors           1
20th   of 47 Floors          1
27th   of 48 Floors          1
6th   of 7 Floors            1
3rd   of 6 Floors            1
20th   of 40 Floors          1
31st   of 40 Floors          1
9th   of 42 Floors           1
4th   of 28 Floors           1
7th   of 32 Floors           1
30th   of 40 Floors          1
4th   of 25 Floors           1
19th   of 23 Floors          1
5th   of 27 Floors           1
24th   of 39 Floors          1
20th   of 43 Floors          1
21st   of 51 Floors          1
12nd   of 28 Floors          1
10th   of 34 Floors          1
18th   of 23 Floors          1
12nd   of 32 Floors          1
23rd   of 40 Floors          1
5th   of 32 Floors           1
1st   of 9 Floors            1
20th   of 29 Floors          1
13rd   of 18 Floors          1
7th   of 34 Floors           1
16th   of 25 Floors          1
6th   of 25 Floors           1
3rd   of 40 Floors           1
12nd   of 39 Floors          1
8th   of 31 Floors           1
20th   of 30 Floors          1
18th   of 51 Floors          1
19th   of 22 Floors          1
19th   of 26 Floors          1
2nd   of 27 Floors           1
14th   of 51 Floors          1
19th   of 39 Floors          1
38th   of 40 Floors          1
15th   of 27 Floors          1
18th   of 40 Floors          1
35th   of 51 Floors          1
22nd   of 28 Floors          1
17th   of 21 Floors          1
4th   of 39 Floors           1
24th   of 32 Floors          1
8th   of 27 Floors           1
28th   of 29 Floors          1
23rd   of 36 Floors          1
Name: count, dtype: int64

In [98]:
df['floorNum'].isnull().sum()

2

In [99]:
df[df['floorNum'].isnull()] # may be filled when we wiill treate nan val

,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
181,3 BHK Flat in Dwarka Expressway Gurgaon,experion heartsong,1.08,6150.0,Built Up area: 1758 (163.32 sq.m.),3,3,0,not available,"604, Tower B-3, 6th Floor,Sector 108, Dwarka E...",NaN,NaN,Under Construction,NaN,A property by one of the most reputed builders...,[],NaN,NaN
2767,2 BHK Flat in Sector 78 Gurgaon,nan,0.60,3692.0,Built Up area: 1625 (150.97 sq.m.),2,2,0,not available,"Gurgaon, Sector 78 Gurgaon, Gurgaon, Haryana",NaN,NaN,Under Construction,NaN,The property is under construction it's by rah...,[],NaN,"['Safety4 out of 5', 'Lifestyle4 out of 5', 'E..."

In [109]:
# Ground , Lower ,Basement , treating them
temp = df['floorNum'].str.split(' ').str.get(0).str.replace('Ground','0').str.strip().str.replace('Lower','').str.strip().str.replace('Basement','-1').str.strip().str.extract(r'(\d+)')
temp

        0
0       4
1       1
2      12
3       2
4       5
5       3
6       5
7      14
8       2
9      31
10      1
11      4
12      4
13      3
14     13
15     25
16      0
17      0
18     11
19     12
20      4
21     11
22      4
23      0
24     10
26      3
27     20
28      5
29      4
30      4
31      1
32     12
33      8
34     20
35      8
36     21
37      0
38      6
39      1
40      1
41     12
42      6
43      1
44      2
45      1
46      9
47      5
48     18
49     29
50      3
51      3
52      5
53      1
54      9
55      6
56      2
57     14
58      1
59      8
60      2
61     12
62      4
63      1
64      7
65      3
66      5
67      9
68     14
69     14
70     15
71      6
72      6
73      2
74      3
75      2
76      4
77      3
78      6
79      8
80      2
81      4
82      0
83     11
84      1
85     11
86     21
87      4
88      2
89      2
90      4
91     32
92      2
93      2
94      2
95     11
96     23
97      6
98      9
99      1
100     5
101    43
102     1
103     1
104     1
105    11
106    14
107     9
108     8
109     9
110     2
111     4
112    32
113    43
114     2
115     3
116     8
117     3
118    20
119     2
120     1
121     4
122     0
123     3
124     4
125     3
126     6
127    13
128    13
129    16
130     3
131     0
132    11
133     2
134    12
135     2
136     1
137     4
138    11
139     5
140     1
141    12
142    16
143     6
144     2
145     3
146    11
147    10
148     2
149     4
150    19
151     1
152     8
153    18
154    10
155     7
156     2
157    10
158     5
159    10
160    20
161    20
162     3
163    13
164     3
165     7
166     4
167     4
168     2
169     2
170     4
171     3
172     1
173     2
174    11
175    11
176    16
177     8
178     1
179    18
180     8
181   NaN
182     2
183    17
184    23
185    10
186    30
187     4
188     2
189     0
190     0
191     1
192     1
193    11
194    11
195     0
196    19
197    28
198     4
199     9
200     7
201     1
202    15
203     2
204     0
205     9
206     1
207     1
208     4
209     4
210     3
211     1
212     1
213   NaN
214    13
215     4
216     6
217    20
218    27
219     6
220    33
221    35
222    26
223     0
224     2
225     4
226    10
227    11
228    10
229     0
230     3
231     7
232     8
233     2
234     3
235     1
236     9
237    14
238     4
239     8
240    10
241     3
242     3
243     2
244     3
245     7
246     2
247     3
248     8
249    12
250     8
251     1
252     1
253    26
254    21
255     8
256     2
257     1
258     2
259    39
260     1
261     8
262     2
263     3
264     7
265     4
266    22
267    14
268    11
269    17
270     3
271    12
272     8
273     3
274    14
275     7
276     9
277     2
278     3
279     6
280    16
281    12
282     1
283     4
284    17
285     7
287    11
288     4
289     1
290     6
291     1
292    17
293     1
294    16
295    19
296    31
297    14
298     5
299     2
300     1
301     1
302    15
303     1
304     1
305     2
306    11
307     9
308    33
309    14
310     4
311     5
312    18
313     1
314    20
315     9
316    18
317     8
318     4
319     9
320     4
321     1
322     6
323     1
324    19
325    31
326     5
327     1
328     1
329    15
330     1
331     1
332     2
333    11
334     9
335    14
336     5
337     1
338     9
339    18
340     4
341     1
342    20
343    24
344     2
345     4
346    14
347     9
348    14
349     4
350    26
351     2
352    14
353    17
354     2
355    25
356     9
357     4
358     6
359     5
360     4
361    14
362    15
363     7
364     2
365    16
366    24
367    10
368     2
369     2
370     2
371     1
372     8
373    12
374    18
375     1
376     2
377     3
378    11
379     7
380     5
381     6
382    19
383    25
384    10
385    10
386     3
387     8
388     5
389     4
390     1
391    10
392    16
393    10
394     3
395    17
396     9
397    11
398    19
399     0
400     0
401     8
402     4
403    30
404    16
405    18
406     2
407     7
408     2
409    10
410     9
411     6
412    14
413    25
414     7
415     4
416     7
417    18
418    12
419     3
420    21
421    14
422     5
423     3
424    19
425    10
426     5
427    10
428     7
429    11
430     2
431     2
432     7
433     6
434    11
435     9
436     4
437    14
438     5
439     1
440    16
441     1
442    18
443     6
444     8
445     4
446     7
447     9
448     3
449    11
450    17
451     7
452     5
453    16
454     2
455     8
456     2
457     3
458     6
459     0
460     2
461    15
462    10
463    11
464    10
465     4
466     3
467     9
468     8
469     7
470     5
471     7
472     7
473     9
474     2
475     5
476    11
477     8
478     7
479    20
480    10
481     7
482    10
483    16
484     8
485     1
486    18
487    15
488    25
489     5
490     9
491     5
492     7
493     7
494     7
495    12
496     5
497     4
498     6
499     3
500    10
501    15
502    15
503    10
504     9
505    10
506    10
507     9
508     0
509     1
510    11
511    17
512     1
513     0
514     7
515     5
516    12
517    14
518    14
519     9
520    19
521     8
522    14
523     8
524     2
525     9
526     5
527     0
528     6
529    10
530     6
531     8
532     9
533     9
534    12
535    11
536     6
537    15
538     7
539     8
540     8
541     3
542    10
543     1
544     4
545     5
546     2
547    20
548    13
549     8
550     8
551    16
552    12
553    10
554     6
555    16
556     8
557    12
558    12
559     5
560     9
561     7
562     7
563     7
564     5
565     8
566     7
567     5
568     9
569    11
570    10
571     6
572     3
573    22
574     5
575    15
576     5
577     0
578     6
579     1
580     2
581    12
582    12
583     6
584     8
585     4
586     5
587     2
588    20
589    12
590    18
591     2
592     3
593     3
594    18
595     7
596    17
597     8
598     2
599     8
600     9
601     3
602    12
603    10
604     2
605     0
606     7
607     2
608     5
609     3
610     3
611    12
612     6
613    28
614    10
615    24
616     4
617     0
618    17
619    12
620    19
621    15
622    10
623     3
624     9
625    15
626    19
627     6
628    21
629    14
630    20
631     7
632     2
633     5
634    14
635    16
636    12
637     3
638     7
639    10
640    11
641    17
642     8
643     6
644    10
645    11
646     4
647    15
648    19
649     5
650    14
651     6
652    17
653     7
654     7
655    12
656    10
657    38
658     8
659    18
660     9
661    19
662     3
663     9
664     7
665    14
666     1
667     0
668     5
669     0
670    10
671     8
672     0
673    10
674    23
675     7
676     6
677     7
678    18
679     5
680    17
681     3
682     7
683     4
684     1
685     6
686    10
687     6
688     0
689     8
690     5
691    14
692    15
693     7
694    10
695    10
696     8
697    11
698     3
699    12
700     5
701     8
702     4
703    10
704    12
705    17
706     2
707     9
708     1
709    10
710     7
711    11
712    11
713    11
714    15
715     8
716     8
717    12
718     9
719    27
720     7
721     6
722     5
723     6
724     3
725    10
726     7
727    10
728     3
729     9
730     8
731     8
732    10
733     8
734     7
735    14
736     4
737     5
738    15
739    14
740     2
741     3
742     3
743     9
744    20
745     3
746     0
747     1
748     5
749     5
750     5
751     2
752     7
753     9
754    20
755    16
756    15
757    15
758     9
759     4
760     9
761     6
762     7
763    35
764    10
765     9
766    10
767    22
768     7
769     7
770    11
771     8
772     8
773    14
774     6
775    14
776     6
777     6
778    10
779     8
780     7
781     7
782     2
783     8
784     1
785    10
786    10
787    10
788     8
789    19
790     2
791    10
792    20
793     2
794     9
795    10
796     7
797     9
798    10
799    17
800     7
801     9
802     4
803    14
804     3
805     3
806     2
807     3
808     2
809    10
810     8
811    24
812     8
813    10
814    12
815     9
816    10
817     8
818    11
819     6
820    10
821    14
822     9
823     8
824    12
825     1
826    12
827    12
828     0
829     1
830    10
831     6
832    21
833    10
834    12
835    19
836     3
837    26
838     7
839     6
840     5
841     3
842    19
843     4
844     8
845    15
846     9
847    26
848     3
849    14
850     5
851     8
852     3
853     9
854     5
855     8
856     5
857     9
858     5
859    10
860    10
861     7
862     9
863     5
864    15
865    10
866    17
867     8
868     7
869    11
870     7
871     4
872    24
873     8
874     3
875    22
876     0
877     3
878    11
879     7
880     5
881    11
882    10
883     2
884     2
885     5
886     9
887     8
888     8
889     8
890     8
891    19
892     7
893    21
894     4
895    21
896     8
897     7
898    16
899     7
900     6
901     6
902     5
903     6
904     7
905     0
906    12
907     6
908    10
909    12
910     8
911    11
912     6
913     2
914    17
915    11
916    14
917    28
918     7
919    19
920    15
921     9
922    18
923    18
924    15
925     6
926    18
927    11
928    10
929     7
930     3
931    18
932     6
933     7
934     6
935    10
936     1
937     1
938    10
939     6
940     4
941     5
942     3
943     9
944     8
945     5
946    12
947    10
948     8
949     4
950    11
951     7
952    23
953     1
954     8
955    11
956     7
957     5
958     4
959    12
960     9
961    13
962     4
963    15
964    11
965     5
966     3
967     3
968     3
969     3
970     1
971    24
972     7
973    11
974    18
975     1
976     3
977     3
978    15
979     6
980     1
981    14
982    22
983    22
984    16
985     8
986     4
987    16
988    12
989    20
990    18
991     2
992     8
993     2
994    15
995     4
996     6
997    11
998     6
999     8
1000   14
1001   10
1002    7
1003    7
1004    4
1005    4
1006    7
1007    6
1008   16
1009    9
1010   10
1011    6
1012   10
1013   13
1014   10
1015   12
1016    9
1017   10
1018    4
1019    5
1020    0
1021    7
1022    4
1023   30
1024    2
1025    2
1026    4
1027   11
1028    9
1029    8
1030    5
1031    6
1032   10
1033    8
1034    5
1035    4
1036    5
1037    7
1038    6
1039    7
1040   19
1041    7
1042    5
1043    3
1044   12
1045   16
1046   18
1047    3
1048    8
1049   10
1050    2
1051    6
1052    8
1053    4
1054    0
1055    6
1056    2
1057    6
1058   15
1059    7
1060   16
1061    8
1062    8
1063   11
1064    9
1065    7
1066    0
1067    3
1068    2
1069    2
1070    2
1071    3
1072    2
1073    2
1074   10
1075    6
1076    6
1077    6
1078    3
1079   14
1080    8
1081    3
1082   15
1083    8
1084    9
1085   10
1086    4
1087    9
1088   12
1089    6
1090   11
1091   11
1092   11
1093    8
1094    7
1095    0
1096    0
1097   11
1098    4
1099    3
1100    3
1101   24
1102   20
1103    6
1104    8
1105   12
1106   15
1107    4
1108   11
1109    9
1110    0
1111    9
1112    5
1113    7
1114    4
1115    9
1116   18
1117    9
1118    7
1119    6
1120    1
1121   12
1122    2
1123   15
1124    7
1125    1
1126    6
1127    2
1128   15
1129    2
1130    7
1131    7
1132   12
1133    1
1134   12
1135   12
1136   12
1137   12
1138   12
1139   12
1140   12
1141   12
1142   12
1143   12
1144   15
1145    2
1146   11
1147   16
1148    6
1149    7
1150    8
1151    5
1152    2
1153    7
1154    1
1155   15
1156    0
1157   11
1158   14
1159   10
1160    4
1161    8
1162    9
1163    8
1164   11
1165    8
1166    1
1167    6
1168   15
1169   10
1170    8
1171    4
1172    9
1173    4
1174    5
1175    8
1176    2
1177    3
1178    2
1179    9
1180    6
1181   10
1182   21
1183    0
1184    5
1185   12
1186    6
1187   17
1188    1
1189   10
1190    8
1191    1
1192    1
1193    8
1194   10
1195   15
1196   15
1197    6
1198   11
1199   10
1200   16
1201   16
1202    2
1203    6
1204    7
1205    3
1206    2
1207    0
1208    2
1209    6
1210    5
1211    2
1212    4
1213    8
1214   20
1215    5
1216    8
1217    6
1218    8
1219    6
1220    5
1221   11
1222    8
1223    6
1224    0
1225   10
1226    2
1227    2
1228    5
1229    1
1230    9
1231   10
1232    5
1233    3
1234    5
1235    9
1236    8
1237   10
1238   15
1239    2
1240    2
1241    2
1242    2
1243    2
1244    2
1245    2
1246    9
1247    9
1248    9
1249    9
1250    9
1251    9
1252   15
1253   12
1254   15
1255   17
1256   20
1257   18
1258   12
1259   16
1260    9
1261    1
1262    3
1263   10
1264   11
1265    2
1266    8
1267    7
1268    7
1269    4
1270    7
1271    4
1272    8
1273    5
1274   15
1275   12
1276    4
1277    8
1278   23
1279   19
1280    5
1281    5
1282    5
1283    5
1284   15
1285   19
1286    6
1287    1
1288    4
1289    7
1290    6
1291    3
1292   20
1293    4
1294    6
1295    5
1296   10
1297    8
1298    9
1299   19
1300   12
1301   17
1302   21
1303    6
1304   10
1305    6
1306    6
1307   10
1308   12
1309    1
1310   13
1311   12
1312   13
1313   10
1314    4
1315    7
1316   13
1317   14
1318   12
1319    5
1320   15
1321   12
1322   12
1323   16
1324   10
1325   17
1326    4
1327   10
1328   16
1329    8
1330    6
1331    2
1332    9
1333   10
1334    9
1335    2
1336   10
1337    7
1338    7
1339   12
1340    4
1341   11
1342   14
1343    5
1344    7
1345   14
1346   10
1347    0
1348    8
1349    8
1350   11
1351    7
1352   13
1353    9
1354    1
1355    8
1356   11
1357   12
1358    4
1359   23
1360    5
1361    1
1362    7
1363   15
1364   10
1365   10
1366    6
1367   15
1368    8
1369    3
1370    5
1371    3
1372    2
1373    3
1374    8
1375    1
1376   10
1377    3
1378    7
1379    5
1380   17
1381    7
1382   13
1383    1
1384    2
1385   10
1386   15
1387   15
1388    8
1389   12
1390    7
1391    1
1392   10
1393   14
1394    8
1395    6
1396    9
1397    7
1398   17
1399    1
1400   12
1401    3
1402    3
1403    8
1404    8
1405    8
1406   19
1407    6
1408   21
1409    8
1410    3
1411   31
1412   15
1413    3
1414   13
1415   13
1416    8
1417    8
1418   18
1419    2
1420   25
1421   11
1422    7
1423    3
1424    6
1425    9
1426    5
1427    6
1428   11
1429    8
1430   14
1431    6
1432    8
1433    1
1434    5
1435   10
1436   12
1437    3
1438    1
1439    2
1440    1
1441    3
1442    1
1443    2
1444    8
1445    5
1446    4
1447    9
1448   12
1449    8
1450    3
1451    4
1452    4
1453    3
1454    2
1455   10
1456   15
1457   19
1458    4
1459    9
1460    4
1461   10
1462   12
1463    8
1464    5
1465    6
1466   13
1467   10
1468    5
1469    7
1470    1
1471   13
1472    4
1473    7
1474    7
1475    4
1476    0
1477   24
1478   14
1479    5
1480    6
1481    2
1482    7
1483    5
1484    5
1485   12
1486    6
1487   19
1488    6
1489    5
1490    7
1491    7
1492    7
1493   22
1494    7
1495    8
1496    0
1497    6
1498   11
1499   22
1500    6
1501   25
1502    7
1503    8
1504   10
1505    5
1506    9
1507    6
1508    3
1509    4
1510    6
1511    6
1512    2
1513   10
1514    7
1515    7
1516    0
1517    3
1518    4
1519    4
1520    2
1521    6
1522    7
1523    6
1524   10
1525    4
1526   11
1527    8
1528    7
1529    6
1530    2
1531    6
1532   10
1533    4
1534   15
1535   11
1536    0
1537    0
1538   14
1539   14
1540   14
1541   14
1542    5
1543    1
1544   13
1545   22
1546    6
1547   19
1548    2
1549    7
1550   12
1551   16
1552   17
1553   12
1554   27
1555    9
1556    6
1557   12
1558   15
1559    0
1560    9
1561    6
1562    5
1563    6
1564    2
1565   16
1566   10
1567   14
1568    3
1569   17
1570   18
1571   20
1572    6
1573    5
1574   39
1575    1
1576   18
1577    9
1578   27
1579    1
1580   15
1581    8
1582   12
1583    5
1584    5
1585    7
1586   10
1587    3
1588    2
1589    3
1590    5
1591    5
1592    4
1593    2
1594   15
1595    9
1596    2
1597    7
1598    9
1599   10
1600    5
1601    9
1602   12
1603    6
1604    6
1605    3
1606    6
1607    6
1608    5
1609    5
1610    6
1611    9
1612    3
1613    2
1614    4
1615    8
1616    5
1617    3
1618    5
1619    3
1620    4
1621    4
1622    4
1623    6
1624   12
1625    9
1626   10
1627   11
1628    2
1629   10
1630   15
1631    3
1632    9
1633    8
1634   10
1635    9
1636    5
1637    7
1638   16
1639    7
1640   12
1641   13
1642   11
1643    9
1644   12
1646   10
1647    4
1648    3
1649    5
1650   10
1651   14
1652   11
1653    3
1654    6
1655   18
1656    6
1657   15
1658    1
1659    9
1660   10
1661   12
1662   17
1663    9
1664   19
1665   14
1666   14
1667   12
1668   11
1669   12
1670   12
1671    9
1672   11
1673   12
1674   12
1675    4
1676    3
1677    1
1678    7
1679    1
1680    8
1681    3
1682    2
1683    9
1684    0
1685    7
1686    8
1687    7
1688    7
1689   12
1690    7
1691   14
1692    2
1693   14
1694   16
1695    8
1696   18
1697   14
1698    3
1699   12
1700    7
1701    7
1702   14
1703   12
1704    7
1705   10
1706    5
1707   24
1708   11
1709    0
1710    0
1711    0
1712   12
1713    0
1714   12
1715    0
1716    6
1717    5
1718   10
1719    3
1720    5
1721   16
1722   18
1723    1
1724   12
1725    0
1726    2
1727    0
1728    0
1729    0
1730    0
1731    0
1732    0
1733   14
1734    2
1735    8
1736    6
1737    3
1738    2
1739    2
1740   21
1741   13
1742   29
1743    7
1744   15
1745   11
1746   17
1747   11
1748   12
1749   12
1750   18
1751    4
1752    8
1753    5
1754    7
1755   15
1756   15
1757   16
1758   24
1759   16
1760   16
1761    6
1762   12
1763    0
1764    6
1765   14
1766   12
1767    1
1768   14
1769   12
1770    0
1771    0
1772    0
1773   12
1774   12
1775   12
1776   12
1777   12
1778   12
1779    1
1780    1
1781    7
1782   14
1783    8
1784   12
1785    1
1786    4
1787    5
1788    6
1789   20
1790   10
1791    6
1792    8
1793    8
1794   20
1795   11
1796    7
1797   10
1798    9
1799    7
1800    1
1801    1
1802    5
1803    8
1804    5
1805   10
1806   12
1807   10
1808   17
1809    9
1810    8
1811    1
1812    8
1813    5
1814    3
1815   12
1816    6
1817   15
1818    0
1819    9
1820    6
1821   25
1822    8
1823    8
1824   14
1825    0
1826    5
1827   10
1828   12
1829    3
1830   14
1831    7
1832    7
1833    3
1834    4
1835    5
1836    6
1837   14
1838   14
1839   12
1840   12
1841   10
1842    6
1843    5
1844   22
1845   12
1846   10
1847    4
1848   10
1849    6
1850    4
1851    6
1852    4
1853    8
1854    2
1855    4
1856    0
1857    3
1858    2
1859    3
1860    2
1861    3
1862    3
1863    8
1864   11
1865   15
1866   11
1867    4
1868    1
1869    8
1870    3
1871    5
1872   16
1873    9
1874    6
1875    8
1876    8
1877   15
1878    2
1879    0
1880    2
1881    1
1882   12
1883    5
1884    3
1885   11
1886    8
1887    5
1888   10
1889    3
1890    2
1891   10
1892    8
1893   11
1894    1
1895   10
1896   10
1897   15
1898   17
1899    9
1900    5
1901    7
1902   16
1903    8
1904    6
1905    9
1906    1
1907    4
1908    4
1909    2
1910   14
1911    2
1912    8
1913    9
1914   15
1915    7
1916   13
1917    0
1918    6
1919    2
1920   45
1921    0
1922    1
1923    9
1924    0
1925    6
1926    5
1927   10
1928    6
1929   10
1930    3
1931    2
1932    1
1933    4
1934    8
1935    0
1936    9
1937    4
1938    2
1939    6
1940    0
1941   14
1942    7
1943    9
1944    2
1945    3
1946    3
1947    4
1948   14
1949   12
1950    9
1951    8
1952   12
1953    8
1954    1
1955    4
1956   22
1957    3
1958    9
1959    0
1960   12
1961    9
1962    4
1963   19
1964   10
1965   10
1966    2
1967   15
1968    7
1969    8
1970   33
1971    9
1972    3
1974   12
1975   15
1976    2
1977    3
1978    0
1979    2
1980    9
1981    1
1982    8
1983   12
1984   12
1985    1
1986   12
1987    6
1988    1
1989    9
1990    9
1991    6
1992    5
1993   12
1994    8
1995    1
1996    6
1997   14
1998    4
1999    3
2000    3
2001    2
2002    3

In [112]:
temp[0].str.strip()

0         4
1         1
2        12
3         2
4         5
5         3
6         5
7        14
8         2
9        31
10        1
11        4
12        4
13        3
14       13
15       25
16        0
17        0
18       11
19       12
20        4
21       11
22        4
23        0
24       10
26        3
27       20
28        5
29        4
30        4
31        1
32       12
33        8
34       20
35        8
36       21
37        0
38        6
39        1
40        1
41       12
42        6
43        1
44        2
45        1
46        9
47        5
48       18
49       29
50        3
51        3
52        5
53        1
54        9
55        6
56        2
57       14
58        1
59        8
60        2
61       12
62        4
63        1
64        7
65        3
66        5
67        9
68       14
69       14
70       15
71        6
72        6
73        2
74        3
75        2
76        4
77        3
78        6
79        8
80        2
81        4
82        0
83       11
84        1
85       11
86       21
87        4
88        2
89        2
90        4
91       32
92        2
93        2
94        2
95       11
96       23
97        6
98        9
99        1
100       5
101      43
102       1
103       1
104       1
105      11
106      14
107       9
108       8
109       9
110       2
111       4
112      32
113      43
114       2
115       3
116       8
117       3
118      20
119       2
120       1
121       4
122       0
123       3
124       4
125       3
126       6
127      13
128      13
129      16
130       3
131       0
132      11
133       2
134      12
135       2
136       1
137       4
138      11
139       5
140       1
141      12
142      16
143       6
144       2
145       3
146      11
147      10
148       2
149       4
150      19
151       1
152       8
153      18
154      10
155       7
156       2
157      10
158       5
159      10
160      20
161      20
162       3
163      13
164       3
165       7
166       4
167       4
168       2
169       2
170       4
171       3
172       1
173       2
174      11
175      11
176      16
177       8
178       1
179      18
180       8
181     NaN
182       2
183      17
184      23
185      10
186      30
187       4
188       2
189       0
190       0
191       1
192       1
193      11
194      11
195       0
196      19
197      28
198       4
199       9
200       7
201       1
202      15
203       2
204       0
205       9
206       1
207       1
208       4
209       4
210       3
211       1
212       1
213     NaN
214      13
215       4
216       6
217      20
218      27
219       6
220      33
221      35
222      26
223       0
224       2
225       4
226      10
227      11
228      10
229       0
230       3
231       7
232       8
233       2
234       3
235       1
236       9
237      14
238       4
239       8
240      10
241       3
242       3
243       2
244       3
245       7
246       2
247       3
248       8
249      12
250       8
251       1
252       1
253      26
254      21
255       8
256       2
257       1
258       2
259      39
260       1
261       8
262       2
263       3
264       7
265       4
266      22
267      14
268      11
269      17
270       3
271      12
272       8
273       3
274      14
275       7
276       9
277       2
278       3
279       6
280      16
281      12
282       1
283       4
284      17
285       7
287      11
288       4
289       1
290       6
291       1
292      17
293       1
294      16
295      19
296      31
297      14
298       5
299       2
300       1
301       1
302      15
303       1
304       1
305       2
306      11
307       9
308      33
309      14
310       4
311       5
312      18
313       1
314      20
315       9
316      18
317       8
318       4
319       9
320       4
321       1
322       6
323       1
324      19
325      31
326       5
327       1
328       1
329      15
330       1
331       1
332       2
333      11
334       9
335      14
336       5
337       1
338       9
339      18
340       4
341       1
342      20
343      24
344       2
345       4
346      14
347       9
348      14
349       4
350      26
351       2
352      14
353      17
354       2
355      25
356       9
357       4
358       6
359       5
360       4
361      14
362      15
363       7
364       2
365      16
366      24
367      10
368       2
369       2
370       2
371       1
372       8
373      12
374      18
375       1
376       2
377       3
378      11
379       7
380       5
381       6
382      19
383      25
384      10
385      10
386       3
387       8
388       5
389       4
390       1
391      10
392      16
393      10
394       3
395      17
396       9
397      11
398      19
399       0
400       0
401       8
402       4
403      30
404      16
405      18
406       2
407       7
408       2
409      10
410       9
411       6
412      14
413      25
414       7
415       4
416       7
417      18
418      12
419       3
420      21
421      14
422       5
423       3
424      19
425      10
426       5
427      10
428       7
429      11
430       2
431       2
432       7
433       6
434      11
435       9
436       4
437      14
438       5
439       1
440      16
441       1
442      18
443       6
444       8
445       4
446       7
447       9
448       3
449      11
450      17
451       7
452       5
453      16
454       2
455       8
456       2
457       3
458       6
459       0
460       2
461      15
462      10
463      11
464      10
465       4
466       3
467       9
468       8
469       7
470       5
471       7
472       7
473       9
474       2
475       5
476      11
477       8
478       7
479      20
480      10
481       7
482      10
483      16
484       8
485       1
486      18
487      15
488      25
489       5
490       9
491       5
492       7
493       7
494       7
495      12
496       5
497       4
498       6
499       3
500      10
501      15
502      15
503      10
504       9
505      10
506      10
507       9
508       0
509       1
510      11
511      17
512       1
513       0
514       7
515       5
516      12
517      14
518      14
519       9
520      19
521       8
522      14
523       8
524       2
525       9
526       5
527       0
528       6
529      10
530       6
531       8
532       9
533       9
534      12
535      11
536       6
537      15
538       7
539       8
540       8
541       3
542      10
543       1
544       4
545       5
546       2
547      20
548      13
549       8
550       8
551      16
552      12
553      10
554       6
555      16
556       8
557      12
558      12
559       5
560       9
561       7
562       7
563       7
564       5
565       8
566       7
567       5
568       9
569      11
570      10
571       6
572       3
573      22
574       5
575      15
576       5
577       0
578       6
579       1
580       2
581      12
582      12
583       6
584       8
585       4
586       5
587       2
588      20
589      12
590      18
591       2
592       3
593       3
594      18
595       7
596      17
597       8
598       2
599       8
600       9
601       3
602      12
603      10
604       2
605       0
606       7
607       2
608       5
609       3
610       3
611      12
612       6
613      28
614      10
615      24
616       4
617       0
618      17
619      12
620      19
621      15
622      10
623       3
624       9
625      15
626      19
627       6
628      21
629      14
630      20
631       7
632       2
633       5
634      14
635      16
636      12
637       3
638       7
639      10
640      11
641      17
642       8
643       6
644      10
645      11
646       4
647      15
648      19
649       5
650      14
651       6
652      17
653       7
654       7
655      12
656      10
657      38
658       8
659      18
660       9
661      19
662       3
663       9
664       7
665      14
666       1
667       0
668       5
669       0
670      10
671       8
672       0
673      10
674      23
675       7
676       6
677       7
678      18
679       5
680      17
681       3
682       7
683       4
684       1
685       6
686      10
687       6
688       0
689       8
690       5
691      14
692      15
693       7
694      10
695      10
696       8
697      11
698       3
699      12
700       5
701       8
702       4
703      10
704      12
705      17
706       2
707       9
708       1
709      10
710       7
711      11
712      11
713      11
714      15
715       8
716       8
717      12
718       9
719      27
720       7
721       6
722       5
723       6
724       3
725      10
726       7
727      10
728       3
729       9
730       8
731       8
732      10
733       8
734       7
735      14
736       4
737       5
738      15
739      14
740       2
741       3
742       3
743       9
744      20
745       3
746       0
747       1
748       5
749       5
750       5
751       2
752       7
753       9
754      20
755      16
756      15
757      15
758       9
759       4
760       9
761       6
762       7
763      35
764      10
765       9
766      10
767      22
768       7
769       7
770      11
771       8
772       8
773      14
774       6
775      14
776       6
777       6
778      10
779       8
780       7
781       7
782       2
783       8
784       1
785      10
786      10
787      10
788       8
789      19
790       2
791      10
792      20
793       2
794       9
795      10
796       7
797       9
798      10
799      17
800       7
801       9
802       4
803      14
804       3
805       3
806       2
807       3
808       2
809      10
810       8
811      24
812       8
813      10
814      12
815       9
816      10
817       8
818      11
819       6
820      10
821      14
822       9
823       8
824      12
825       1
826      12
827      12
828       0
829       1
830      10
831       6
832      21
833      10
834      12
835      19
836       3
837      26
838       7
839       6
840       5
841       3
842      19
843       4
844       8
845      15
846       9
847      26
848       3
849      14
850       5
851       8
852       3
853       9
854       5
855       8
856       5
857       9
858       5
859      10
860      10
861       7
862       9
863       5
864      15
865      10
866      17
867       8
868       7
869      11
870       7
871       4
872      24
873       8
874       3
875      22
876       0
877       3
878      11
879       7
880       5
881      11
882      10
883       2
884       2
885       5
886       9
887       8
888       8
889       8
890       8
891      19
892       7
893      21
894       4
895      21
896       8
897       7
898      16
899       7
900       6
901       6
902       5
903       6
904       7
905       0
906      12
907       6
908      10
909      12
910       8
911      11
912       6
913       2
914      17
915      11
916      14
917      28
918       7
919      19
920      15
921       9
922      18
923      18
924      15
925       6
926      18
927      11
928      10
929       7
930       3
931      18
932       6
933       7
934       6
935      10
936       1
937       1
938      10
939       6
940       4
941       5
942       3
943       9
944       8
945       5
946      12
947      10
948       8
949       4
950      11
951       7
952      23
953       1
954       8
955      11
956       7
957       5
958       4
959      12
960       9
961      13
962       4
963      15
964      11
965       5
966       3
967       3
968       3
969       3
970       1
971      24
972       7
973      11
974      18
975       1
976       3
977       3
978      15
979       6
980       1
981      14
982      22
983      22
984      16
985       8
986       4
987      16
988      12
989      20
990      18
991       2
992       8
993       2
994      15
995       4
996       6
997      11
998       6
999       8
1000     14
1001     10
1002      7
1003      7
1004      4
1005      4
1006      7
1007      6
1008     16
1009      9
1010     10
1011      6
1012     10
1013     13
1014     10
1015     12
1016      9
1017     10
1018      4
1019      5
1020      0
1021      7
1022      4
1023     30
1024      2
1025      2
1026      4
1027     11
1028      9
1029      8
1030      5
1031      6
1032     10
1033      8
1034      5
1035      4
1036      5
1037      7
1038      6
1039      7
1040     19
1041      7
1042      5
1043      3
1044     12
1045     16
1046     18
1047      3
1048      8
1049     10
1050      2
1051      6
1052      8
1053      4
1054      0
1055      6
1056      2
1057      6
1058     15
1059      7
1060     16
1061      8
1062      8
1063     11
1064      9
1065      7
1066      0
1067      3
1068      2
1069      2
1070      2
1071      3
1072      2
1073      2
1074     10
1075      6
1076      6
1077      6
1078      3
1079     14
1080      8
1081      3
1082     15
1083      8
1084      9
1085     10
1086      4
1087      9
1088     12
1089      6
1090     11
1091     11
1092     11
1093      8
1094      7
1095      0
1096      0
1097     11
1098      4
1099      3
1100      3
1101     24
1102     20
1103      6
1104      8
1105     12
1106     15
1107      4
1108     11
1109      9
1110      0
1111      9
1112      5
1113      7
1114      4
1115      9
1116     18
1117      9
1118      7
1119      6
1120      1
1121     12
1122      2
1123     15
1124      7
1125      1
1126      6
1127      2
1128     15
1129      2
1130      7
1131      7
1132     12
1133      1
1134     12
1135     12
1136     12
1137     12
1138     12
1139     12
1140     12
1141     12
1142     12
1143     12
1144     15
1145      2
1146     11
1147     16
1148      6
1149      7
1150      8
1151      5
1152      2
1153      7
1154      1
1155     15
1156      0
1157     11
1158     14
1159     10
1160      4
1161      8
1162      9
1163      8
1164     11
1165      8
1166      1
1167      6
1168     15
1169     10
1170      8
1171      4
1172      9
1173      4
1174      5
1175      8
1176      2
1177      3
1178      2
1179      9
1180      6
1181     10
1182     21
1183      0
1184      5
1185     12
1186      6
1187     17
1188      1
1189     10
1190      8
1191      1
1192      1
1193      8
1194     10
1195     15
1196     15
1197      6
1198     11
1199     10
1200     16
1201     16
1202      2
1203      6
1204      7
1205      3
1206      2
1207      0
1208      2
1209      6
1210      5
1211      2
1212      4
1213      8
1214     20
1215      5
1216      8
1217      6
1218      8
1219      6
1220      5
1221     11
1222      8
1223      6
1224      0
1225     10
1226      2
1227      2
1228      5
1229      1
1230      9
1231     10
1232      5
1233      3
1234      5
1235      9
1236      8
1237     10
1238     15
1239      2
1240      2
1241      2
1242      2
1243      2
1244      2
1245      2
1246      9
1247      9
1248      9
1249      9
1250      9
1251      9
1252     15
1253     12
1254     15
1255     17
1256     20
1257     18
1258     12
1259     16
1260      9
1261      1
1262      3
1263     10
1264     11
1265      2
1266      8
1267      7
1268      7
1269      4
1270      7
1271      4
1272      8
1273      5
1274     15
1275     12
1276      4
1277      8
1278     23
1279     19
1280      5
1281      5
1282      5
1283      5
1284     15
1285     19
1286      6
1287      1
1288      4
1289      7
1290      6
1291      3
1292     20
1293      4
1294      6
1295      5
1296     10
1297      8
1298      9
1299     19
1300     12
1301     17
1302     21
1303      6
1304     10
1305      6
1306      6
1307     10
1308     12
1309      1
1310     13
1311     12
1312     13
1313     10
1314      4
1315      7
1316     13
1317     14
1318     12
1319      5
1320     15
1321     12
1322     12
1323     16
1324     10
1325     17
1326      4
1327     10
1328     16
1329      8
1330      6
1331      2
1332      9
1333     10
1334      9
1335      2
1336     10
1337      7
1338      7
1339     12
1340      4
1341     11
1342     14
1343      5
1344      7
1345     14
1346     10
1347      0
1348      8
1349      8
1350     11
1351      7
1352     13
1353      9
1354      1
1355      8
1356     11
1357     12
1358      4
1359     23
1360      5
1361      1
1362      7
1363     15
1364     10
1365     10
1366      6
1367     15
1368      8
1369      3
1370      5
1371      3
1372      2
1373      3
1374      8
1375      1
1376     10
1377      3
1378      7
1379      5
1380     17
1381      7
1382     13
1383      1
1384      2
1385     10
1386     15
1387     15
1388      8
1389     12
1390      7
1391      1
1392     10
1393     14
1394      8
1395      6
1396      9
1397      7
1398     17
1399      1
1400     12
1401      3
1402      3
1403      8
1404      8
1405      8
1406     19
1407      6
1408     21
1409      8
1410      3
1411     31
1412     15
1413      3
1414     13
1415     13
1416      8
1417      8
1418     18
1419      2
1420     25
1421     11
1422      7
1423      3
1424      6
1425      9
1426      5
1427      6
1428     11
1429      8
1430     14
1431      6
1432      8
1433      1
1434      5
1435     10
1436     12
1437      3
1438      1
1439      2
1440      1
1441      3
1442      1
1443      2
1444      8
1445      5
1446      4
1447      9
1448     12
1449      8
1450      3
1451      4
1452      4
1453      3
1454      2
1455     10
1456     15
1457     19
1458      4
1459      9
1460      4
1461     10
1462     12
1463      8
1464      5
1465      6
1466     13
1467     10
1468      5
1469      7
1470      1
1471     13
1472      4
1473      7
1474      7
1475      4
1476      0
1477     24
1478     14
1479      5
1480      6
1481      2
1482      7
1483      5
1484      5
1485     12
1486      6
1487     19
1488      6
1489      5
1490      7
1491      7
1492      7
1493     22
1494      7
1495      8
1496      0
1497      6
1498     11
1499     22
1500      6
1501     25
1502      7
1503      8
1504     10
1505      5
1506      9
1507      6
1508      3
1509      4
1510      6
1511      6
1512      2
1513     10
1514      7
1515      7
1516      0
1517      3
1518      4
1519      4
1520      2
1521      6
1522      7
1523      6
1524     10
1525      4
1526     11
1527      8
1528      7
1529      6
1530      2
1531      6
1532     10
1533      4
1534     15
1535     11
1536      0
1537      0
1538     14
1539     14
1540     14
1541     14
1542      5
1543      1
1544     13
1545     22
1546      6
1547     19
1548      2
1549      7
1550     12
1551     16
1552     17
1553     12
1554     27
1555      9
1556      6
1557     12
1558     15
1559      0
1560      9
1561      6
1562      5
1563      6
1564      2
1565     16
1566     10
1567     14
1568      3
1569     17
1570     18
1571     20
1572      6
1573      5
1574     39
1575      1
1576     18
1577      9
1578     27
1579      1
1580     15
1581      8
1582     12
1583      5
1584      5
1585      7
1586     10
1587      3
1588      2
1589      3
1590      5
1591      5
1592      4
1593      2
1594     15
1595      9
1596      2
1597      7
1598      9
1599     10
1600      5
1601      9
1602     12
1603      6
1604      6
1605      3
1606      6
1607      6
1608      5
1609      5
1610      6
1611      9
1612      3
1613      2
1614      4
1615      8
1616      5
1617      3
1618      5
1619      3
1620      4
1621      4
1622      4
1623      6
1624     12
1625      9
1626     10
1627     11
1628      2
1629     10
1630     15
1631      3
1632      9
1633      8
1634     10
1635      9
1636      5
1637      7
1638     16
1639      7
1640     12
1641     13
1642     11
1643      9
1644     12
1646     10
1647      4
1648      3
1649      5
1650     10
1651     14
1652     11
1653      3
1654      6
1655     18
1656      6
1657     15
1658      1
1659      9
1660     10
1661     12
1662     17
1663      9
1664     19
1665     14
1666     14
1667     12
1668     11

In [113]:
df['floorNum'] = temp[0].str.strip()

In [117]:
df.sample(3)

,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
873,3 BHK Flat in Sector 63 Gurgaon,dhoot time residency,2.20,12813.0,Super Built up area 1717(159.51 sq.m.),3,4,3+,study room,"Sector 63 Gurgaon, Gurgaon, Haryana",8,North-West,5 to 10 Year Old,"['Metro Station', 'High end group housing', 'N...","Dhoot time residency in sector 63, gurgaon is ...","['2 Wardrobe', '6 Fan', '1 Exhaust Fan', '4 Ge...","['Power Back-up', 'Lift(s)', 'High Ceiling Hei...","['Green Area4 out of 5', 'Construction4 out of..."
2693,3 BHK Flat in Mehrauli Gurgaon Road,essel towers,2.20,12500.0,Carpet area: 1760 (163.51 sq.m.),3,4,3+,not available,"Mehrauli Gurgaon Road, Mehrauli Gurgaon Road, ...",3,NaN,undefined,"['Mg road metro station', 'Iffco chowk metro s...",Best in class property available at mehrauli g...,"['1 Wardrobe', '1 Fan', '1 Light', 'No AC', 'N...",NaN,"['Environment4 out of 5', 'Safety3 out of 5', ..."
866,3 BHK Flat in Sector 102 Gurgaon,emaar imperial gardens,1.91,9550.0,Super Built up area 2000(185.81 sq.m.)Carpet a...,3,4,2,"servant room,study room","T-4/1704, Sector 102 Gurgaon, Gurgaon, Haryana",17,East,1 to 5 Year Old,"['Satya The Hive Mall', 'Gurugram Road', 'Dwar...",This 3 bhk flat is located in emaar imperial g...,"['5 Fan', '1 Exhaust Fan', '10 Light', '1 Chim...","['Centrally Air Conditioned', 'Security / Fire...","['Green Area5 out of 5', 'Construction4 out of..."

In [118]:
# facing
df['facing'].value_counts()

facing
North-East    505
East          490
North         301
South         203
West          182
North-West    162
South-East    144
South-West    135
Name: count, dtype: int64

In [119]:
df['facing'].isnull().sum()

872

In [120]:
df['facing'].fillna('NA',inplace = True)

In [121]:
df['facing'].value_counts()

facing
NA            872
North-East    505
East          490
North         301
South         203
West          182
North-West    162
South-East    144
South-West    135
Name: count, dtype: int64

In [122]:
# small feature engg total area calculate
df.insert(loc=4,column='area',value=round((df['price']*10000000)/df['price_per_sqft']))

In [123]:
# type define for this dataset 'flat' because planning to merge with another dataset houses
df.insert(loc=1,column='property_type',value='flat')

In [124]:
# remaining col. are little bit complex so on hold
df.head()

,property_name,property_type,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Krishna Colony,flat,maa bhagwati residency,0.45,5000.0,900.0,Carpet area: 900 (83.61 sq.m.),2,2,1,not available,"Krishna Colony, Gurgaon, Haryana",4,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ..."
1,2 BHK Flat in Ashok Vihar,flat,apna enclave,0.50,7692.0,650.0,Carpet area: 650 (60.39 sq.m.),2,2,1,not available,"46b, Ashok Vihar, Gurgaon, Haryana",1,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ..."
2,2 BHK Flat in Sohna,flat,tulsiani easy in homes,0.40,6722.0,595.0,Carpet area: 595 (55.28 sq.m.),2,2,3,not available,"Sohna, Gurgaon, Haryana",12,NA,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment4 out of 5', 'Safety4 out of 5', ..."
3,2 BHK Flat in Sector 61 Gurgaon,flat,smart world orchard,1.47,12250.0,1200.0,Carpet area: 1200 (111.48 sq.m.),2,2,2,study room,"Sector 61 Gurgaon, Gurgaon, Haryana",2,NA,Dec 2023,"['Sector 55-56 Metro station', 'Bestech Centra...",Near to metro station of sector 56 and opposit...,NaN,"['Security / Fire Alarm', 'Private Garden / Te...",NaN
4,2 BHK Flat in Sector 92 Gurgaon,flat,parkwood westend,0.70,5204.0,1345.0,Super Built up area 1345(124.95 sq.m.),2,2,3,study room,"Sector 92 Gurgaon, Gurgaon, Haryana",5,NA,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",We are the proud owners of this 2 bhk alongwit...,[],NaN,"['Environment5 out of 5', 'Safety3 out of 5', ..."

In [125]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2994 entries, 0 to 3027
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   property_name    2994 non-null   object
 1   property_type    2994 non-null   object
 2   society          2994 non-null   object
 3   price            2993 non-null   float64
 4   price_per_sqft   2993 non-null   float64
 5   area             2993 non-null   float64
 6   areaWithType     2994 non-null   object
 7   bedRoom          2994 non-null   int32
 8   bathroom         2994 non-null   int32
 9   balcony          2994 non-null   object
 10  additionalRoom   2994 non-null   object
 11  address          2988 non-null   object
 12  floorNum         2989 non-null   object
 13  facing           2994 non-null   object
 14  agePossession    2993 non-null   object
 15  nearbyLocations  2903 non-null   object
 16  description      2994 non-null   object
 17  furnishDetails   2198 non-null   object
 18  features         2589 non-null   object
 19  rating           2665 non-null   object
dtypes: float64(3), int32(2), object(15)
memory usage: 467.8+ KB

In [126]:
df.shape

(2994, 20)

In [127]:
df.to_csv('flats_cleaned.csv',index=False)