In [1]:
import numpy as np
import pandas as pd
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
df = pd.read_csv('gurgaon_properties.csv')
df.sample(5)

,property_name,property_type,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
2786,3 BHK Flat in Sector 79 Gurgaon,flat,godrej,2.00,8453.0,2366.0,Carpet area: 2366 (219.81 sq.m.),3,4,3+,servant room,"Sector 79 Gurgaon, Gurgaon, Haryana",2.0,North-East,1 to 5 Year Old,"['Vatika Town Square-INXT', 'Naurangpur Road',...","Made with personal taste. Hitachi ac, faber ch...","['1 Water Purifier', '5 Fan', '1 Exhaust Fan',...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Green Area5 out of 5', 'Construction5 out of..."
409,3 BHK Flat in Sector 50 Gurgaon,flat,eros wembley estate,1.40,10174.0,1376.0,Super Built up area 1376(127.83 sq.m.),3,3,2,store room,"Tower F, Sector 50 Gurgaon, Gurgaon, Haryana",9.0,East,1 to 5 Year Old,"['Sri Radhe Krishna Temple', 'Standard charter...",Eros wembley estate is one of gurgaon's most s...,"['2 Wardrobe', '1 Water Purifier', '5 Fan', '1...","['Security / Fire Alarm', 'Power Back-up', 'Fe...","['Green Area5 out of 5', 'Construction4 out of..."
2197,3 BHK Flat in Sector 85 Gurgaon,flat,orris carnation residency,0.88,5952.0,1478.0,Super Built up area 1485(137.96 sq.m.),3,3,1,not available,"Sector 85 Gurgaon, Gurgaon, Haryana",1.0,South,1 to 5 Year Old,"['Omaxe Celebration Mall within reach', 'Nearb...",Azzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz,NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Green Area4 out of 5', 'Construction4 out of..."
3008,6 Bedroom House for sale in Uppals Southend,house,uppal southend,3.75,25562.0,1467.0,Plot area 163(136.29 sq.m.),6,6,3,others,"Uppals Southend, Gurgaon, Haryana",3.0,East,5 to 10 Year Old,"['Sri Radhe Krishna Temple', 'Icici bank ATM',...",Address...Uppal southend sector 49 w blook \n6...,NaN,"['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
1440,3 BHK Flat in Sector 84 Gurgaon,flat,antriksh heights,0.84,4869.0,1725.0,Super Built up area 1725(160.26 sq.m.),3,3,3+,pooja room,"Antriksh Heights, Sector 84 Gurgaon, Gurgaon, ...",8.0,NaN,0 to 1 Year Old,"['Old Bengali Market', 'MatriKiran High School...",Keys in hand wood work done park facing unit f...,NaN,"['Power Back-up', 'Lift(s)', 'High Ceiling Hei...","['Green Area4.5 out of 5', 'Construction3.5 ou..."

In [2]:
df.shape

(3953, 20)

In [3]:
df.duplicated().sum()

0

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3953 entries, 0 to 3952
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   property_name    3953 non-null   object
 1   property_type    3953 non-null   object
 2   society          3952 non-null   object
 3   price            3933 non-null   float64
 4   price_per_sqft   3933 non-null   float64
 5   area             3933 non-null   float64
 6   areaWithType     3953 non-null   object
 7   bedRoom          3953 non-null   int64
 8   bathroom         3953 non-null   int64
 9   balcony          3953 non-null   object
 10  additionalRoom   3953 non-null   object
 11  address          3943 non-null   object
 12  floorNum         3929 non-null   float64
 13  facing           2783 non-null   object
 14  agePossession    3952 non-null   object
 15  nearbyLocations  3750 non-null   object
 16  description      3953 non-null   object
 17  furnishDetails   2927 non-null   object
 18  features         3251 non-null   object
 19  rating           3503 non-null   object
dtypes: float64(4), int64(2), object(14)
memory usage: 617.8+ KB

In [5]:
df.isnull().sum()

property_name         0
property_type         0
society               1
price                20
price_per_sqft       20
area                 20
areaWithType          0
bedRoom               0
bathroom              0
balcony               0
additionalRoom        0
address              10
floorNum             24
facing             1170
agePossession         1
nearbyLocations     203
description           0
furnishDetails     1026
features            702
rating              450
dtype: int64

In [6]:
df.head()

,property_name,property_type,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,4 Bedroom House for sale in DLF Phase 4,house,independent,4.50,125000.0,360.0,Built Up area: 360 (33.45 sq.m.),4,4,0,not available,"Dlf City Phase 4, Sector 28, DLF Phase 4, Gurg...",4.0,NaN,undefined,NaN,Best in class property available at dlf city p...,"['1 Light', 'No AC', 'No Bed', 'No Chimney', '...",NaN,"['Environment5 out of 5', 'Lifestyle4 out of 5..."
1,3 BHK Flat in Sector 66 Gurgaon,flat,emaar mgf the palm drive,2.80,14358.0,1950.0,Super Built up area 1950(181.16 sq.m.)Built Up...,3,3,2,"servant room,study room,pooja room","Sector 66 Gurgaon, Gurgaon, Haryana",12.0,East,0 to 1 Year Old,"['Sector 55-56 Rapid Metro Station', 'HUB 66',...",Emaar palm drive apartment available for sale ...,"['6 Fan', '1 Fridge', '1 Exhaust Fan', '1 Dini...","['Security / Fire Alarm', 'Power Back-up', 'In...","['Green Area5 out of 5', 'Construction4.5 out ..."
2,3 BHK Flat in Sector 104 Gurgaon,flat,hero homes,1.90,11249.0,1689.0,Super Built up area 1689(156.91 sq.m.)Carpet a...,3,3,3,pooja room,"Sector 104 Gurgaon, Gurgaon, Haryana",16.0,NaN,Mar 2025,"['Basai Metro Station', 'HUDA Market', 'Dwarka...",Property located bang on dwarka expressway,"['1 Water Purifier', '1 Exhaust Fan', '3 Geyse...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Environment4 out of 5', 'Lifestyle4 out of 5..."
3,5 Bedroom House for sale in Nirvana Country,house,independent,10.56,32593.0,3240.0,Plot area 360(301.01 sq.m.),5,5,3,servant room,"Nirvana Country, Gurgaon, Haryana",3.0,NaN,5 to 10 Year Old,"['Radhakrishna Shani Mandir', 'Standard charte...",Urgent for sale\nOn main wide road\nConfirm de...,NaN,"['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
4,2 BHK Flat in Shanti Nagar,flat,ganga apartment,0.55,3352.0,1641.0,Super Built up area 1700(157.94 sq.m.)Built Up...,2,2,1,not available,"Shanti Nagar, Gurgaon, Haryana",3.0,North-East,5 to 10 Year Old,"['Rajiv Chowk Mosque', 'Hanuman Mandir', 'Stat...","Cash payment can be accepted\nPrime location ,...","['4 Fan', '1 Exhaust Fan', '1 Dining Table', '...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Safety4 out of 5', 'Lifestyle4 out of 5', 'E..."

In [7]:
# now we will use property name col. to extract new col. sector which may be important for us for our other purppose
df.insert(loc=3,column='sector', value = df['property_name'].str.split('in').str.get(1).str.replace('Gurgaon','').str.strip())

In [8]:
df.head(2)

,property_name,property_type,society,sector,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,4 Bedroom House for sale in DLF Phase 4,house,independent,DLF Phase 4,4.5,125000.0,360.0,Built Up area: 360 (33.45 sq.m.),4,4,0,not available,"Dlf City Phase 4, Sector 28, DLF Phase 4, Gurg...",4.0,NaN,undefined,NaN,Best in class property available at dlf city p...,"['1 Light', 'No AC', 'No Bed', 'No Chimney', '...",NaN,"['Environment5 out of 5', 'Lifestyle4 out of 5..."
1,3 BHK Flat in Sector 66 Gurgaon,flat,emaar mgf the palm drive,Sector 66,2.8,14358.0,1950.0,Super Built up area 1950(181.16 sq.m.)Built Up...,3,3,2,"servant room,study room,pooja room","Sector 66 Gurgaon, Gurgaon, Haryana",12.0,East,0 to 1 Year Old,"['Sector 55-56 Rapid Metro Station', 'HUB 66',...",Emaar palm drive apartment available for sale ...,"['6 Fan', '1 Fridge', '1 Exhaust Fan', '1 Dini...","['Security / Fire Alarm', 'Power Back-up', 'In...","['Green Area5 out of 5', 'Construction4.5 out ..."

In [9]:
df['sector'] = df['sector'].str.lower()

In [10]:
df.head(3)

,property_name,property_type,society,sector,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,4 Bedroom House for sale in DLF Phase 4,house,independent,dlf phase 4,4.5,125000.0,360.0,Built Up area: 360 (33.45 sq.m.),4,4,0,not available,"Dlf City Phase 4, Sector 28, DLF Phase 4, Gurg...",4.0,NaN,undefined,NaN,Best in class property available at dlf city p...,"['1 Light', 'No AC', 'No Bed', 'No Chimney', '...",NaN,"['Environment5 out of 5', 'Lifestyle4 out of 5..."
1,3 BHK Flat in Sector 66 Gurgaon,flat,emaar mgf the palm drive,sector 66,2.8,14358.0,1950.0,Super Built up area 1950(181.16 sq.m.)Built Up...,3,3,2,"servant room,study room,pooja room","Sector 66 Gurgaon, Gurgaon, Haryana",12.0,East,0 to 1 Year Old,"['Sector 55-56 Rapid Metro Station', 'HUB 66',...",Emaar palm drive apartment available for sale ...,"['6 Fan', '1 Fridge', '1 Exhaust Fan', '1 Dini...","['Security / Fire Alarm', 'Power Back-up', 'In...","['Green Area5 out of 5', 'Construction4.5 out ..."
2,3 BHK Flat in Sector 104 Gurgaon,flat,hero homes,sector 104,1.9,11249.0,1689.0,Super Built up area 1689(156.91 sq.m.)Carpet a...,3,3,3,pooja room,"Sector 104 Gurgaon, Gurgaon, Haryana",16.0,NaN,Mar 2025,"['Basai Metro Station', 'HUDA Market', 'Dwarka...",Property located bang on dwarka expressway,"['1 Water Purifier', '1 Exhaust Fan', '3 Geyse...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Environment4 out of 5', 'Lifestyle4 out of 5..."

In [11]:
df['sector'].value_counts()

sector
sohna                                                        163
sector 102                                                   113
sector 85                                                    110
sector 92                                                    104
sector 69                                                     94
sector 65                                                     90
sector 90                                                     90
sector 81                                                     90
sector 109                                                    88
sector 79                                                     80
sector 83                                                     69
sector 37d                                                    68
sector 86                                                     67
sector 104                                                    66
sector 107                                                    60
sector 108                                                    59
sector 95                                                     57
sector 56                                                     57
sector 89                                                     56
sector 48                                                     56
sector 70a                                                    54
sector 70                                                     53
nirvana country                                               53
sector 37c                                                    52
sector 84                                                     51
sector-33 sohna                                               51
palam vihar                                                   50
sector 67                                                     48
sector 66                                                     46
sector 103                                                    45
sector 113                                                    43
dlf phase 1                                                   43
sector 61                                                     42
sector 82                                                     42
dlf phase 2                                                   42
sector 106                                                    38
sector 49                                                     36
sector 99a                                                    32
sushant lok phase 1                                           31
sector 68                                                     30
sector 72                                                     29
sector 77                                                     29
sector 54                                                     27
sector 71                                                     27
laxman vihar                                                  27
dlf phase 4                                                   25
sector 112                                                    24
sector 33                                                     23
sector 88a                                                    23
sector 67a                                                    22
sector 111                                                    22
dlf phase 3                                                   22
sector 82a                                                    20
sector 22                                                     20
sector 78                                                     19
sector 63a                                                    18
sector 74                                                     18
sector 91                                                     17
sector 62                                                     17
sector 110                                                    16
sushant lok phase 3                                           16
sector 99                                                     16
sector 60                                                     15
sector 63                                                     15
sector 14                                                     15
sector 1 imt manesar                                          14
sector 52                                                     14
gwal pahari                                                   14
sector 76                                                     14
sector 53                                                     14
sector 3                                                      14
rajendra park                                                 14
dlf phase 5                                                   14
laxman vihar phase 2                                          13
sector 46                                                     13
sector 36a                                                    13
sector 39                                                     12
sector 93                                                     12
sector 31                                                     12
sohna road                                                    12
sector 38                                                     12
uppals southend                                               12
sector 50                                                     12
ashok vihar phase 3 extension                                 11
sector 47                                                     11
sector 1a imt manesar                                         10
sector 9a                                                     10
sector 7                                                      10
sector 55                                                      9
ashok vihar phase 2                                            9
sector 95a                                                     9
south city 1                                                   9
sector 4                                                       9
sector 40                                                      8
sector 10a                                                     8
malibu town                                                    8
mehrauli  road                                                 8
palam vihar extension                                          8
sector 57                                                      8
dwarka expressway                                              8
c block sushant lok phase 1                                    8
sector 89 a                                                    8
sector 59                                                      8
sector 43                                                      8
sector 51                                                      7
sector 58                                                      7
sector 26                                                      7
sector 11                                                      7
new colony                                                     7
mianwali colony                                                7
sector 36 sohna                                                7
surat nagar 1                                                  7
ashok vihar                                                    6
rajiv nagar                                                    6
sector 1                                                       6
jacobpura                                                      6
sector 5                                                       6
jyoti park                                                     6
sector 28                                                      5
sector 80                                                      5
saraswati vihar                                                5
chakkarpur                                                     5
sector 30                                                      5
sector 9                                                       5
sector 2                                                       5
sushant lok phase 2                                            5
manesar                                                        5
subhash nagar                                                  5
dayanand colony                                                5
sector 23a                                                     5
ansal plaza                                                    5
new palam vihar                                                5
greenwood city                                                 5
sector 12                                                      4
vishnu garden                                                  4
sector 12a                                                     4
baldev nagar                                                   4
sector 3a                                                      4
sector 105                                                     4
shivaji nagar                                                  4
imt manesar                                                    4
devilal colony                                                 4
shivpuri                                                       4
surya vihar                                                    4
sector 36                                                      4
sector 17                                                      4
dharam colony                                                  4
arjun nagar                                                    4
ravi nagar                                                     4
krishna colony                                                 4
garhi harsaru                                                  4
adarsh nagar                                                   4
sector 45                                                      4
new                                                            4
suncity                                                        4
valley view estate                                             4
bhim nagar                                                     4
madanpuri                                                      4
sector 6                                                       4
a block sushant lok phase 1                                    3
mg road                                                        3
laxmi garden                                                   3
patel nagar                                                    3
maruti kunj                                                    3
sector 27                                                      3
sector 110 a                                                   3
sector 8                                                       3
gandhi nagar                                                   3
shakti nagar                                                   3
sector 23                                                      3
sector 17a                                                     3
sector 88b                                                     3
bhondsi                                                        3
sector 73                                                      3
prem nagar                                                     3
sector 15                                                      3
b block sushant lok phase 1                                    3
sector 17b                                                     3
daulatabad                                                     2
sheetla colony                                                 2
sector 24                                                      2
new palam vihar phase 1                                        2
block a surya vihar                                            2
farukhnagar                                                    2
sispal vihar                                                   2
samaspur                                                       2
golf course road                                               2
rosewood                                                       2
new basti                                                      2
surat nagar                                                    2
hira nagar                                                     2
mohan nagar                                                    2
mayfield garden                                                2
, delhi ncr                                                    2
sector 32                                                      2
new palam vihar phase 2                                        2
sector 15 part 1                                               2
golf course ext road                                           2
rajiv chowk                                                    2
sector-11 sohna                                                2
bissar                                                         2
nars                                                           2
manohar nagar                                                  2
bhawani enclave                                                2
sector-2 sohna                                                 2
lajpat nagar                                                   2
sector 15 part 2                                               2
shanti nagar                                                   2
sohna  road                                                    2
shankar vihar                                                  2
west rajiv nagar                                               2
ambience island                                                2
pratap nagar                                                   2
faridabad road                                                 2
sector 21                                                      2
surat nagar phase 2                                            2
iffco chowk                                                    2
sector 41                                                      2
sushant lok                                                    2
sultanpur                                                      1
gopal nagar, garhi ghasita, sonipat                            1
sector 4 urban estate                                          1
godrej aria , sector 79 ,                                      1
ansal's palam vihar                                            1
ats marigold                                                   1
vir nagar                                                      1
sector 13                                                      1
dhankot                                                        1
sector 37b                                                     1
ram nagar                                                      1
lucknow                                                        1
sai kunj                                                       1
carterpuri village                                             1
pataudi road                                                   1
sector 5 chowk                                                 1
park view                                                      1
mahavir pura                                                   1
om nagar                                                       1
sector-7 hous                                                  1
ashok vihar phase i                                            1
alipur                                                         1
hsiidc plot sector 1 imt manesar                               1
udyog vihar phase 1                                            1
b1 block sector 57                                             1
bhora kalan                                                    1
sector-5 sheetla colony                                        1
saraswati enclave                                              1
laxmna vihar, phase 2                                          1
nirvana country pocket h                                       1
garauli kalan                                                  1
rattan garden                                                  1
sector-5 sohna                                                 1
rajiv colony                                                   1
old delhi road, opp sector-14                                  1
devi lal colony gali no 12 gurgaon nr omkar public school      1
near khandsa road                                              1
khandsa                                                        1
kanahi                                                         1
shivji park colony                                             1
bptp                                                           1
bhimgarh kheri phase 3                                         1
part 3 sector 5                                                1
begampur khatola                                               1
jat colony,fazilpur/taj nagar road                             1
jacobpura near sadar bazar                                     1
block g sector-57                                              1
ashok vihar phase 3                                            1
ravi nager basai road                                          1
naharpur rupa                                                  1
laxman vihar, railway road,                                    1
hno 13 sagar enclave sura                                      1
damdma                                                         1
sadar bazar                                                    1
sector 17c                                                     1
anand garden, sector-105                                       1
near pataudi chowk                                             1
sector 37a                                                     1
near sector 1 market                                           1
acharya puri                                                   1
urban estate, sector 5                                         1
sector 42                                                      1
sector 21a faridabad                                           1
south city                                                     1
sec 3 bhim vihar part 1 bhimgher kheri                         1
huda saraswati vihar                                           1
block h ashok vihar phase iii extension                        1
cyber city                                                     1
civil l                                                        1
new colony, sector 7                                           1
new jyoti park                                                 1
heritage city                                                  1
sector-35 sohna                                                1
kheri                                                          1
v block dlf phase 3                                            1
near euro                                                      1
near nand hospital                                             1
mahalaxmi garden, rajendra place                               1
saroop garden rajendra park                                    1
g block dlf city phase 1                                       1
sector 9b                                                      1
tekchand nagar                                                 1
Name: count, dtype: int64

In [12]:
df['sector'] = df['sector'].str.replace('dharam colony','sector 12')
df['sector'] = df['sector'].str.replace('krishna colony','sector 7')
df['sector'] = df['sector'].str.replace('suncity','sector 54')
df['sector'] = df['sector'].str.replace('prem nagar','sector 13')
df['sector'] = df['sector'].str.replace('mg road','sector 28')
df['sector'] = df['sector'].str.replace('gandhi nagar','sector 28')
df['sector'] = df['sector'].str.replace('laxmi garden','sector 11')
df['sector'] = df['sector'].str.replace('shakti nagar','sector 11')
df['sector'] = df['sector'].str.replace('baldev nagar','sector 7')
df['sector'] = df['sector'].str.replace('shivpuri','sector 7')
df['sector'] = df['sector'].str.replace('garhi harsaru','sector 17')
df['sector'] = df['sector'].str.replace('imt manesar','manesar') ######
df['sector'] = df['sector'].str.replace('adarsh nagar','sector 12')
df['sector'] = df['sector'].str.replace('shivaji nagar','sector 11')
df['sector'] = df['sector'].str.replace('bhim nagar','sector 6')
df['sector'] = df['sector'].str.replace('madanpuri','sector 7')
df['sector'] = df['sector'].str.replace('saraswati vihar','sector 28')
df['sector'] = df['sector'].str.replace('arjun nagar','sector 8')
df['sector'] = df['sector'].str.replace('ravi nagar','sector 9')
df['sector'] = df['sector'].str.replace('vishnu garden','sector 105')
df['sector'] = df['sector'].str.replace('bhondsi','sector 11')
df['sector'] = df['sector'].str.replace('surya vihar','sector 21')
df['sector'] = df['sector'].str.replace('devilal colony','sector 9')
df['sector'] = df['sector'].str.replace('valley view estate','gwal pahari')#####
df['sector'] = df['sector'].str.replace('mehrauli  road','sector 14')
df['sector'] = df['sector'].str.replace('jyoti park','sector 7')
df['sector'] = df['sector'].str.replace('ansal plaza','sector 23')
df['sector'] = df['sector'].str.replace('dayanand colony','sector 6')
df['sector'] = df['sector'].str.replace('sushant lok phase 2','sector 55')
df['sector'] = df['sector'].str.replace('chakkarpur','sector 28')
df['sector'] = df['sector'].str.replace('greenwood city','sector 45')
df['sector'] = df['sector'].str.replace('subhash nagar','sector 12')
df['sector'] = df['sector'].str.replace('sohna road road','sohna road')
df['sector'] = df['sector'].str.replace('malibu town','sector 47')
df['sector'] = df['sector'].str.replace('surat nagar 1','sector 104')
df['sector'] = df['sector'].str.replace('new colony','sector 7')
df['sector'] = df['sector'].str.replace('mianwali colony','sector 12')
df['sector'] = df['sector'].str.replace('jacobpura','sector 12')
df['sector'] = df['sector'].str.replace('rajiv nagar','sector 13')
df['sector'] = df['sector'].str.replace('ashok vihar','sector 3')
df['sector'] = df['sector'].str.replace('dlf phase 1','sector 26')
df['sector'] = df['sector'].str.replace('nirvana country','sector 50')
df['sector'] = df['sector'].str.replace('palam vihar','sector 2')
df['sector'] = df['sector'].str.replace('dlf phase 2','sector 25')
df['sector'] = df['sector'].str.replace('sushant lok phase 1','sector 43')
df['sector'] = df['sector'].str.replace('laxman vihar','sector 4')
df['sector'] = df['sector'].str.replace('dlf phase 4','sector 28')
df['sector'] = df['sector'].str.replace('dlf phase 3','sector 24')
df['sector'] = df['sector'].str.replace('sushant lok phase 3','sector 57')
df['sector'] = df['sector'].str.replace('dlf phase 5','sector 43')
df['sector'] = df['sector'].str.replace('rajendra park','sector 105')
df['sector'] = df['sector'].str.replace('uppals southend','sector 49')
df['sector'] = df['sector'].str.replace('sohna','sohna road')#######
df['sector'] = df['sector'].str.replace('ashok vihar phase 3 extension','sector 5')
df['sector'] = df['sector'].str.replace('south city 1','sector 41')
df['sector'] = df['sector'].str.replace('ashok vihar phase 2','sector 5')
df['sector'] = df['sector'].str.replace('sector 95a','sector 95')
df['sector'] = df['sector'].str.replace('sector 23a','sector 23')
df['sector'] = df['sector'].str.replace('sector 12a','sector 12')
df['sector'] = df['sector'].str.replace('sector 3a','sector 3')
df['sector'] = df['sector'].str.replace('sector 110 a','sector 110')
df['sector'] = df['sector'].str.replace('patel nagar','sector 15')
df['sector'] = df['sector'].str.replace('a block sector 43','sector 43')
df['sector'] = df['sector'].str.replace('maruti kunj','sector 12')
df['sector'] = df['sector'].str.replace('b block sector 43','sector 43')
df['sector'] = df['sector'].str.replace('sector-33 sohna road','sector 33')
df['sector'] = df['sector'].str.replace('sector 1 manesar','manesar')#########
df['sector'] = df['sector'].str.replace('sector 4 phase 2','sector 4')
df['sector'] = df['sector'].str.replace('sector 1a manesar','manesar')#####
df['sector'] = df['sector'].str.replace('c block sector 43','sector 43')
df['sector'] = df['sector'].str.replace('sector 89 a','sector 89')
df['sector'] = df['sector'].str.replace('sector 2 extension','sector 2')
df['sector'] = df['sector'].str.replace('sector 36 sohna road','sector 36')

In [13]:
df.head()

,property_name,property_type,society,sector,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,4 Bedroom House for sale in DLF Phase 4,house,independent,sector 28,4.50,125000.0,360.0,Built Up area: 360 (33.45 sq.m.),4,4,0,not available,"Dlf City Phase 4, Sector 28, DLF Phase 4, Gurg...",4.0,NaN,undefined,NaN,Best in class property available at dlf city p...,"['1 Light', 'No AC', 'No Bed', 'No Chimney', '...",NaN,"['Environment5 out of 5', 'Lifestyle4 out of 5..."
1,3 BHK Flat in Sector 66 Gurgaon,flat,emaar mgf the palm drive,sector 66,2.80,14358.0,1950.0,Super Built up area 1950(181.16 sq.m.)Built Up...,3,3,2,"servant room,study room,pooja room","Sector 66 Gurgaon, Gurgaon, Haryana",12.0,East,0 to 1 Year Old,"['Sector 55-56 Rapid Metro Station', 'HUB 66',...",Emaar palm drive apartment available for sale ...,"['6 Fan', '1 Fridge', '1 Exhaust Fan', '1 Dini...","['Security / Fire Alarm', 'Power Back-up', 'In...","['Green Area5 out of 5', 'Construction4.5 out ..."
2,3 BHK Flat in Sector 104 Gurgaon,flat,hero homes,sector 104,1.90,11249.0,1689.0,Super Built up area 1689(156.91 sq.m.)Carpet a...,3,3,3,pooja room,"Sector 104 Gurgaon, Gurgaon, Haryana",16.0,NaN,Mar 2025,"['Basai Metro Station', 'HUDA Market', 'Dwarka...",Property located bang on dwarka expressway,"['1 Water Purifier', '1 Exhaust Fan', '3 Geyse...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Environment4 out of 5', 'Lifestyle4 out of 5..."
3,5 Bedroom House for sale in Nirvana Country,house,independent,sector 50,10.56,32593.0,3240.0,Plot area 360(301.01 sq.m.),5,5,3,servant room,"Nirvana Country, Gurgaon, Haryana",3.0,NaN,5 to 10 Year Old,"['Radhakrishna Shani Mandir', 'Standard charte...",Urgent for sale\nOn main wide road\nConfirm de...,NaN,"['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
4,2 BHK Flat in Shanti Nagar,flat,ganga apartment,shanti nagar,0.55,3352.0,1641.0,Super Built up area 1700(157.94 sq.m.)Built Up...,2,2,1,not available,"Shanti Nagar, Gurgaon, Haryana",3.0,North-East,5 to 10 Year Old,"['Rajiv Chowk Mosque', 'Hanuman Mandir', 'Stat...","Cash payment can be accepted\nPrime location ,...","['4 Fan', '1 Exhaust Fan', '1 Dining Table', '...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Safety4 out of 5', 'Lifestyle4 out of 5', 'E..."

In [14]:
df['sector'].value_counts()

sector
sohna road                                                   163
sector 102                                                   113
sector 85                                                    110
sector 92                                                    104
sector 69                                                     94
sector 65                                                     90
sector 90                                                     90
sector 81                                                     90
sector 109                                                    88
sector 79                                                     80
sector 33                                                     74
sector 104                                                    73
sector 83                                                     69
sector 37d                                                    68
sector 43                                                     67
sector 86                                                     67
sector 95                                                     66
sector 50                                                     65
sector 89                                                     64
sector 2                                                      63
sector 107                                                    60
sector 108                                                    59
sector 56                                                     57
sector 48                                                     56
sector 70a                                                    54
sector 70                                                     53
sector 37c                                                    52
sector 84                                                     51
sector 26                                                     50
sector 4                                                      49
sector 49                                                     48
sector 67                                                     48
sector 28                                                     46
sector 66                                                     46
sector 103                                                    45
sector 113                                                    43
sector 61                                                     42
sector 25                                                     42
sector 82                                                     42
sector 7                                                      39
sector 106                                                    38
sector 12                                                     37
manesar                                                       33
sector 99a                                                    32
sector 54                                                     31
sector 68                                                     30
sector 77                                                     29
sector 72                                                     29
sector 71                                                     27
sector 57                                                     24
sector 24                                                     24
sector 3                                                      24
sector 112                                                    24
sector 88a                                                    23
sector 14                                                     23
sector 67a                                                    22
sector 105                                                    22
sector 111                                                    22
sector 11                                                     20
sector 22                                                     20
sector 82a                                                    20
sector 110                                                    19
sector 78                                                     19
sector 47                                                     19
gwal pahari                                                   18
sector 74                                                     18
sector 63a                                                    18
sector 91                                                     17
sector 62                                                     17
sector 99                                                     16
sector 60                                                     15
sector 63                                                     15
sector 76                                                     14
sector 55                                                     14
sector 52                                                     14
sector 53                                                     14
sector 9                                                      13
sector 6                                                      13
sector 23                                                     13
sector 46                                                     13
sector 36a                                                    13
sector 93                                                     12
sector 38                                                     12
sector 31                                                     12
sohna road road                                               12
sector 39                                                     12
sector 36                                                     11
sector 41                                                     11
sector 3 phase 3 extension                                    11
sector 13                                                     10
sector 9a                                                     10
sector 3 phase 2                                               9
sector 45                                                      9
sector 59                                                      8
sector 40                                                      8
sector 10a                                                     8
dwarka expressway                                              8
sector 17                                                      8
sector 51                                                      7
sector 8                                                       7
sector 58                                                      7
sector 15                                                      6
sector 5                                                       6
sector 21                                                      6
sector 1                                                       6
sector 30                                                      5
new sector 2                                                   5
sector 80                                                      5
new                                                            4
sector 27                                                      3
sector 17b                                                     3
sector 88b                                                     3
sector 17a                                                     3
sector 73                                                      3
faridabad road                                                 2
ambience island                                                2
pratap nagar                                                   2
surat nagar                                                    2
shankar vihar                                                  2
sohna road  road                                               2
hira nagar                                                     2
sheetla colony                                                 2
new basti                                                      2
sispal vihar                                                   2
sector 15 part 1                                               2
rajiv chowk                                                    2
daulatabad                                                     2
rosewood                                                       2
golf course road                                               2
farukhnagar                                                    2
samaspur                                                       2
new sector 2 phase 1                                           2
sector 15 part 2                                               2
, delhi ncr                                                    2
lajpat nagar                                                   2
west sector 13                                                 2
bissar                                                         2
sushant lok                                                    2
surat nagar phase 2                                            2
iffco chowk                                                    2
sector-11 sohna road                                           2
sector 32                                                      2
nars                                                           2
mayfield garden                                                2
block a sector 21                                              2
new sector 2 phase 2                                           2
bhawani enclave                                                2
mohan nagar                                                    2
manohar nagar                                                  2
golf course ext road                                           2
sector-2 sohna road                                            2
shanti nagar                                                   2
ram nagar                                                      1
vir nagar                                                      1
sai kunj                                                       1
sector 4 urban estate                                          1
gopal nagar, garhi ghasita, sonipat                            1
ats marigold                                                   1
ansal's sector 2                                               1
bptp                                                           1
devi lal colony gali no 12 gurgaon nr omkar public school      1
dhankot                                                        1
garauli kalan                                                  1
sector-7 hous                                                  1
sector 3 phase i                                               1
alipur                                                         1
hsiidc plot manesar                                            1
udyog vihar phase 1                                            1
b1 block sector 57                                             1
bhora kalan                                                    1
sector-5 sheetla colony                                        1
saraswati enclave                                              1
laxmna vihar, phase 2                                          1
sector 50 pocket h                                             1
rattan garden                                                  1
lucknow                                                        1
sector-5 sohna road                                            1
rajiv colony                                                   1
hno 13 sagar enclave sura                                      1
near khandsa road                                              1
khandsa                                                        1
om nagar                                                       1
mahavir pura                                                   1
sector 37b                                                     1
sector 5 chowk                                                 1
pataudi road                                                   1
carterpuri village                                             1
old delhi road, opp sector-14                                  1
part 3 sector 5                                                1
sec 3 bhim vihar part 1 bhimgher kheri                         1
shivji park colony                                             1
block h sector 3 phase iii extension                           1
near sector 1 market                                           1
near pataudi chowk                                             1
sector 4, railway road,                                        1
bhimgarh kheri phase 3                                         1
ravi nager basai road                                          1
block g sector-57                                              1
sector 12 near sadar bazar                                     1
urban estate, sector 5                                         1
south city                                                     1
sector 9b                                                      1
mahasector 11, rajendra place                                  1
kanahi                                                         1
kheri                                                          1
heritage city                                                  1
new sector 7                                                   1
huda sector 28                                                 1
sultanpur                                                      1
godrej aria , sector 79 ,                                      1
park view                                                      1
acharya puri                                                   1
sector 37a                                                     1
g block dlf city phase 1                                       1
cyber city                                                     1
civil l                                                        1
sector 7, sector 7                                             1
sector-35 sohna road                                           1
v block sector 24                                              1
near euro                                                      1
near nand hospital                                             1
saroop garden sector 105                                       1
sector 21a faridabad                                           1
anand garden, sector-105                                       1
sector 42                                                      1
begampur khatola                                               1
jat colony,fazilpur/taj nagar road                             1
sector 3 phase 3                                               1
naharpur rupa                                                  1
damdma                                                         1
sadar bazar                                                    1
sector 17c                                                     1
tekchand nagar                                                 1
Name: count, dtype: int64

In [15]:
#greater than 3 only valuecounts rows i m keeping
a = df['sector'].value_counts()[df['sector'].value_counts() >= 3]

In [18]:
a

sector
sohna road                    163
sector 102                    113
sector 85                     110
sector 92                     104
sector 69                      94
sector 65                      90
sector 90                      90
sector 81                      90
sector 109                     88
sector 79                      80
sector 33                      74
sector 104                     73
sector 83                      69
sector 37d                     68
sector 43                      67
sector 86                      67
sector 95                      66
sector 50                      65
sector 89                      64
sector 2                       63
sector 107                     60
sector 108                     59
sector 56                      57
sector 48                      56
sector 70a                     54
sector 70                      53
sector 37c                     52
sector 84                      51
sector 26                      50
sector 4                       49
sector 49                      48
sector 67                      48
sector 28                      46
sector 66                      46
sector 103                     45
sector 113                     43
sector 61                      42
sector 25                      42
sector 82                      42
sector 7                       39
sector 106                     38
sector 12                      37
manesar                        33
sector 99a                     32
sector 54                      31
sector 68                      30
sector 77                      29
sector 72                      29
sector 71                      27
sector 57                      24
sector 24                      24
sector 3                       24
sector 112                     24
sector 88a                     23
sector 14                      23
sector 67a                     22
sector 105                     22
sector 111                     22
sector 11                      20
sector 22                      20
sector 82a                     20
sector 110                     19
sector 78                      19
sector 47                      19
gwal pahari                    18
sector 74                      18
sector 63a                     18
sector 91                      17
sector 62                      17
sector 99                      16
sector 60                      15
sector 63                      15
sector 76                      14
sector 55                      14
sector 52                      14
sector 53                      14
sector 9                       13
sector 6                       13
sector 23                      13
sector 46                      13
sector 36a                     13
sector 93                      12
sector 38                      12
sector 31                      12
sohna road road                12
sector 39                      12
sector 36                      11
sector 41                      11
sector 3 phase 3 extension     11
sector 13                      10
sector 9a                      10
sector 3 phase 2                9
sector 45                       9
sector 59                       8
sector 40                       8
sector 10a                      8
dwarka expressway               8
sector 17                       8
sector 51                       7
sector 8                        7
sector 58                       7
sector 15                       6
sector 5                        6
sector 21                       6
sector 1                        6
sector 30                       5
new sector 2                    5
sector 80                       5
new                             4
sector 27                       3
sector 17b                      3
sector 88b                      3
sector 17a                      3
sector 73                       3
Name: count, dtype: int64

In [19]:
a.index

Index(['sohna road', 'sector 102', 'sector 85', 'sector 92', 'sector 69',
       'sector 65', 'sector 90', 'sector 81', 'sector 109', 'sector 79',
       ...
       'sector 1', 'sector 30', 'new sector 2', 'sector 80', 'new',
       'sector 27', 'sector 17b', 'sector 88b', 'sector 17a', 'sector 73'],
      dtype='object', name='sector', length=114)

In [20]:
df = df[df['sector'].isin(a.index)]

In [21]:
df['sector'].value_counts()

sector
sohna road                    163
sector 102                    113
sector 85                     110
sector 92                     104
sector 69                      94
sector 81                      90
sector 90                      90
sector 65                      90
sector 109                     88
sector 79                      80
sector 33                      74
sector 104                     73
sector 83                      69
sector 37d                     68
sector 43                      67
sector 86                      67
sector 95                      66
sector 50                      65
sector 89                      64
sector 2                       63
sector 107                     60
sector 108                     59
sector 56                      57
sector 48                      56
sector 70a                     54
sector 70                      53
sector 37c                     52
sector 84                      51
sector 26                      50
sector 4                       49
sector 49                      48
sector 67                      48
sector 66                      46
sector 28                      46
sector 103                     45
sector 113                     43
sector 82                      42
sector 61                      42
sector 25                      42
sector 7                       39
sector 106                     38
sector 12                      37
manesar                        33
sector 99a                     32
sector 54                      31
sector 68                      30
sector 77                      29
sector 72                      29
sector 71                      27
sector 24                      24
sector 3                       24
sector 112                     24
sector 57                      24
sector 14                      23
sector 88a                     23
sector 105                     22
sector 111                     22
sector 67a                     22
sector 11                      20
sector 22                      20
sector 82a                     20
sector 78                      19
sector 47                      19
sector 110                     19
sector 63a                     18
gwal pahari                    18
sector 74                      18
sector 62                      17
sector 91                      17
sector 99                      16
sector 63                      15
sector 60                      15
sector 53                      14
sector 76                      14
sector 52                      14
sector 55                      14
sector 9                       13
sector 23                      13
sector 46                      13
sector 36a                     13
sector 6                       13
sector 31                      12
sector 93                      12
sohna road road                12
sector 39                      12
sector 38                      12
sector 36                      11
sector 41                      11
sector 3 phase 3 extension     11
sector 9a                      10
sector 13                      10
sector 45                       9
sector 3 phase 2                9
sector 40                       8
sector 10a                      8
dwarka expressway               8
sector 17                       8
sector 59                       8
sector 51                       7
sector 8                        7
sector 58                       7
sector 15                       6
sector 21                       6
sector 5                        6
sector 1                        6
sector 80                       5
sector 30                       5
new sector 2                    5
new                             4
sector 73                       3
sector 27                       3
sector 88b                      3
sector 17a                      3
sector 17b                      3
Name: count, dtype: int64

In [22]:
df[df['sector'] == 'new']

,property_name,property_type,society,sector,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
276,2 BHK Flat in New Gurgaon,flat,green court,new,0.38,5507.0,690.0,Carpet area: 690 (64.1 sq.m.),2,2,1,not available,"New Gurgaon, Gurgaon, Haryana",7.0,NaN,Under Construction,"['Ing bank ATM', 'Dcb bank ATM', 'Indus ind ba...",We are the proud owners of this 2 bhk apartmen...,[],"['Intercom Facility', 'Lift(s)', 'Maintenance ...",NaN
659,2 BHK Flat in New Gurgaon,flat,takshila heights sector 37 c,new,0.67,5583.0,1200.0,Super Built up area 1200(111.48 sq.m.),2,2,2,not available,"New Gurgaon, Gurgaon, Haryana",3.0,NaN,1 to 5 Year Old,"['Shri Balaji Hospital and Trauma Center', 'S....",Check out this 2 bhk apartment for sale in tak...,[],"['Lift(s)', 'Swimming Pool', 'Visitor Parking'...",NaN
2656,4 BHK Flat in New Gurgaon,flat,sare homes,new,0.85,4786.0,1776.0,Super Built up area 1776(165 sq.m.),4,4,3,not available,"New Gurgaon, Gurgaon, Haryana",3.0,NaN,5 to 10 Year Old,"['Columbia Asia Hospital', 'Apex Multi Special...",Located in the popular residential address of ...,[],NaN,NaN
3096,4 BHK Flat in New Gurgaon,flat,dlf 76,new,4.00,11428.0,3500.0,Carpet area: 3500 (325.16 sq.m.),4,4,2,"study room,servant room","New Gurgaon, Gurgaon, Haryana",4.0,NaN,Jun 2027,"['Shri Balaji Hospital and Trauma Center', 'S....",This lovely 4 bhk apartment/flat in new gurgao...,"['6 Wardrobe', '1 Fridge', '8 Fan', '1 Exhaust...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...",NaN

In [23]:
df.loc[276,'sector'] = 'sector 90'
df.loc[659,'sector'] = 'sector 37'
df.loc[2656,'sector'] = 'sector 92'
df.loc[3096	,'sector'] = 'sector 76'

In [24]:
df[df['sector'] == 'new']

Empty DataFrame
Columns: [property_name, property_type, society, sector, price, price_per_sqft, area, areaWithType, bedRoom, bathroom, balcony, additionalRoom, address, floorNum, facing, agePossession, nearbyLocations, description, furnishDetails, features, rating]
Index: []

In [25]:
df[df['sector'] == 'new sector 2']

,property_name,property_type,society,sector,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
982,2 BHK Flat in New Palam Vihar,flat,my home,new sector 2,0.22,4400.0,500.0,Carpet area: 500 (46.45 sq.m.),2,2,1,not available,"New Palam Vihar, Gurgaon, Haryana",1.0,NaN,0 to 1 Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...",Cctv surveillance are provided here. There is ...,"['3 Fan', '1 Exhaust Fan', '15 Light', '1 Modu...",NaN,"['Safety4 out of 5', 'Lifestyle4 out of 5', 'E..."
2702,2 BHK Flat in New Palam Vihar,flat,ompee k s residency,new sector 2,1.60,26936.0,594.0,Carpet area: 66 (55.18 sq.m.),2,2,2,not available,"New Palam Vihar, Gurgaon, Haryana",1.0,NaN,1 to 5 Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...",We are the proud owners of this 2 bhk apartmen...,NaN,NaN,"['Environment4 out of 5', 'Safety4 out of 5', ..."
2879,2 BHK Flat in New Palam Vihar,flat,my home,new sector 2,0.28,3166.0,884.0,Carpet area: 900 (83.61 sq.m.),2,1,1,others,"F 150/b, New Palam Vihar, Gurgaon, Haryana",2.0,NaN,1 to 5 Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...","2 bhk room with wooden coverd ,1 drawing room,...","['3 Wardrobe', '5 Light', '1 Chimney', '1 Modu...","['Water Storage', 'Park']","['Environment4 out of 5', 'Safety4 out of 5', ..."
3006,2 Bedroom House for sale in New Palam Vihar,house,my home,new sector 2,0.34,12592.0,270.0,Plot area 270(25.08 sq.m.),2,2,2,not available,"Ez-19 A, New Palam Vihar, Gurgaon, Haryana",3.0,West,5 to 10 Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...",There are availability of various facilities l...,"['1 Wardrobe', '3 Fan', '6 Light', 'No AC', 'N...","['Water Storage', 'Park', 'Visitor Parking']","['Environment4 out of 5', 'Lifestyle4 out of 5..."
3147,3 Bedroom House for sale in New Palam Vihar,house,independent,new sector 2,1.00,8796.0,1137.0,Plot area 120(100.34 sq.m.)Built Up area: 120 ...,3,2,2,pooja room,"Q-148, New Palam Vihar, Phase-2, Near Royal Oa...",1.0,North,10+ Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...","Ground and first floor, Ground floor: Ground f...",NaN,NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."

In [26]:
df.loc[[982,2702,2879,3006,3147],'sector'] = 'sector 110'

In [27]:
df[df['sector'] == 'new sector 2']

Empty DataFrame
Columns: [property_name, property_type, society, sector, price, price_per_sqft, area, areaWithType, bedRoom, bathroom, balcony, additionalRoom, address, floorNum, facing, agePossession, nearbyLocations, description, furnishDetails, features, rating]
Index: []

In [28]:
df.shape

(3796, 21)

In [29]:
df.duplicated().sum()

0

In [30]:
df.head()

,property_name,property_type,society,sector,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,4 Bedroom House for sale in DLF Phase 4,house,independent,sector 28,4.50,125000.0,360.0,Built Up area: 360 (33.45 sq.m.),4,4,0,not available,"Dlf City Phase 4, Sector 28, DLF Phase 4, Gurg...",4.0,NaN,undefined,NaN,Best in class property available at dlf city p...,"['1 Light', 'No AC', 'No Bed', 'No Chimney', '...",NaN,"['Environment5 out of 5', 'Lifestyle4 out of 5..."
1,3 BHK Flat in Sector 66 Gurgaon,flat,emaar mgf the palm drive,sector 66,2.80,14358.0,1950.0,Super Built up area 1950(181.16 sq.m.)Built Up...,3,3,2,"servant room,study room,pooja room","Sector 66 Gurgaon, Gurgaon, Haryana",12.0,East,0 to 1 Year Old,"['Sector 55-56 Rapid Metro Station', 'HUB 66',...",Emaar palm drive apartment available for sale ...,"['6 Fan', '1 Fridge', '1 Exhaust Fan', '1 Dini...","['Security / Fire Alarm', 'Power Back-up', 'In...","['Green Area5 out of 5', 'Construction4.5 out ..."
2,3 BHK Flat in Sector 104 Gurgaon,flat,hero homes,sector 104,1.90,11249.0,1689.0,Super Built up area 1689(156.91 sq.m.)Carpet a...,3,3,3,pooja room,"Sector 104 Gurgaon, Gurgaon, Haryana",16.0,NaN,Mar 2025,"['Basai Metro Station', 'HUDA Market', 'Dwarka...",Property located bang on dwarka expressway,"['1 Water Purifier', '1 Exhaust Fan', '3 Geyse...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Environment4 out of 5', 'Lifestyle4 out of 5..."
3,5 Bedroom House for sale in Nirvana Country,house,independent,sector 50,10.56,32593.0,3240.0,Plot area 360(301.01 sq.m.),5,5,3,servant room,"Nirvana Country, Gurgaon, Haryana",3.0,NaN,5 to 10 Year Old,"['Radhakrishna Shani Mandir', 'Standard charte...",Urgent for sale\nOn main wide road\nConfirm de...,NaN,"['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
5,4 Bedroom House for sale in Shivaji Nagar,house,not applicable,sector 11,2.20,12222.0,1800.0,Plot area 1800(167.23 sq.m.),4,3,2,"pooja room,study room",NaN,1.0,South,10+ Year Old,"['Rajiv Chowk Mosque', 'Hanuman Mandir', 'Hdfc...",We are proud owners of house/villa available f...,[],"['Private Garden / Terrace', 'Park', 'Visitor ...","['Environment4 out of 5', 'Lifestyle4 out of 5..."

In [31]:
# features to drop -> property_name, address, description, rating
df.drop(columns=['property_name', 'address', 'description', 'rating'],inplace=True)# sector is created , no need for extras col.

In [34]:
df.sample(5)

,property_type,society,sector,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,floorNum,facing,agePossession,nearbyLocations,furnishDetails,features
3869,flat,ats kocoon,sector 109,1.68,9627.0,1745.0,Super Built up area 1745(162.12 sq.m.),3,3,3,not available,8.0,North-East,1 to 5 Year Old,"['Jagdish Super Market', 'Dwarka', 'Euro Inter...",[],"['Centrally Air Conditioned', 'Security / Fire..."
2743,flat,imperia the esfera,sector 37c,0.86,4886.0,1760.0,Super Built up area 1760(163.51 sq.m.),3,3,2,others,0.0,NaN,0 to 1 Year Old,"['Approved Sector 37 Mero Station', 'Esplanade...",NaN,"['Feng Shui / Vaastu Compliant', 'Lift(s)', 'M..."
2672,flat,vatika the seven lamps,sector 82,0.86,6022.0,1428.0,Super Built up area 1430(132.85 sq.m.),2,2,2,study room,12.0,East,1 to 5 Year Old,"['SS Omnia Mall', 'Golf Course Ext Rd', 'Knowl...","['2 Wardrobe', '5 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Feng Shui / Vaastu ..."
1638,flat,signature global synera,sector 81,0.39,6500.0,600.0,Carpet area: 600 (55.74 sq.m.),2,2,2,not available,6.0,South-West,1 to 5 Year Old,"['Sapphire 83 Mall', 'Delhi Jaipur Expressway'...",NaN,"['Lift(s)', 'Maintenance Staff', 'Park', 'Pipe..."
1566,flat,bptp terra,sector 37d,1.67,7622.0,2191.0,Super Built up area 2191(203.55 sq.m.)Built Up...,4,4,3,not available,11.0,West,1 to 5 Year Old,"['Airia Mall', 'Dwarka Expressway', 'Golf Cour...","['7 Fan', '18 Light', '5 AC', '1 Chimney', '1 ...","['Centrally Air Conditioned', 'Water purifier'..."

In [35]:
df.duplicated().sum()

122

In [37]:
df.drop_duplicates(inplace= True, ignore_index = True)

In [38]:
df.duplicated().sum()

0

In [39]:
df.shape

(3674, 17)

In [40]:
df.to_csv('gurgaon_properties_cleaned_v1.csv',index=False)